# -*- coding: utf-8 -*-
"""Endpoint (khóa ngắn, số E sinh tự động theo thứ tự) + bảng mã lỗi (124 mã của BE).

Mỗi endpoint của BE phải xuất hiện đúng 1 lần ở ENDPOINTS (kể cả "không dùng" có lý do).
build.py đối chiếu với controller thật: thiếu hoặc thừa đều fail.
"""

BASE = "Mọi đường dẫn bắt đầu bằng `/api`. Phản hồi (trừ ảnh PNG, SSE, redirect) bọc trong `{ success, code, message, data }`."

# key, method, path, auth, owner, note
ENDPOINTS = [
    # ---------------- Auth (A) ----------------
    ("auth.login", "POST", "/auth/login", "public", "A", "Body `{email,password}`. Trả `accessToken, email, role` (thiếu `fullName`, `phoneNumber`); set cookie refresh. Dùng `role` để chọn vỏ giao diện."),
    ("auth.register", "POST", "/auth/register", "public", "A", "Gửi OTP 6 số tới email. Body `{fullName,email,phoneNumber,password,confirmPassword}`. Chỉ tạo tài khoản DRIVER."),
    ("auth.register_verify", "POST", "/auth/register/verify", "public", "A", "Query `otp=`; body như `register`. 201, đã đăng nhập."),
    ("auth.refresh", "POST", "/auth/refresh", "cookie", "A", "Không body, cần cookie `refresh_token`. Thiếu cookie → 401 `REFRESH_TOKEN_MISSING`."),
    ("auth.logout", "POST", "/auth/logout", "cookie", "A", "Thu hồi refresh token. Luôn xóa token cục bộ dù lỗi."),
    ("auth.me", "GET", "/auth/me", "Bearer", "A", "`{id, fullName, email, phoneNumber, role}`. Hồ sơ của nhân viên/quản lý/quản trị (chỉ xem). Không token → 500 (G-13)."),
    ("auth.forgot", "POST", "/auth/forgot-password", "public", "A", "Body `{email}`, gửi OTP."),
    ("auth.verify_otp", "POST", "/auth/verify-otp", "public", "A", "Body `{email, otp}`."),
    ("auth.reset", "POST", "/auth/reset-password", "public", "A", "Body `{email, newPassword}` (6–100 ký tự)."),
    ("auth.change_pw", "PUT", "/auth/change-password", "Bearer", "A", "Body `{oldPassword,newPassword,confirmPassword}`. Mọi vai trò."),
    ("drv.profile_get", "GET", "/drivers/profile", "DRIVER", "A", "`{id,fullName,email,phoneNumber,roleName,status,provider}`."),
    ("drv.profile_put", "PUT", "/drivers/profile", "DRIVER", "A", "Body `{fullName, phoneNumber}`; luôn gửi đủ 2 trường (R-A12)."),
    # ---------------- Xe & giấy tờ ----------------
    ("veh.list", "GET", "/vehicle", "DRIVER", "A", "Chỉ xe `ACTIVE` của mình: `{id,numberPlate,vehicleTypeName,status}` (thiếu `vehicleTypeId`, `verificationStatus`, G-10)."),
    ("veh.add", "POST", "/vehicle/add", "DRIVER", "A", "Body `{numberPlate, vehicleTypeId}`. 201."),
    ("veh.delete", "DELETE", "/vehicle/{vehicleId}", "DRIVER", "A", "Xóa mềm; bị chặn theo R-A08."),
    ("veh.type_save", "POST", "/vehicle/admin/vehicleType/save", "ADMIN", "B", "Chỉ thêm mới (không sửa): `{vehicleTypeName, areaPerVehicle}` → `{id, vehicleTypeName, areaPerVehicle}` (R-B15)."),
    ("doc.upload", "POST", "/drivers/vehicle-documents/{vehicleId}/documents", "DRIVER", "A", "`multipart/form-data`: `documentType` (REGISTRATION_FRONT/BACK) + file `file`."),
    ("doc.view_url", "GET", "/drivers/vehicle-documents/documents/{documentId}/view-url", "DRIVER", "A", "URL tạm xem ảnh (chỉ bản `current`)."),
    ("ver.my_status", "GET", "/vehicle-verification/{vehicleId}/my-status", "DRIVER", "A", "`{verificationStatus, verifiedAt, verificationRejectReason, currentDocuments[]}`."),
    ("ver.pending", "GET", "/vehicle-verification/pending", "MANAGER, ADMIN", "C", "Danh sách xe `PENDING` chờ duyệt."),
    ("ver.detail", "GET", "/vehicle-verification/{vehicleId}", "MANAGER, ADMIN", "C", "Chi tiết xác minh một xe."),
    ("ver.view_url", "GET", "/vehicle-verification/documents/{documentId}/view-url", "MANAGER, ADMIN", "C", "URL tạm xem ảnh giấy tờ để duyệt."),
    ("ver.approve", "PATCH", "/vehicle-verification/{vehicleId}/approve", "MANAGER, ADMIN", "C", "Chỉ từ `PENDING` → `VERIFIED`."),
    ("ver.reject", "PATCH", "/vehicle-verification/{vehicleId}/reject", "MANAGER, ADMIN", "C", "Body `{rejectReason}` bắt buộc; chỉ từ `PENDING` → `REJECTED`."),
    # ---------------- Cấu hình ----------------
    ("fee.list", "GET", "/fee-policies", "public", "B", "Mọi chính sách (kể cả `INACTIVE`): lọc `status==ACTIVE`. Có `vehicleTypeId/Name, hourlyRate, nightMultiplier, wrongZoneFee`."),
    ("fee.active", "GET", "/fee-policies/active", "Bearer", "B", "Query `vehicleTypeId`: một chính sách ACTIVE."),
    ("fee.save", "POST", "/fee-policies/save", "MANAGER, ADMIN", "B", "Tạo chính sách đầu tiên cho một loại xe `{vehicleTypeId,hourlyRate,nightMultiplier,wrongZoneFee}`."),
    ("fee.update", "POST", "/fee-policies/{id}", "MANAGER, ADMIN", "B", "Cập nhật = tạo bản mới ACTIVE, bản cũ thành INACTIVE."),
    ("cfg.slots", "GET", "/parking-config/slots", "Bearer", "B", "`slot1Start..slot4End` dạng `HH:mm:ss`; `00:00:00` ở slot 4 nghĩa là 24:00."),
    ("cfg.get", "GET", "/parking-config", "MANAGER, ADMIN", "B", "Toàn bộ cấu hình: tên bãi, địa chỉ, số tầng, diện tích, số khu, hạn mức %, 4 slot."),
    ("cfg.update", "PUT", "/parking-config/update", "ADMIN", "B", "Body `{buildingName,address,slot1..4Start/End,reservationQuotaPercent}`."),
    ("cfg.manager_update", "PUT", "/parking-config/manager/update", "MANAGER", "B", "Manager chỉ đổi 4 slot + hạn mức (đủ 8 mốc giờ bắt buộc)."),
    ("cfg.create", "POST", "/parking-config/create", "ADMIN", "B", "**Không dùng**: controller thiếu `@RequestBody` nên không nhận JSON (G-23). Cấu hình đã có sẵn từ dữ liệu seed."),
    # ---------------- Đặt chỗ ----------------
    ("rsv.create", "POST", "/reservations/create", "DRIVER", "B", "Body `{vehicleId, reservationDate: yyyy-MM-dd, slotOrders: [..], payNow?}` → `PENDING` (`payNow=true`: hạn riêng 15 phút; trả sau: giữ tới `releaseAt`). Cờ `payNow` và các mã `PENDING_LIMIT_EXCEEDED`, `RESERVATION_RELEASE_TOO_SOON` là **đề xuất** (T-B7)."),
    ("rsv.pay", "POST", "/reservations/{reservationId}/payment", "DRIVER", "B", "Trả `{reservationId,paymentId,amount,paymentUrl}`. Gọi được bất kỳ lúc nào trước `releaseAt` (không còn cửa sổ 15 phút từ lúc bấm); sau đó `RESERVATION_EXPIRED`. Không kiểm lại hạn mức. `paymentExpiredAt` của BE hiện tại sẽ bỏ (G-35)."),
    ("rsv.my", "GET", "/reservations/my", "DRIVER", "B", "Danh sách `{id,reservationCode,plateNumber,vehicleTypeName,reservationStartTime,reservationEndTime,status,reservationFee}`. `releaseAt` app tự tính = `reservationStartTime + 15 phút`."),
    ("rsv.my_detail", "GET", "/reservations/my/{reservationId}", "DRIVER", "B", "Chi tiết `{reservationCode,status,reservedStartAt,reservedEndAt,reservationFee,slotOrdersSnapshot,holdApplied,...}` (`paymentExpiredAt` của BE hiện tại sẽ bỏ, `releaseAt` tự tính)."),
    ("rsv.cancel", "PATCH", "/reservations/my/{reservationId}/cancel", "DRIVER", "B", "Hiện chỉ `PENDING`. **Hợp đồng đề xuất (G-02)**: thêm `CONFIRMED` trước giờ bắt đầu, body `{reason, destinationBank, destinationAccount, destinationHolder}` (bắt buộc với `CONFIRMED`; số tài khoản 6–20 chữ số, sai trả 400); trả `{status: CANCELLED, refundRequest: {id, amount, status: REQUESTED, destinationMasked}}` (không hoàn tiền ngay, chờ quản lý duyệt)."),
    ("rsv.cb", "GET", "/reservations/vnPay-callback", "BE nội bộ", "B", "VNPay quay về, BE 302 sang trang web. App không gọi; WebView chặn `/payment-success`, `/payment-fail`. Đang bị chặn bảo mật (G-01)."),
    ("rsv.all", "GET", "/reservations", "STAFF, MANAGER", "D", "Toàn bộ đặt chỗ, **không phân trang** (G-22): lọc/tìm phía app."),
    ("rsv.by_code", "GET", "/reservations/code/{reservationCode}", "STAFF, MANAGER", "D", "Tra cứu khi quét mã RSV-…: `{reservationId,customerId,plateNumber,vehicleType,status,reservationStartTime,reservationEndTime,reservationFee,...}`."),
    ("rsv.by_id", "GET", "/reservations/{reservationId}", "STAFF, MANAGER", "D", "Chi tiết một đặt chỗ cho nhân viên/quản lý."),
    # ---------------- Gói thành viên ----------------
    ("mem.plans_available", "GET", "/membership/plans/available", "DRIVER", "C", "Query `vehicleId`: gói `ACTIVE` đúng loại xe. Không kiểm tra chủ xe."),
    ("mem.plans_public", "GET", "/membership/plans", "public", "D", "Mọi gói kể cả `INACTIVE` (lọc phía app). Dùng cho Bảng giá."),
    ("mem.preview", "POST", "/membership/subscription/purchase-preview", "DRIVER", "C", "Body `{vehicleId, membershipPlanId, scheduledStartAt?}` → xem trước, có `recommendFullTime`."),
    ("mem.create", "POST", "/membership/subscription", "DRIVER", "C", "Cùng body → `{subscriptionId, amount, paymentExpiresAt, status:PENDING_PAYMENT}`."),
    ("mem.pay", "POST", "/membership/subscription/{subscriptionId}/payment", "DRIVER", "C", "Trả `{subscriptionId,paymentId,vnpayPaymentUrl}`. Gọi lại được trong hạn."),
    ("mem.my", "GET", "/membership/subscription/my", "DRIVER", "C", "Danh sách mới nhất trước, trạng thái hiệu lực + `usableNow`."),
    ("mem.detail", "GET", "/membership/subscription/{subscriptionId}", "DRIVER", "C", "Chi tiết kèm `membershipCode, usableNow, entryCountToday, paymentStatus, paymentExpiresAt`. Dùng để poll sau thanh toán."),
    ("mem.cancel", "PATCH", "/membership/subscription/{subscriptionId}/cancel", "DRIVER", "C", "Chỉ `PENDING_PAYMENT`."),
    ("mem.renew", "POST", "/membership/subscription/{subscriptionId}/renew", "DRIVER", "C", "Tạo gói mới + trả URL VNPay (purpose `RENEWAL`)."),
    ("mem.up_preview", "POST", "/membership/subscription/upgrade/preview", "DRIVER", "C", "Body `{vehicleId, fullTimePlanId}` → `{creditItems[], totalCredit, payableAmount, quoteExpiresAt}`."),
    ("mem.upgrade", "POST", "/membership/subscription/upgrade", "DRIVER", "C", "Cùng body → `{changeId, paymentId, vnpayPaymentUrl}`; báo giá đóng băng lúc tạo."),
    ("mem.replacement", "GET", "/membership/subscription/{subscriptionId}/replacement", "DRIVER", "C", "Gói bị thay thế → thông tin gói thay; chưa bị thay thì `data=null`."),
    ("mem.cb", "GET", "/membership/subscription/vnPay-callback", "BE nội bộ", "C", "Như `rsv.cb`. Đã `permitAll`."),
    ("mem.plan_get", "GET", "/membership/plans/{id}", "ADMIN, MANAGER", "C", "Một gói."),
    ("mem.plan_create", "POST", "/membership/plans", "ADMIN, MANAGER", "C", "Body `{name,vehicleTypeId,description,planType,timeSlotId,durationInMonths,price}`."),
    ("mem.plan_update", "PUT", "/membership/plans/{id}", "ADMIN, MANAGER", "C", "Cùng body; không kiểm tra lại tính duy nhất (G-24)."),
    ("mem.plan_status", "PATCH", "/membership/plans/{id}/status", "ADMIN, MANAGER", "C", "Body `{status: ACTIVE|INACTIVE}` (ngừng bán = INACTIVE)."),
    ("mem.slot_list", "GET", "/membership/time-slots", "ADMIN, MANAGER", "C", "Các khung giờ của gói."),
    ("mem.slot_get", "GET", "/membership/time-slots/{id}", "ADMIN, MANAGER", "C", "Một khung giờ."),
    ("mem.slot_create", "POST", "/membership/time-slots", "ADMIN, MANAGER", "C", "Body `{code,displayName,fullDayAccess,accessStartTime,accessEndTime,status}`."),
    ("mem.slot_update", "PUT", "/membership/time-slots/{id}", "ADMIN, MANAGER", "C", "Cùng body."),
    ("mem.slot_status", "PATCH", "/membership/time-slots/{id}/status", "ADMIN, MANAGER", "C", "Body `{status}`; khung đang có gói ACTIVE dùng thì không tắt được."),
    ("mem.subscribers", "GET", "/membership/subscription/subscribers", "MANAGER, ADMIN", "C", "Tóm tắt từng người đăng ký, mới nhất trước."),
    ("mem.subscriber_subs", "GET", "/membership/subscription/subscribers/{userId}/subscriptions", "MANAGER, ADMIN", "C", "Các gói của một người; trạng thái **thô** (G-24)."),
    ("mem.staff_preview", "GET", "/membership/subscription/preview/{membershipCode}", "STAFF, MANAGER", "D", "Tra cứu gói khi quét mã MBS-…: `usableNow`, khung giờ, biển số."),
    # ---------------- Giao dịch ----------------
    ("tx.my", "GET", "/transactions/my", "DRIVER", "D", "Query `page,size`. `PageResponse{content,page,size,totalElements,totalPages}`, mới nhất trước."),
    ("tx.my_detail", "GET", "/transactions/my/{id}", "DRIVER", "D", "`id` là Payment id. Có `reservationDetail/membershipDetail/parkingFeeDetail`."),
    ("tx.all", "GET", "/transactions", "STAFF, MANAGER", "C", "Toàn bộ giao dịch (Manager giám sát)."),
    ("tx.detail", "GET", "/transactions/{id}", "STAFF, MANAGER", "C", "Chi tiết một giao dịch."),
    # ---------------- Thông báo ----------------
    ("ntf.list", "GET", "/notifications", "Bearer", "D", "Query `page,size`; `page` từ 0."),
    ("ntf.unread", "GET", "/notifications/unread-count", "Bearer", "D", "`data` là số."),
    ("ntf.read", "PATCH", "/notifications/{id}/read", "Bearer", "D", "Đánh dấu đã đọc."),
    ("ntf.read_all", "PATCH", "/notifications/read-all", "Bearer", "D", "Đánh dấu tất cả."),
    ("ntf.stream", "GET", "/notifications/stream", "query token", "D", "SSE, token ở query `?token=`. Đóng sau ~60 giây, nối lại (R-D02)."),
    # ---------------- Cổng bãi (nhân viên) ----------------
    ("pk.checkin_walkin", "POST", "/parking/check-in", "STAFF, MANAGER", "D", "Xe vãng lai `{numberPlate, vehicleTypeId, floorId?}` → `{ticketCode,numberPlate,vehicleTypeName,floorName,zoneName,checkInTime,status}`."),
    ("pk.checkin_rsv", "POST", "/parking/check-in/reservation", "STAFF, MANAGER", "D", "`{reservationCode, numberPlate, floorId?, collectCash?}`. `collectCash` là **đề xuất** (G-36): chỉ gửi khi nhân viên bấm \"Đã nhận tiền mặt\" (R-D19); ghi nhận thu tiền và check-in nguyên tử cho đặt chỗ `PENDING`."),
    ("pk.checkin_mem", "POST", "/parking/check-in/membership", "STAFF, MANAGER", "D", "`{membershipCode, numberPlate, floorId?}`."),
    ("pk.floor_gate", "GET", "/parking/check-in/floor", "không cần JWT", "D", "Query `ticketCode,currentFloorId`: đúng tầng → phiên `ACTIVE`; sai tầng → `correctFloor=false` kèm hướng dẫn; vé đã `ACTIVE` → lỗi `VEHICLE_ALREADY_PARKING`. Không cần đăng nhập (G-25)."),
    ("pk.checkout_preview", "GET", "/parking/check-out/preview", "STAFF, MANAGER", "D", "Query `keyword`: mã vé hoặc biển số, khớp chính xác phân biệt hoa/thường, chỉ phiên `ACTIVE` → `{currentFeeEstimate, wrongZoneFee, ...}`."),
    ("pk.checkout", "POST", "/parking/check-out", "STAFF, MANAGER", "D", "`{ticketCode, paymentMethod: CASH|VN_PAY}` → `{totalFee, paymentStatus, vnPayPaymentUrl?}`. Với `CASH`, app chỉ gọi sau khi nhân viên bấm \"Đã nhận tiền mặt\" (R-D19)."),
    ("pk.exit_gate", "GET", "/parking/check-out/exit-gate", "không cần JWT", "D", "Query `ticketCode,currentFloorId`: đọc, cho biết xe có được ra ở tầng này không (`canExit`)."),
    ("pk.cb", "GET", "/parking/vnPay-callback", "BE nội bộ", "D", "VNPay phí gửi xe quay về BE rồi redirect web. Chỉ ghi chú."),
    # ---------------- Phiên gửi xe ----------------
    ("ses.current", "GET", "/parking-sessions/current", "STAFF, MANAGER, ADMIN", "D", "Phiên `CHECKED_IN_GATE` + `ACTIVE`, phân trang (size 20, `checkInTime` giảm dần). Không có `floorId`, không có loại xe."),
    ("ses.list", "GET", "/parking-sessions", "STAFF, MANAGER, ADMIN", "C", "Lịch sử, lọc `status,ticketCode,numberPlate,staffEmail,fromDate,toDate`, phân trang. Nhân viên dùng `ticketCode=` để biết vé đang `CHECKED_IN_GATE`, `ACTIVE` hay `COMPLETED`."),
    ("ses.staffs", "GET", "/parking-sessions/staffs", "MANAGER, ADMIN", "C", "Danh sách email nhân viên cho bộ lọc."),
    ("ses.penalty_apply", "PATCH", "/parking-sessions/{ticketCode}/wrong-zone-penalty", "STAFF, MANAGER, ADMIN", "D", "Áp phạt đỗ sai khu (tầng hỗn hợp, phiên ACTIVE)."),
    ("ses.penalty_cancel", "DELETE", "/parking-sessions/{ticketCode}/wrong-zone-penalty", "STAFF, MANAGER, ADMIN", "D", "Hủy phạt đã áp."),
    # ---------------- Tầng, khu ----------------
    ("flr.list", "GET", "/floors", "MANAGER, STAFF, ADMIN", "B", "`{id,floorName,floorType,status,vehicleCapacities[]}`. Nhân viên dùng để chọn tầng."),
    ("flr.get", "GET", "/floors/{id}", "MANAGER, STAFF, ADMIN", "B", "Chi tiết: khu, chính sách, chỗ trống/đang đỗ, tỷ lệ lấp đầy."),
    ("flr.create", "POST", "/floors/create", "MANAGER, ADMIN", "B", "Body `{floorName, description}`; tầng mới ở `MAINTENANCE`."),
    ("flr.info", "PUT", "/floors/information/{id}", "MANAGER, STAFF, ADMIN", "B", "Sửa tên, mô tả."),
    ("flr.status", "PUT", "/floors/status/{id}", "MANAGER, ADMIN", "B", "Body là chuỗi JSON trần `\"ACTIVE\"`."),
    ("flr.config", "POST", "/floors/config/{id}", "MANAGER, ADMIN", "B", "`{floorType, description, floorVehiclePolicies:[{vehicleTypeId, zoneDefinitionIds?}]}`."),
    ("flr.priority", "PATCH", "/floors/{floorId}/vehicle-types/{vehicleTypeId}/priority", "STAFF, MANAGER, ADMIN", "B", "Body `{priorityLevel>=1}`, duy nhất theo loại xe. Trả **204 không có phần thân** (R-B17)."),
    ("zon.list", "GET", "/zones", "MANAGER, ADMIN", "B", "Danh sách định nghĩa khu (A, B, C...)."),
    ("zon.create", "POST", "/zones/create", "MANAGER, ADMIN", "B", "Body `{zoneName}`."),
    ("zon.save", "POST", "/zones/{id}/save", "MANAGER, ADMIN", "B", "Đổi tên khu."),
    # ---------------- Quản trị / thống kê ----------------
    ("adm.drivers", "GET", "/admin/drivers", "ADMIN", "C", "Danh sách tài xế."),
    ("adm.driver", "GET", "/admin/drivers/{id}", "ADMIN", "C", "Chi tiết một tài xế."),
    ("dash.manager", "GET", "/dashboard/manager/dashboard", "MANAGER, ADMIN", "C", "`{totalActiveVehicles, revenue{daily,weekly,monthly}, floorOccupancy[], vehicleTypeUsage[]}`."),
    # ---------------- QR ảnh (app tự sinh QR nên không dùng) ----------------
    ("qr.rsv", "GET", "/qr/reservation/{reservationId}/", "DRIVER", "B", "PNG QR của `reservationCode`. **App không dùng** (R-X09), tự sinh QR."),
    ("qr.mem", "GET", "/qr/subscription/{subscriptionId}/", "DRIVER", "C", "PNG QR của `membershipCode`. **App không dùng**."),
    ("qr.ticket", "GET", "/qr/{ticketCode}", "STAFF, MANAGER, DRIVER", "D", "PNG QR mã vé, không kiểm tra chủ vé (G-04). **App không dùng**."),
]

# Endpoint ĐỀ XUẤT (BE chưa có, thuộc task T-B7). Không đối chiếu với BE; hiển thị đánh dấu "đề xuất".
PROPOSED = [
    ("ref.my", "GET", "/reservations/my/{reservationId}/refund", "DRIVER", "B", "Mảng yêu cầu hoàn tiền của đặt chỗ (mỗi khoản thanh toán tối đa một): `[{id, amount, status: REQUESTED|APPROVED|REJECTED|REFUNDED, reason, decisionNote, requestedAt, decidedAt, refundedAt}]`. Chỉ chủ đặt chỗ; sai chủ trả `RESERVATION_NOT_FOUND`."),
    ("ref.list", "GET", "/refund-requests", "MANAGER, ADMIN", "C", "Query `status`: danh sách yêu cầu kèm mã đặt chỗ, biển số, tên và số điện thoại tài xế, số tiền, `paymentMethod`, mã giao dịch VNPay (`vnpTxnRef`), giờ đã trả, giờ hủy, lý do. Chỉ MANAGER/ADMIN, nhân viên và tài xế nhận 403."),
    ("ref.approve", "PATCH", "/refund-requests/{id}/approve", "MANAGER, ADMIN", "C", "`REQUESTED` → `APPROVED`; đã xử lý rồi trả `REFUND_REQUEST_ALREADY_PROCESSED`."),
    ("ref.reject", "PATCH", "/refund-requests/{id}/reject", "MANAGER, ADMIN", "C", "Body `{decisionNote}` bắt buộc (cùng tên với trường `decisionNote` tài xế đọc); `REQUESTED` → `REJECTED`."),
    ("ref.paid", "PATCH", "/refund-requests/paid", "MANAGER, ADMIN", "C", "Body `{ids: [..], transferSource: BUSINESS|PERSONAL, personalHolderName? (bắt buộc nếu PERSONAL), transferRef, evidenceFileId}` (thiếu mã giao dịch, ảnh biên lai hoặc họ tên chủ tài khoản cá nhân thì 400, không đổi trạng thái; `transferRef` đã dùng cho yêu cầu khác thì cảnh báo trùng): xác nhận **đã chuyển tiền** các yêu cầu `APPROVED` → `REFUNDED` (Payment → `REFUNDED`). Xử lý từng id, trả `{updated: [..], skipped: [{id, reason}]}`: id đã `REFUNDED` coi là thành công, id không phải `APPROVED` bị bỏ qua, không bao giờ lỗi cả lô."),
    ("ref.evidence_upload", "POST", "/refund-requests/evidence", "MANAGER", "C", "Tải **ảnh biên lai** chuyển tiền (multipart `file`, jpg/png, tối đa 5 MB); trả `{evidenceFileId}` để gửi kèm `ref.paid`. Lưu ở kho ảnh sẵn có, chỉ quản lý và quản trị xem."),
    ("pay.cash_summary", "GET", "/payments/cash-summary", "STAFF, MANAGER", "D", "Query `date`, `staffId?`: tiền mặt đã thu theo nhân viên `{staffId, staffName, total, count}`. Nhân viên chỉ thấy phần của mình (R-D18, R-C12)."),
]

# Endpoint ghi nhận nhưng không có màn nào gọi trực tiếp (có lý do rõ)
NOTE_ONLY = {"rsv.cb", "mem.cb", "pk.cb", "cfg.create", "qr.rsv", "qr.mem", "qr.ticket", "mem.plan_get", "mem.slot_get"}

# --------------------------------------------------------------------------
# Mã lỗi: tài xế gặp (D) / nhân viên-quản lý-quản trị gặp (S)
# --------------------------------------------------------------------------
DRIVER_ERRORS = {
    # Auth
    "INVALID_EMAIL_OR_PASSWORD": (401, "Email hoặc mật khẩu không đúng.", "Giữ nguyên form, không xóa email."),
    "EMAIL_ALREADY_EXISTS": (409, "Email này đã được đăng ký.", "Gợi ý chuyển sang Đăng nhập."),
    "PASSWORD_MISMATCH": (400, "Mật khẩu xác nhận không khớp.", "Báo lỗi dưới ô xác nhận."),
    "USER_NOT_FOUND": (404, "Không tìm thấy tài khoản với email này.", "Ở màn Quên mật khẩu."),
    "CUSTOMER_NOT_FOUND": (404, "Không tìm thấy thông tin khách hàng.", "Thông báo chung."),
    "ROLE_NOT_FOUND": (404, "Tài khoản chưa được phân quyền, liên hệ quản lý.", "Thông báo chung."),
    "INVALID_REFRESH_TOKEN": (401, "Phiên đăng nhập không hợp lệ, vui lòng đăng nhập lại.", "Đăng xuất về màn đăng nhập."),
    "REFRESH_TOKEN_EXPIRED": (401, "Phiên đăng nhập đã hết hạn, vui lòng đăng nhập lại.", "Đăng xuất về màn đăng nhập."),
    "REFRESH_TOKEN_REVOKED": (401, "Phiên đăng nhập đã bị thu hồi, vui lòng đăng nhập lại.", "Đăng xuất về màn đăng nhập."),
    "VALIDATION_ERROR": (400, "Dữ liệu chưa hợp lệ.", "Đọc `data{field: message}` và gắn lỗi vào từng ô."),
    "INVALID_OTP": (400, "Mã OTP không đúng.", "Cho nhập lại."),
    "OTP_EXPIRED": (400, "Mã OTP đã hết hạn. Hãy gửi lại mã mới.", "Bật nút Gửi lại mã."),
    "OTP_MAX_ATTEMPTS": (429, "Bạn nhập sai quá 5 lần. Hãy gửi lại mã mới.", "Khóa ô nhập, bật Gửi lại mã."),
    "INVALID_NEW_PASSWORD": (400, "Mật khẩu mới không hợp lệ (6–100 ký tự).", "Báo lỗi ở ô mật khẩu mới."),
    "INVALID_OLD_PASSWORD": (400, "Mật khẩu hiện tại không đúng.", "Báo lỗi ở ô mật khẩu cũ."),
    "INTERNAL_SERVER_ERROR": (500, "Hệ thống đang gặp sự cố, vui lòng thử lại.", "Nút Thử lại."),
    # Xe / giấy tờ
    "VEHICLE_NOT_FOUND": (404, "Không tìm thấy xe.", "Tải lại danh sách xe."),
    "VEHICLE_TYPE_NOT_FOUND": (404, "Không tìm thấy loại xe.", "Tải lại danh sách loại xe."),
    "VEHICLE_ALREADY_PARKING": (409, "Xe đang gửi trong bãi nên chưa thực hiện được thao tác này.", "Giữ nguyên màn."),
    "VEHICLE_NOT_BELONG_TO_CUSTOMER": (403, "Xe này không thuộc tài khoản của bạn.", "Về danh sách xe."),
    "VEHICLE_NUMBER_PLATE_EXISTS": (409, "Biển số này đã tồn tại trong hệ thống.", "Báo ở ô biển số."),
    "VEHICLE_HAS_ACTIVE_RESERVATION": (409, "Xe còn đặt chỗ chưa kết thúc nên chưa xóa được.", "Link tới Đặt chỗ."),
    "VEHICLE_HAS_ACTIVE_MEMBERSHIP": (409, "Xe còn gói thành viên đang hiệu lực/chờ thanh toán nên chưa xóa được.", "Link tới Gói tháng."),
    "VEHICLE_NOT_ACTIVE": (409, "Xe không còn hoạt động.", "Về danh sách xe."),
    "VEHICLE_NOT_VERIFIED": (409, "Xe chưa được xác minh giấy tờ.", "Nút \"Xác minh xe\" mở màn xác minh (R-A11)."),
    "VEHICLE_ALREADY_VERIFIED": (409, "Xe đã được xác minh, không cần gửi lại giấy tờ.", "Tải lại trạng thái."),
    "INVALID_VEHICLE_VERIFICATION_STATUS": (400, "Trạng thái xác minh không hợp lệ cho thao tác này.", "Tải lại trạng thái."),
    "VEHICLE_REQUIRES_CLAIM_PROOF": (400, "Biển số này cần giấy tờ chứng minh quyền sở hữu.", "Thông báo chung, liên hệ quản lý."),
    "VEHICLE_ALREADY_HAS_ACTIVE_MEMBERSHIP": (409, "Xe đã có gói thành viên đang hiệu lực.", "BE khai báo nhưng chưa dùng; vẫn map."),
    "FILE_EMPTY": (400, "Tệp ảnh trống.", "Chọn lại ảnh."),
    "FILE_TOO_LARGE": (400, "Ảnh quá lớn. Hãy chọn ảnh nhỏ hơn.", "Nén lại rồi thử."),
    "INVALID_FILE_TYPE": (400, "Chỉ nhận ảnh JPG, PNG hoặc WEBP.", "Chọn lại ảnh."),
    "FILE_NOT_FOUND": (404, "Không tìm thấy tệp.", "Tải lại màn xác minh."),
    "FILE_UPLOAD_FAILED": (500, "Tải ảnh lên thất bại. Hãy thử lại.", "Nút Thử lại ở đúng mặt ảnh."),
    "FILE_ACCESS_DENIED": (403, "Bạn không có quyền xem tệp này.", "Thông báo chung."),
    # Đặt chỗ
    "RESERVATION_NOT_FOUND": (404, "Không tìm thấy đặt chỗ.", "Về danh sách, tải lại."),
    "RESERVATION_TIME_MUST_BE_IN_FUTURE": (400, "Ngày đặt phải từ hôm nay trở đi.", "Mở lại bộ chọn ngày."),
    "RESERVATION_EXCEEDS_7_DAYS": (400, "Chỉ đặt trước tối đa 7 ngày.", "Mở lại bộ chọn ngày."),
    "INVALID_RESERVATION_DATE": (400, "Ngày đặt không hợp lệ.", "Mở lại bộ chọn ngày."),
    "INVALID_RESERVATION_SLOT": (400, "Khung giờ không hợp lệ.", "Chọn lại slot."),
    "RESERVATION_SLOT_NOT_CONSECUTIVE": (400, "Các khung giờ phải liền nhau.", "Chọn lại slot."),
    "RESERVATION_SLOT_IN_PAST": (400, "Khung giờ này đã qua.", "Chọn slot khác."),
    "ACTIVE_RESERVATION_EXISTS": (409, "Xe này đã có đặt chỗ trùng khung giờ.", "BE không trả id: app tìm đặt chỗ trùng trong danh sách đã tải và hiện link."),
    "RESERVATION_NOT_AVAILABLE": (409, "Khung giờ này đã hết chỗ. Hãy chọn ngày/khung giờ khác.", "Giữ lại lựa chọn, cho đổi."),
    "RESERVATION_QUOTA_FULL": (409, "Hạn mức đặt chỗ trong ngày đã hết.", "BE khai báo nhưng chưa dùng; vẫn map."),
    "RESERVATION_NOT_PENDING": (409, "Đặt chỗ này không còn ở trạng thái chờ thanh toán.", "Tải lại chi tiết."),
    "RESERVATION_EXPIRED": (409, "Đặt chỗ đã hết hạn.", "Tải lại chi tiết, gợi ý đặt mới."),
    "RESERVATION_PAYMENT_EXPIRED": (409, "Đã quá thời gian thanh toán.", "BE khai báo nhưng chưa dùng; vẫn map."),
    "RESERVATION_CANNOT_BE_CANCELLED": (409, "Không thể hủy đặt chỗ này (đã bắt đầu hoặc đã kết thúc).", "Tải lại, ẩn nút Hủy (R-B10)."),
    "PARKING_CONFIG_NOT_FOUND": (404, "Chưa có cấu hình bãi xe.", "Thông báo chung."),
    "FEE_POLICY_NOT_FOUND": (404, "Chưa có bảng giá cho loại xe này.", "Không cho đặt chỗ."),
    # Thanh toán
    "PAYMENT_FAILED": (400, "Thanh toán không thành công.", "Cho Thử thanh toán lại nếu còn hạn."),
    "PAYMENT_ALREADY_EXISTS": (409, "Khoản thanh toán này đã tồn tại.", "Tải lại chi tiết."),
    "PAYMENT_ALREADY_SUCCESS": (409, "Khoản thanh toán này đã thành công.", "Tải lại chi tiết."),
    "PAYMENT_NOT_FOUND": (404, "Không tìm thấy khoản thanh toán.", "Tải lại."),
    "TRANSACTION_NOT_FOUND": (404, "Không tìm thấy giao dịch.", "Về danh sách giao dịch."),
    "TRANSACTION_ACCESS_DENIED": (403, "Bạn không có quyền xem giao dịch này.", "Về danh sách giao dịch."),
    # Gói thành viên
    "MEMBERSHIP_PLAN_NOT_FOUND": (404, "Không tìm thấy gói hoặc gói đã ngừng bán.", "Tải lại danh sách gói."),
    "INVALID_MEMBERSHIP_PLAN_FOR_VEHICLE_TYPE": (400, "Gói này không dành cho loại xe của bạn.", "Về chọn lại gói."),
    "MEMBERSHIP_SUBSCRIPTION_NOT_FOUND": (404, "Không tìm thấy gói thành viên.", "Tải lại danh sách."),
    "INVALID_MEMBERSHIP_STATUS": (400, "Gói đang ở trạng thái không cho phép thao tác này.", "Tải lại chi tiết."),
    "MEMBERSHIP_CODE_GENERATION_FAILED": (500, "Hệ thống chưa tạo được mã gói. Hãy thử lại.", "Nút Thử lại."),
    "MEMBERSHIP_TIME_RANGE_CONFLICT": (409, "Khung giờ của gói này trùng với gói đang có/đang chờ thanh toán.", "Link tới gói trùng."),
    "FULL_TIME_ALREADY_ACTIVE": (409, "Xe đã có gói cả ngày đang hiệu lực.", "Link tới gói đó."),
    "USE_MEMBERSHIP_UPGRADE_FLOW": (409, "Xe đang có gói khung giờ. Hãy dùng chức năng Nâng cấp lên gói cả ngày.", "Nút mở màn Nâng cấp."),
    "MEMBERSHIP_PAYMENT_EXPIRED": (409, "Đã quá hạn thanh toán gói này. Hãy mua lại.", "Về chọn gói."),
    "NO_ACTIVE_TIME_SLOT_MEMBERSHIP": (409, "Bạn chưa có gói khung giờ đang dùng để nâng cấp.", "Ẩn nút Nâng cấp."),
    "FULL_TIME_COVERAGE_ALREADY_REACHED": (409, "Bạn đã có đủ 4 khung giờ, nâng cấp không còn lợi.", "Ẩn nút Nâng cấp."),
    "INVALID_FULL_TIME_PLAN": (400, "Gói cả ngày không hợp lệ cho xe này.", "Tải lại gói."),
    "MEMBERSHIP_CHANGE_IN_PROGRESS": (409, "Xe đang có yêu cầu nâng cấp chờ thanh toán.", "Mở lại thanh toán nâng cấp."),
    "MEMBERSHIP_CHANGE_NOT_FOUND": (404, "Không tìm thấy yêu cầu nâng cấp.", "Tải lại."),
    "MEMBERSHIP_QUOTE_EXPIRED": (409, "Báo giá nâng cấp đã hết hạn. Hãy xem lại giá.", "BE khai báo nhưng chưa dùng; vẫn map."),
    "MEMBERSHIP_CHANGE_EXPIRED": (409, "Yêu cầu nâng cấp đã hết hạn.", "BE khai báo nhưng chưa dùng; vẫn map."),
    "MEMBERSHIP_RENEWAL_NOT_OPEN": (409, "Chưa tới thời gian gia hạn (mở trước hạn 3 ngày).", "Hiện ngày mở gia hạn."),
    "INVALID_MEMBERSHIP_START_TIME": (400, "Ngày bắt đầu không hợp lệ (từ bây giờ đến 30 ngày tới).", "Mở lại bộ chọn ngày."),
    "INVALID_MEMBERSHIP_PLAN_DURATION": (400, "Thời hạn gói không hợp lệ.", "Thông báo chung."),
    "FUTURE_MEMBERSHIP_EXISTS": (409, "Bạn có gói bắt đầu trong tương lai nên chưa nâng cấp được.", "Link tới gói đó."),
    "MEMBERSHIP_USAGE_LIMIT_EXCEEDED": (409, "Đã hết lượt vào bãi hôm nay.", "BE khai báo nhưng chưa dùng; vẫn map."),
    "NOTIFICATION_NOT_FOUND": (404, "Không tìm thấy thông báo.", "Tải lại danh sách."),
}

# Lỗi của nhân viên / quản lý / quản trị (thao tác cổng bãi và cấu hình)
STAFF_ERRORS = {
    "RESERVATION_NOT_CONFIRMED": (409, "Đặt chỗ chưa được xác nhận (chưa thanh toán hoặc đã hủy/hết hạn).", "Hiện trạng thái, không cho check-in."),
    "RESERVATION_NOT_STARTED": (409, "Chưa tới giờ bắt đầu của đặt chỗ.", "Hiện giờ bắt đầu, không cho check-in."),
    "RESERVATION_HOLD_NOT_APPLIED": (409, "Đặt chỗ chưa được giữ chỗ.", "Báo quản lý."),
    "RESERVATION_ALREADY_CHECKED_IN": (409, "Đặt chỗ này đã check-in.", "Mở phiên đang gửi của xe."),
    "NUMBER_PLATE_NOT_MATCH": (409, "Biển số không khớp với đặt chỗ/gói.", "Cho nhập lại biển số thực tế."),
    "PARKING_CAPACITY_FULL": (409, "Bãi đã hết chỗ cho loại xe này.", "Không check-in."),
    "SELECTED_FLOOR_FULL": (409, "Tầng đã chọn hết chỗ.", "Chọn tầng khác hoặc để hệ thống tự xếp."),
    "FLOOR_NOT_ACTIVE": (409, "Tầng đã chọn không hoạt động.", "Chọn tầng khác."),
    "FLOOR_NOT_SUPPORT_VEHICLE_TYPE": (409, "Tầng này không nhận loại xe này.", "Chọn tầng khác."),
    "FLOOR_NOT_FOUND": (404, "Không tìm thấy tầng.", "Tải lại danh sách tầng."),
    "ZONE_NOT_FOUND": (404, "Không tìm thấy khu.", "Tải lại."),
    "TICKET_CODE_GENERATION_FAILED": (500, "Chưa tạo được mã vé. Hãy thử lại.", "Nút Thử lại."),
    "QR_CODE_GENERATION_FAILED": (500, "Chưa tạo được mã QR.", "App tự sinh QR nên hiếm gặp."),
    "SESSION_NOT_FOUND": (404, "Không tìm thấy phiên đang gửi xe với mã này.", "Có thể vé chưa xác nhận lên tầng: tra trạng thái phiên (R-D08)."),
    "SESSION_NOT_ACTIVE": (409, "Xe chưa xác nhận lên tầng nên chưa check-out được.", "Mở màn Xác nhận lên tầng (R-D12)."),
    "SESSION_CHECKOUT_IN_PROGRESS": (409, "Phiên đang chờ thanh toán check-out nên chưa áp/hủy phạt được.", "Chờ thanh toán xong hoặc chuyển sang tiền mặt."),
    "WRONG_ZONE_PENALTY_ONLY_FOR_MIXED_FLOOR": (409, "Chỉ phạt đỗ sai khu ở tầng hỗn hợp.", "Ẩn nút phạt ở tầng khác."),
    "WRONG_ZONE_PENALTY_ALREADY_APPLIED": (409, "Đã áp phạt đỗ sai khu cho phiên này.", "Chuyển nút thành Hủy phạt."),
    "WRONG_ZONE_PENALTY_NOT_APPLIED": (409, "Phiên này chưa bị phạt nên không hủy được.", "Tải lại."),
    "INVALID_WRONG_ZONE_FEE": (409, "Chưa cấu hình phí đỗ sai khu cho loại xe này.", "Báo quản lý cập nhật bảng giá."),
    "INVALID_MIXED_FLOOR_CONFIGURATION": (400, "Cấu hình tầng hỗn hợp chưa hợp lệ.", "Hiện chi tiết để sửa."),
    "INVALID_ZONE_ORDER": (400, "Thứ tự khu không hợp lệ.", "Sửa lại cấu hình."),
    "INVALID_ZONE_CONFIGURATION": (400, "Cấu hình khu chưa hợp lệ.", "Sửa lại cấu hình."),
    "ZONE_NAME_ALREADY_EXISTS": (409, "Tên khu đã tồn tại.", "Báo ở ô tên khu."),
    "ZONE_COUNT_LIMIT_EXCEEDED": (409, "Vượt số khu tối đa của bãi.", "Không cho tạo thêm."),
    "INVALID_FLOOR_POLICY": (400, "Chính sách tầng chưa hợp lệ.", "Sửa lại cấu hình."),
    "FLOOR_HAS_ACTIVE_SESSION": (409, "Tầng đang có xe nên chưa cấu hình/đổi được.", "Chờ xe ra hết."),
    "FLOOR_MUST_BE_MAINTENANCE": (409, "Phải chuyển tầng sang bảo trì trước khi cấu hình.", "Nút chuyển trạng thái bảo trì."),
    "FLOOR_NAME_ALREADY_EXISTS": (409, "Tên tầng đã tồn tại.", "Báo ở ô tên tầng."),
    "FLOOR_LIMIT_EXCEEDED": (409, "Đã đạt số tầng tối đa của bãi.", "Không cho tạo thêm."),
    "INVALID_FLOOR_CONFIGURATION": (400, "Cấu hình tầng chưa hợp lệ.", "Sửa lại cấu hình."),
    "FLOOR_NOT_CONFIGURED": (409, "Tầng chưa được cấu hình nên chưa bật hoạt động được.", "Mở màn cấu hình tầng."),
    "FLOOR_POLICY_NOT_FOUND": (409, "Không tìm thấy chính sách của tầng cho loại xe này.", "Tải lại."),
    "DUPLICATE_VEHICLE_PRIORITY": (409, "Mức ưu tiên này đã được tầng khác dùng cho loại xe.", "Chọn mức khác."),
    "INVALID_PRIORITY_LEVEL": (409, "Mức ưu tiên phải từ 1 trở lên.", "Báo ở ô ưu tiên."),
    "INVALID_VEHICLE_AREA": (409, "Diện tích mỗi xe không hợp lệ.", "Báo ở ô diện tích."),
    "PARKING_CONFIG_ALREADY_EXISTS": (409, "Bãi đã có cấu hình.", "Dùng chức năng cập nhật."),
    "INVALID_PARKING_CONFIGURATION": (409, "Cấu hình bãi chưa hợp lệ (kiểm tra khung giờ, hạn mức).", "Hiện chi tiết để sửa."),
    "MEMBERSHIP_NOT_AVAILABLE": (409, "Gói chưa dùng được lúc này (ngoài khung giờ hoặc chưa tới ngày bắt đầu).", "Hiện khung giờ, không cho check-in."),
    "MEMBERSHIP_PLAN_TIME_WINDOW_CONFLICT": (409, "Khung giờ của gói bị trùng.", "BE khai báo nhưng chưa dùng; vẫn map."),
    "INVALID_MEMBERSHIP_PLAN_CONFIGURATION": (409, "Cấu hình gói chưa hợp lệ (loại gói không khớp khung giờ).", "Hiện chi tiết để sửa."),
    "MEMBERSHIP_TIME_SLOT_NOT_FOUND": (404, "Không tìm thấy khung giờ của gói.", "Tải lại."),
    "MEMBERSHIP_TIME_SLOT_ALREADY_EXISTS": (409, "Mã khung giờ đã tồn tại.", "Báo ở ô mã."),
    "INVALID_MEMBERSHIP_PLAN_PRICE_CONFIGURATION": (409, "Giá gói cả ngày phải lớn hơn tổng 3 giá gói khung giờ cao nhất cùng loại xe và thời hạn.", "Báo ở ô giá."),
    "MEMBERSHIP_PLAN_ALREADY_EXISTS": (409, "Đã có gói đang bán cùng loại xe, loại gói và thời hạn.", "Báo ở form gói."),
}

# Mã ngoài enum ErrorCode
EXTRA_ERRORS = [
    ("PENDING_LIMIT_EXCEEDED", 409, "Bạn đang giữ 2 đặt chỗ chưa thanh toán. Hãy thanh toán hoặc hủy bớt rồi đặt tiếp.", "**Đề xuất, BE chưa có** (T-B7). App tự chặn trước khi gọi."),
    ("RESERVATION_RELEASE_TOO_SOON", 409, "Không thể đặt trả sau vì giờ giữ chỗ quá gần hoặc quá xa. Hãy chọn \"Đặt và trả ngay\".", "**Đề xuất, BE chưa có** (T-B7). App ẩn nút trả sau theo cùng điều kiện."),
    ("REFUND_REQUEST_ALREADY_EXISTS", 409, "Khoản thanh toán này đã có yêu cầu hoàn tiền.", "**Đề xuất, BE chưa có** (T-B7). Mở yêu cầu đang có thay vì tạo mới."),
    ("REFUND_REQUEST_ALREADY_PROCESSED", 409, "Yêu cầu hoàn tiền này đã được xử lý.", "**Đề xuất, BE chưa có** (T-B7). Tải lại danh sách."),
    ("REFRESH_TOKEN_MISSING", 401, "Phiên đăng nhập đã hết hạn, vui lòng đăng nhập lại.", "AuthController trả thẳng chuỗi này khi thiếu cookie `refresh_token`: đăng xuất."),
    ("UNAUTHORIZED", 401, "Bạn cần đăng nhập.", "Có thể là JSON hoặc **text thuần `Unauthorized`** (G-13): thử refresh 1 lần rồi đăng xuất."),
    ("FORBIDDEN", 403, "Bạn không có quyền thực hiện thao tác này.", "JSON hoặc text thuần `Forbidden` (R-X08)."),
]

# Ngoài phạm vi (quyết định có chủ đích, không phải bỏ sót)
OUT_OF_SCOPE = [
    ("Đăng nhập bằng Google", "BE chỉ có luồng redirect trình duyệt về `localhost:5173` và chỉ cấp access token (G-11). v1 chỉ đăng nhập email + mật khẩu (Q-04)."),
    ("Thông báo đẩy khi app đóng (FCM)", "BE chỉ có SSE khi app đang mở và không có API đăng ký token thiết bị (G-18, Q-05). Người dùng thấy thông báo khi mở app."),
    ("Tạo/khóa tài khoản nhân sự, đổi vai trò", "BE chưa có API (G-27). Quản trị chỉ xem danh sách tài xế."),
    ("Tài xế tự trả phí gửi xe trên app", "Nhân viên xử lý ở cổng ra (tiền mặt hoặc VNPay do nhân viên mở). Tài xế chỉ xem lịch sử giao dịch (G-20, Q-07)."),
    ("Biểu đồ doanh thu theo ngày/tháng", "Dashboard của BE chỉ trả ba con số tổng (ngày, tuần, tháng), không có chuỗi thời gian (R-C12)."),
    ("Sửa hồ sơ của nhân viên, quản lý, quản trị", "BE chỉ có API sửa hồ sơ cho tài xế (G-26)."),
    ("Tạo mới cấu hình bãi", "`POST /parking-config/create` không nhận được JSON (G-23); cấu hình có sẵn từ dữ liệu seed."),
    ("Ảnh QR từ BE", "App tự sinh QR trên máy từ chuỗi mã (R-X09)."),
]
