# -*- coding: utf-8 -*-
"""Màn hình (S-xx), luồng, máy trạng thái. Mỗi màn có đúng một chủ. Endpoint tham chiếu bằng khóa ngắn (api.py)."""

ROLE_NAME = {"driver": "Tài xế", "staff": "Nhân viên", "manager": "Quản lý", "admin": "Quản trị"}

# id, tên, vai trò dùng, route, owner, [endpoint keys], [rule ids], mô tả
SCREENS = [
    # ===================== A: Nền tảng & Tài khoản =====================
    ("S-A01", "Splash", "mọi vai trò", "/splash", "A", ["auth.refresh", "auth.me"], ["R-A04", "R-A01"],
     "Đọc token đã lưu → thử `refresh` → vào trang chủ của vai trò hoặc `/login`. Không nhấp nháy màn đăng nhập khi đã có phiên."),
    ("S-A02", "Đăng nhập", "mọi vai trò", "/login", "A", ["auth.login", "auth.me"], ["R-A01", "R-A03", "R-X02", "R-X01"],
     "Email + mật khẩu, hiện/ẩn mật khẩu, link Quên mật khẩu và Đăng ký. Chip tài khoản demo khi chạy dữ liệu giả. `INVALID_EMAIL_OR_PASSWORD` hiện dưới form."),
    ("S-A03", "Đăng ký", "tài xế", "/register", "A", ["auth.register"], ["R-A02", "R-A03"],
     "Họ tên, email, SĐT, mật khẩu, xác nhận. Kiểm tra định dạng tại chỗ trước khi gọi API."),
    ("S-A04", "Nhập OTP đăng ký", "tài xế", "/register/otp", "A", ["auth.register", "auth.register_verify"], ["R-A02"],
     "6 ô số, đếm ngược 5 phút, Gửi lại mã (gọi lại `register`, giãn 30 giây). Xong → `/driver/home`."),
    ("S-A05", "Quên mật khẩu (3 bước)", "mọi vai trò", "/forgot-password", "A", ["auth.forgot", "auth.verify_otp", "auth.reset"], ["R-A05", "R-A03"],
     "Email → OTP → mật khẩu mới. Không cho nhảy bước. Xong → về Đăng nhập."),
    ("S-A06", "Tài khoản", "mọi vai trò", "/{role}/account", "A", ["auth.me", "drv.profile_get", "auth.logout"], ["R-A13", "R-A12", "R-X06"],
     "Thẻ hồ sơ + vai trò (tài xế: `/drivers/profile`; vai trò khác: `/auth/me`), mục Sửa hồ sơ (tài xế), Đổi mật khẩu, Xe của tôi (tài xế), Đăng xuất. Quản lý dùng tab Quản lý chứa mục này."),
    ("S-A07", "Hồ sơ", "mọi vai trò", "/{role}/account/profile", "A", ["drv.profile_get", "drv.profile_put", "auth.me"], ["R-A12"],
     "Tài xế sửa họ tên + SĐT (gửi đủ 2 trường, gọi `/drivers/profile`); vai trò khác chỉ xem từ `/auth/me` và **không gọi `/drivers/profile`** (sẽ 403). Email chỉ đọc."),
    ("S-A08", "Đổi mật khẩu", "mọi vai trò", "/{role}/account/password", "A", ["auth.change_pw"], ["R-A03", "R-A12"],
     "Mật khẩu cũ, mới, xác nhận. Xong thì giữ phiên hiện tại."),
    ("S-A09", "Xe của tôi", "tài xế", "/driver/account/vehicles", "A", ["veh.list", "veh.delete", "ver.my_status"], ["R-A08", "R-A10", "R-A11"],
     "Mỗi xe: biển số, loại, huy hiệu xác minh. Xóa kèm xác nhận; lỗi chặn xóa hiển thị đúng lý do."),
    ("S-A10", "Thêm xe", "tài xế", "/driver/account/vehicles/add", "A", ["veh.add", "fee.list"], ["R-A06", "R-A07"],
     "Biển số tự viết hoa + kiểm tra regex; chọn loại xe (từ chính sách giá ACTIVE). Thành công → gợi ý \"Xác minh xe ngay\"."),
    ("S-A11", "Xác minh xe", "tài xế", "/driver/account/vehicles/:id/verify", "A", ["doc.upload", "doc.view_url", "ver.my_status"], ["R-A09", "R-A10"],
     "2 khung ảnh (trước/sau), chụp hoặc chọn thư viện, nén ≤ 1 MB, gửi tuần tự, lỗi theo mặt. `REJECTED` hiện lý do đỏ, `VERIFIED` khóa."),
    # ===================== B: Đặt chỗ & Quản trị bãi =====================
    ("S-B01", "Danh sách đặt chỗ (tab giữa)", "tài xế", "/driver/reservations", "B", ["rsv.my"], ["R-B13", "R-B07", "R-X06", "R-X07"],
     "2 nhóm: Sắp tới, Lịch sử. Thẻ: mã, biển số, khung giờ, tiền, trạng thái. `PENDING` hiện \"Giữ chỗ đến HH:mm\" (tính từ giờ bắt đầu, R-B13) kèm đếm ngược và nút Thanh toán. Nút Đặt chỗ."),
    ("S-B02", "Tạo đặt chỗ", "tài xế", "/driver/reservations/new", "B", ["veh.list", "fee.list", "fee.active", "cfg.slots", "rsv.create", "rsv.my"], ["R-B01", "R-B02", "R-B03", "R-B04", "R-B05", "R-B06"],
     "Chọn xe → ngày (hôm nay..+7) → slot liên tiếp (4 chip) → thẻ giá ước tính có công thức → hai nút: **Đặt và trả ngay** (giữ chắc cả khung giờ, hạn riêng 15 phút để trả) và **Đặt, trả sau** (giữ chỗ tới giờ bắt đầu + 15 phút, ghi rõ giờ nhả chỗ). \"Trả sau\" chỉ hiện khi giờ bắt đầu cách không quá 24 giờ và `releaseAt` còn ít nhất 5 phút; chặn khi đã có 2 đặt chỗ trả sau (kiểm trên danh sách `rsv.my` đã tải). Cảnh báo đỏ nếu slot đang diễn ra."),
    ("S-B03", "Xác nhận & thanh toán", "tài xế", "/driver/reservations/:id/pay", "B", ["rsv.pay", "rsv.my_detail"], ["R-B07", "R-B06", "R-X05"],
     "Tóm tắt, số tiền thật (`reservationFee`), nhắc chính sách hủy/hoàn, nút Thanh toán VNPay → S-B06 → gọi lại chi tiết và poll theo trạng thái. Mở từ \"Đặt và trả ngay\" hoặc từ nút Thanh toán của đặt chỗ `PENDING` (khóa khi còn dưới 2 phút tới `releaseAt`). Nếu đã tới giờ bắt đầu: hộp xác nhận đỏ \"thanh toán xong sẽ không hủy, không hoàn tiền\", bắt buộc tích xác nhận."),
    ("S-B04", "Chi tiết đặt chỗ", "tài xế", "/driver/reservations/:id", "B", ["rsv.my_detail", "rsv.cancel", "ref.my"], ["R-B08", "R-B09", "R-B10", "R-B11", "R-B12", "R-B22", "R-X09"],
     "Trạng thái, khung giờ, tiền, mã + QR (QR to khi `PENDING` còn giữ chỗ và `CONFIRMED`), mốc \"Giữ chỗ đến\" cho `PENDING`, nút Thanh toán/Hủy hoặc lý do không hủy được, lưu ý check-in/ra sớm/quá giờ. Đặt chỗ đã hủy có thẻ **yêu cầu hoàn tiền** hiển thị trạng thái và lý do (R-B22)."),
    ("S-B05", "Hộp xác nhận hủy", "tài xế", "(bottom sheet)", "B", ["rsv.cancel"], ["R-B08", "R-B09", "R-B10", "R-B22"],
     "Gửi yêu cầu hủy. `PENDING`: nút Hủy hiện đến `releaseAt`, ghi \"Hủy miễn phí\" (không có hoàn tiền). `CONFIRMED` trước `reservedStartAt`: ghi rõ \"Đặt chỗ sẽ bị hủy ngay và chỗ được nhả. Tiền chỉ được hoàn nếu quản lý duyệt; nếu bị từ chối bạn không được hoàn tiền\", **bắt chọn lý do hủy**, số tiền xin hoàn; nút Gửi khóa sau lần bấm đầu. Từ giờ bắt đầu (đã trả): không có nút Hủy."),
    ("S-B06", "WebView VNPay (dùng chung)", "tài xế, nhân viên", "/payment-webview", "B", ["rsv.pay", "rsv.cb"], ["R-X05", "R-B07"],
     "Mở URL VNPay; chặn điều hướng `/payment-success`, `/payment-fail` rồi đóng và trả `PaymentOutcome`. Dùng chung với Gói thành viên và Check-out VNPay."),
    ("S-B07", "Thông tin bãi & khung giờ", "quản trị, quản lý", "/admin/setup  ·  /manager/manage/parking-config", "B", ["cfg.get", "cfg.update", "cfg.manager_update", "cfg.create"], ["R-B14"],
     "Quản trị sửa tên, địa chỉ, 4 slot, hạn mức. Quản lý chỉ sửa 4 slot + hạn mức (cả 8 mốc giờ). Hiển thị lỗi BE theo từng ô."),
    ("S-B08", "Danh sách tầng", "quản trị, quản lý", "/admin/floors  ·  /manager/floors", "B", ["flr.list", "flr.create", "flr.status"], ["R-B16", "R-X08"],
     "Thẻ tầng: tên, loại (đơn/hỗn hợp), trạng thái, sức chứa từng loại xe, mức lấp đầy. Quản trị/quản lý tạo tầng và đổi trạng thái."),
    ("S-B09", "Chi tiết & cấu hình tầng", "quản trị, quản lý", "/admin/floors/:id  ·  /manager/floors/:id", "B", ["flr.get", "flr.info", "flr.config", "flr.priority", "zon.list"], ["R-B16", "R-B17"],
     "Xem khu/chính sách/chỗ trống, sửa tên-mô tả, đổi ưu tiên, cấu hình đơn loại/hỗn hợp (chọn khu cho từng loại xe) khi tầng đang bảo trì."),
    ("S-B10", "Khu (zone)", "quản trị", "/admin/setup/zones", "B", ["zon.list", "zon.create", "zon.save"], ["R-B18"],
     "Danh sách tên khu, tạo thêm, đổi tên."),
    ("S-B11", "Loại xe", "quản trị", "/admin/setup/vehicle-types", "B", ["veh.type_save", "fee.list"], ["R-B15"],
     "Danh sách loại xe (suy ra từ bảng giá/tầng, G-10) và form **thêm mới** tên + diện tích mỗi xe (BE không có sửa)."),
    ("S-B12", "Bảng giá", "quản trị, quản lý", "/admin/pricing  ·  /manager/manage/pricing", "B", ["fee.list", "fee.save", "fee.update"], ["R-B19"],
     "Mỗi loại xe: giá/giờ, hệ số đêm, phí sai khu. Sửa tạo bản mới; xem bản cũ (INACTIVE)."),
    # ===================== C: Gói thành viên & Quản lý =====================
    ("S-C01", "Gói thành viên (tab)", "tài xế", "/driver/membership", "C", ["mem.my"], ["R-C06", "R-C10", "R-X06"],
     "2 tab: Của tôi (danh sách gói + `usableNow`) và Các gói (S-C02)."),
    ("S-C02", "Chọn gói theo xe", "tài xế", "/driver/membership (tab Các gói)", "C", ["veh.list", "ver.my_status", "mem.plans_available"], ["R-C01", "R-A11"],
     "Chọn xe; xe chưa `VERIFIED` → cảnh báo + nút tới S-A11. Gói nhóm theo khung giờ, hiện giá, thời hạn, khung giờ vào bãi."),
    ("S-C03", "Xem trước & mua", "tài xế", "/driver/membership/buy", "C", ["mem.preview", "mem.create", "mem.pay", "mem.detail", "mem.cancel"], ["R-C02", "R-C03", "R-C04", "R-C09", "R-C11"],
     "Bắt đầu ngay/hẹn ngày (≤ 30 ngày), xem trước, banner gợi ý FULL_TIME, Mua → Thanh toán (S-B06) → poll. Gói `PENDING_PAYMENT` mở lại để trả tiếp/hủy."),
    ("S-C04", "Chi tiết gói", "tài xế", "/driver/membership/:id", "C", ["mem.detail", "mem.renew", "mem.replacement", "mem.cancel"], ["R-C05", "R-C06", "R-C07", "R-C10", "R-X09"],
     "Mã + QR, khung giờ vào bãi, thời hạn, `usableNow`, `entryCountToday`. Gia hạn (mở trước hạn 3 ngày), Nâng cấp (nếu đủ điều kiện), thông tin gói thay thế nếu `REPLACED`."),
    ("S-C05", "Nâng cấp lên cả ngày", "tài xế", "/driver/membership/upgrade", "C", ["mem.up_preview", "mem.upgrade", "mem.detail", "mem.replacement"], ["R-C08"],
     "Danh sách gói cũ + tiền được trừ, giá FULL_TIME, số phải trả, đếm ngược báo giá 15 phút. Sau khi xong hiện thông tin thay thế."),
    ("S-C06", "Tổng quan", "quản lý", "/manager/overview", "C", ["dash.manager", "pay.cash_summary"], ["R-C12", "R-X06"],
     "Ô số liệu: xe đang gửi, doanh thu ngày/tuần/tháng; **tiền mặt đã thu theo nhân viên trong ngày**; thanh mức lấp đầy từng tầng; tỷ lệ theo loại xe. Kéo để làm mới."),
    ("S-C07", "Duyệt xe", "quản lý", "/manager/verify", "C", ["ver.pending", "ver.detail", "ver.view_url", "ver.approve", "ver.reject"], ["R-C13", "R-A10"],
     "Danh sách chờ duyệt (có huy hiệu số lượng trên tab), mở chi tiết xem 2 ảnh, Duyệt / Từ chối (bắt buộc lý do)."),
    ("S-C08", "Quản lý gói", "quản lý", "/manager/manage/plans", "C", ["mem.plans_public", "mem.plan_get", "mem.plan_create", "mem.plan_update", "mem.plan_status"], ["R-C14"],
     "Danh sách gói theo loại xe, tạo/sửa (loại gói ↔ khung giờ), ngừng bán/bán lại. Báo đúng lỗi giá FULL_TIME."),
    ("S-C09", "Khung giờ của gói", "quản lý", "/manager/manage/time-slots", "C", ["mem.slot_list", "mem.slot_get", "mem.slot_create", "mem.slot_update", "mem.slot_status"], ["R-C15"],
     "Danh sách khung giờ, tạo/sửa (cả ngày hoặc giờ bắt đầu-kết thúc), bật/tắt, báo trùng giờ."),
    ("S-C10", "Người đăng ký gói", "quản lý", "/manager/manage/subscribers", "C", ["mem.subscribers", "mem.subscriber_subs"], ["R-C16"],
     "Danh sách người đăng ký + số gói theo trạng thái, chi tiết gói từng người (tự tính \"Hết hạn\")."),
    ("S-C11", "Giám sát", "quản lý", "/manager/manage/monitor", "C", ["rsv.all", "ses.list", "ses.staffs", "tx.all", "tx.detail"], ["R-C17"],
     "3 tab chỉ đọc: Đặt chỗ, Phiên gửi xe (lọc theo trạng thái/ngày/nhân viên/biển/mã), Giao dịch."),
    ("S-C12", "Người dùng", "quản trị", "/admin/users", "C", ["adm.drivers", "adm.driver"], ["R-C18"],
     "Danh sách tài xế + tìm kiếm, chi tiết một tài xế (chỉ đọc)."),
    # ===================== D: Cổng bãi (nhân viên) & Trang chủ tài xế =====================
    ("S-C13", "Duyệt hoàn tiền", "quản lý", "/manager/verify/refunds", "C", ["ref.list", "ref.approve", "ref.reject", "ref.paid", "ref.evidence_upload"], ["R-C19", "R-B22"],
     "3 danh sách: Chờ duyệt, Chờ chuyển tiền (gom theo ngày, hiện tổng cần chuyển, cảnh báo quá hạn), Đã xử lý. Thẻ yêu cầu: mã đặt chỗ, biển số, số tiền, giờ đã trả, giờ hủy, còn bao lâu tới giờ bắt đầu, lý do tài xế. Nút Duyệt / Từ chối (bắt buộc lý do) và \"Đã chuyển tiền\" (từng yêu cầu hoặc chọn cả danh sách, hộp xác nhận ghi tổng số tiền)."),
    ("S-D01", "Trang chủ tài xế (tab)", "tài xế", "/driver/home", "D", ["mem.my", "rsv.my", "ntf.unread"], ["R-D05", "R-D06", "R-X06"],
     "Chuông + số chưa đọc, thẻ Xe đang gửi (tạm, G-04), đặt chỗ sắp tới, gói đang hiệu lực/sắp hết hạn, nút tắt."),
    ("S-D02", "Thông báo", "tài xế", "/driver/home/notifications", "D", ["ntf.list", "ntf.unread", "ntf.read", "ntf.read_all", "ntf.stream"], ["R-D01", "R-D02"],
     "Danh sách phân trang cuộn vô hạn, chấm chưa đọc, Đọc tất cả, chạm điều hướng theo loại. SSE chạy khi Home hoặc Thông báo đang mở."),
    ("S-D03", "Giao dịch (tab)", "tài xế", "/driver/wallet", "D", ["tx.my"], ["R-D03", "R-D04", "R-X06"],
     "Danh sách phân trang, chip lọc theo Loại và Trạng thái; mỗi dòng: loại, mã tham chiếu, tiền, trạng thái, thời gian."),
    ("S-D04", "Chi tiết giao dịch", "tài xế", "/driver/wallet/:id", "D", ["tx.my_detail"], ["R-D03", "R-D04"],
     "Thông tin chung + khối chi tiết theo loại; nút nhảy tới đặt chỗ/gói liên quan."),
    ("S-D05", "Bảng giá & Chính sách", "tài xế", "/driver/home/pricing", "D", ["fee.list", "mem.plans_public", "cfg.slots"], ["R-D07", "R-B08", "R-B09", "R-B10"],
     "Giá theo giờ, hệ số đêm, phí sai khu, giờ các slot, bảng gói, đoạn Chính sách hủy & hoàn tiền (chỉ đọc)."),
    ("S-D06", "Thẻ gửi xe", "tài xế", "/driver/home/ticket/:sessionId", "D", ["ntf.list"], ["R-D06", "R-X09"],
     "QR mã vé, biển số, giờ vào. Mã vé lấy từ thông báo CHECK_IN (tạm)."),
    ("S-D07", "Trang chủ nhân viên (tab)", "nhân viên", "/staff/home", "D", ["ses.current", "pay.cash_summary"], ["R-D18", "R-X06"],
     "Số xe đang gửi, **tiền mặt đã thu hôm nay** (tổng và số lần), nút Quét mã, nút Check-in vãng lai, việc gần đây."),
    ("S-D08", "Quét mã (nút giữa)", "nhân viên, quản lý", "/scan", "D", [], ["R-D08", "R-X07", "R-X09"],
     "Toàn màn hình: camera QR, đèn pin, nhập mã thủ công, hướng dẫn cấp quyền camera. Quét xong → S-D09."),
    ("S-D09", "Kết quả quét & Check-in", "nhân viên, quản lý", "/scan/result?code=", "D", ["rsv.by_code", "mem.staff_preview", "pk.checkin_rsv", "pk.checkin_mem", "flr.list", "ses.list"], ["R-D09", "R-D10", "R-D08", "R-D19"],
     "Tra cứu mã → thẻ thông tin, cảnh báo chặn (sai trạng thái/giờ/biển), ô xác nhận biển số thực tế, nút Check-in. Đặt chỗ `PENDING` trong giờ giữ chỗ: thẻ **\"Cần thu <tiền> tiền mặt\" (số lớn)** và nút **Đã nhận <tiền> tiền mặt** có hộp xác nhận cuối (R-D19); bấm xong mới ghi nhận thu tiền và check-in. Thành công: mã vé + tầng/khu + QR vé. Mã `PKG-`: tra `GET /parking-sessions?ticketCode=` rồi chuyển S-D11 (`CHECKED_IN_GATE`), S-D12 (`ACTIVE`) hoặc báo \"Xe đã ra\" (`COMPLETED`)."),
    ("S-D10", "Check-in xe vãng lai", "nhân viên, quản lý", "/staff/home/walk-in", "D", ["pk.checkin_walkin", "fee.list", "flr.list", "rsv.all"], ["R-D11", "R-A06"],
     "Biển số (regex), loại xe, tầng chọn tay tùy chọn. Kết quả: mã vé + QR + tầng/khu. Hết chỗ báo đúng lỗi."),
    ("S-D11", "Xác nhận lên tầng", "nhân viên, quản lý", "/staff/sessions/:ticket/floor", "D", ["pk.floor_gate", "flr.list"], ["R-D12"],
     "Quét/nhập vé, chọn tầng đang đứng → kết quả đúng/sai tầng + hướng dẫn."),
    ("S-D12", "Check-out", "nhân viên, quản lý", "/staff/sessions/:ticket/checkout", "D", ["pk.checkout_preview", "pk.checkout", "pk.exit_gate", "pk.cb", "ses.list"], ["R-D13", "R-D14", "R-D19", "R-X05"],
     "Tra mã vé/biển số → phí hiện tại + phí sai khu → chọn Tiền mặt/VNPay. **Tiền mặt**: màn hiện số tiền cần thu thật lớn và nút **Đã nhận <tiền> tiền mặt** có hộp xác nhận (R-D19); chỉ khi bấm mới gọi check-out. VNPay: QR/WebView cho tài xế trả, poll phiên tới `COMPLETED`."),
    ("S-D13", "Xe đang gửi", "nhân viên, quản lý", "/staff/sessions", "D", ["ses.current", "ses.penalty_apply", "ses.penalty_cancel"], ["R-D15", "R-D16"],
     "Danh sách phân trang + tìm theo biển/vé; chi tiết phiên với Xác nhận lên tầng, Phạt/Hủy phạt sai khu, Check-out."),
    ("S-D14", "Tra cứu đặt chỗ", "nhân viên, quản lý", "/staff/reservations", "D", ["rsv.all", "rsv.by_code", "rsv.by_id"], ["R-D17", "R-D09"],
     "Tìm theo mã/biển số, lọc trạng thái; chạm xem chi tiết và Check-in nếu đủ điều kiện."),
]

# Luồng (đọc để hiểu thứ tự gọi API)
FLOWS = {
    "A": [
        ("Phiên đăng nhập (mọi vai trò)", [
            "`POST /auth/login` → lưu `accessToken` và cookie `refresh_token` (đọc `Set-Cookie`); đọc `role`.",
            "Tài xế: `GET /drivers/profile`. Vai trò khác: `GET /auth/me`. Chuyển tới trang chủ của vai trò.",
            "Mỗi request gắn `Authorization: Bearer`. Gặp 401 → `POST /auth/refresh` đúng 1 lần (request khác chờ) → thử lại.",
            "Refresh thất bại hoặc `REFRESH_TOKEN_*` → xóa token, về `/login`.",
        ]),
        ("Thêm và xác minh xe (tài xế)", [
            "S-A10: nhập biển số (viết hoa), chọn loại → `POST /vehicle/add`.",
            "S-A11: chụp/chọn 2 ảnh, nén ≤ 1 MB → `POST …/documents` (mặt trước rồi mặt sau) → xe `PENDING`.",
            "Quản lý duyệt ở S-C07 → `VERIFIED`/`REJECTED`. App tải lại `my-status` mỗi lần mở màn.",
        ]),
    ],
    "B": [
        ("Đặt chỗ: trả ngay hoặc trả sau", [
            "S-B02: chọn xe, ngày, slot liên tiếp. Tải `fee-policies/active` + `parking-config/slots` để tính giá ước tính; app tính `releaseAt = reservedStartAt + 15 phút`.",
            "Bấm Tạo → `POST /reservations/create` → `PENDING` + `reservationFee` thật. Lỗi `RESERVATION_NOT_AVAILABLE` nghĩa là hết hạn mức.",
            "**Đặt và trả ngay** (`payNow=true`): ngay sau khi tạo → S-B03 → `POST /reservations/{id}/payment` → `paymentUrl` → S-B06. Trả xong → `CONFIRMED`: chỗ giữ chắc suốt khung giờ. Bỏ dở thì hết hạn riêng sau 15 phút (hoặc `releaseAt` nếu sớm hơn), không tính vào giới hạn 2 đặt chỗ trả sau.",
            "**Đặt, trả sau**: dừng ở `PENDING`, hiển thị \"Giữ chỗ đến `releaseAt`\". Trả được lúc nào cũng được tới và gồm `releaseAt` (nút Thanh toán ở S-B01/S-B04; trả sau giờ bắt đầu thì phải xác nhận không hoàn tiền).",
            "S-B06 mở `paymentUrl`. VNPay gọi BE callback rồi redirect sang trang `/payment-success` hoặc `/payment-fail` (web) → WebView chặn và đóng.",
            "Gọi lại `GET /reservations/my/{id}` và poll: `CONFIRMED` → thành công, tới S-B04. Vẫn `PENDING` → hết poll thì cho Thử lại nếu còn trước `releaseAt`. `EXPIRED`/`CANCELLED` → báo và tải lại.",
        ]),
        ("Không trả và không tới: tự nguyện bỏ", [
            "Khi `now > releaseAt` (giờ bắt đầu + 15 phút) mà đặt chỗ vẫn `PENDING`, chưa check-in → BE chuyển `EXPIRED` và nhả chỗ (G-35). Không có khoản tiền nào bị mất.",
            "App hiển thị \"Chỗ đã được nhả vì quá giờ giữ\" kèm nút Đặt lại. Chỗ đó giờ nhận được khách vãng lai (R-B21).",
            "Nếu tài xế tới sau `releaseAt`: nhân viên chỉ check-in vãng lai được (R-D11).",
        ]),
        ("Hủy đặt chỗ", [
            "`PENDING` (chưa trả tiền): `PATCH …/cancel` → `CANCELLED`, miễn phí, nhả chỗ ngay (được tới `releaseAt`).",
            "`CONFIRMED` và `now < reservedStartAt`: hộp xác nhận ghi số tiền xin hoàn, nói rõ \"tiền chỉ hoàn nếu quản lý duyệt, bị từ chối thì không được hoàn\" và bắt chọn lý do → `PATCH …/cancel {reason}` (hợp đồng đề xuất G-02) → `CANCELLED`, chỗ nhả ngay, **tạo yêu cầu hoàn tiền `REQUESTED`** (không hoàn tiền ngay). Tài xế theo dõi ở chi tiết đặt chỗ, Giao dịch và thông báo.",
            "Từ `reservedStartAt`: đặt chỗ đã trả không hủy được, ghi \"Đã tới giờ bắt đầu: không hủy/hoàn tiền\". Đã trả mà không đến → `EXPIRED` lúc `reservedEndAt`, mất tiền.",
        ]),
        ("Thiết lập bãi từ đầu (quản trị)", [
            "S-B07: kiểm tra thông tin bãi và 4 khung giờ. S-B11: có đủ loại xe cần dùng. S-B10: có đủ khu (số khu ≥ 2 nếu có tầng hỗn hợp).",
            "S-B12: mỗi loại xe có một chính sách giá `ACTIVE`.",
            "S-B08: tạo tầng (ở `MAINTENANCE`) → S-B09: cấu hình tầng (đơn loại/hỗn hợp, khu) → đổi sang `ACTIVE`.",
            "S-B09: đặt ưu tiên tầng cho từng loại xe (duy nhất giữa các tầng).",
        ]),
    ],
    "C": [
        ("Mua gói", [
            "S-C02: chọn xe (phải `VERIFIED`) → `GET /membership/plans/available?vehicleId=`.",
            "S-C03: chọn bắt đầu ngay (không gửi `scheduledStartAt`) hoặc hẹn ≤ 30 ngày → `purchase-preview`.",
            "Bấm Mua → `POST /membership/subscription` (`PENDING_PAYMENT`, hạn 15 phút) → `POST …/{id}/payment` → `vnpayPaymentUrl` → S-B06.",
            "Đóng WebView → poll `GET …/{id}` mỗi 2 giây tối đa 30 giây tới khi `status ≠ PENDING_PAYMENT`. `ACTIVE` → tới S-C04.",
        ]),
        ("Gia hạn và nâng cấp", [
            "Từ 3 ngày trước `endAt` (hoặc đã hết hạn): S-C04 hiện Gia hạn → `POST …/{id}/renew` → URL VNPay → S-B06. Gói mới có mã mới.",
            "Nâng cấp (R-C08): S-C05 gọi `upgrade/preview` → hiện tiền được trừ và số phải trả, đếm ngược 15 phút → `POST …/upgrade` → URL VNPay → poll gói cũ tới `REPLACED` → `GET …/{id}/replacement`.",
        ]),
        ("Duyệt hoàn tiền (quản lý, cuối ngày)", [
            "S-C13 tab Chờ duyệt: `GET /refund-requests?status=REQUESTED` → xem lý do và thời điểm hủy → **Duyệt** (`PATCH …/approve`) hoặc **Từ chối** kèm lý do (`PATCH …/reject`). Tài xế nhận thông báo mỗi lần.",
            "Cuối ngày: tab Chờ chuyển tiền (`status=APPROVED`) hiện tổng cần chuyển theo ngày; quản lý chuyển tiền **ngoài app** (Q-16) từ tài khoản doanh nghiệp, hoặc cá nhân kèm bằng chứng (mã giao dịch, ảnh biên lai, họ tên chủ tài khoản).",
            "Quản lý chọn các yêu cầu đã chuyển và bấm **Đã chuyển tiền** (hộp xác nhận ghi tổng) → `PATCH /refund-requests/paid {ids}` → `REFUNDED`; tài xế thấy \"Đã hoàn <số tiền>\".",
        ]),
        ("Duyệt xe (quản lý)", [
            "S-C07: `GET /vehicle-verification/pending` → mở chi tiết → `view-url` của từng mặt → xem ảnh.",
            "Duyệt: `PATCH …/approve`. Từ chối: bắt buộc nhập lý do → `PATCH …/reject {rejectReason}`. Xong xóa khỏi danh sách và tải lại.",
        ]),
    ],
    "D": [
        ("Ngày xe vào bãi (đặt chỗ)", [
            "Tài xế mở S-B04, đưa QR `RSV-…`. Nhân viên bấm Quét mã (S-D08).",
            "S-D09: `GET /reservations/code/{code}` → kiểm tra theo trạng thái (R-D09) → nhân viên xác nhận biển số thực tế → `POST /parking/check-in/reservation` → mã vé `PKG-…`, tầng, khu. Nếu đặt chỗ còn `PENDING` (trong `[start, releaseAt]`): màn hiện **số tiền cần thu**; nhân viên nhận tiền mặt rồi bấm **Đã nhận <tiền> tiền mặt** (R-D19) → ghi nhận thu tiền và check-in trong cùng thao tác (G-36).",
            "Xe lên tầng được xếp: nhân viên quét vé `PKG-…` → app tra `GET /parking-sessions?ticketCode=` thấy `CHECKED_IN_GATE` → S-D11 → `GET /parking/check-in/floor` → `ACTIVE`.",
            "Tài xế nhận thông báo `CHECK_IN`; đặt chỗ đổi `CHECKED_IN`.",
        ]),
        ("Xe ra bãi", [
            "S-D12 (vé đã `ACTIVE`): nhập/quét mã vé hoặc biển số → `GET /parking/check-out/preview` → phí + phạt sai khu (nếu có).",
            "Tiền mặt: màn hiện số tiền cần thu, nhân viên nhận tiền rồi bấm **Đã nhận <tiền> tiền mặt** (R-D19) → `POST /parking/check-out {paymentMethod: CASH}` → `COMPLETED`. VNPay: nhận `vnPayPaymentUrl` → hiện QR/WebView cho tài xế trả → poll phiên.",
            "Phí 0đ: hoàn tất ngay (không có thông báo `CHECK_OUT`). Đặt chỗ → `COMPLETED`. Phí > 0 và đã thu: tài xế nhận thông báo `CHECK_OUT`.",
        ]),
        ("Thông báo thời gian thực (tài xế)", [
            "Mở Home: `GET /notifications` + `unread-count`, rồi mở SSE `GET /notifications/stream?token=`.",
            "Nhận `notification` → chèn đầu danh sách, tăng số chưa đọc, hiện banner trong app.",
            "BE đóng SSE sau ~60 giây → nối lại ngay, rồi tải lại danh sách và số chưa đọc để bù thông báo bị lỡ.",
        ]),
    ],
}

# Máy trạng thái (bảng chuyển trạng thái)
STATE_MACHINES = [
    ("Đặt chỗ (ReservationStatus)", "B", [
        ("(tạo)", "PENDING", "Tài xế bấm Đặt (trả ngay hoặc trả sau)", "Hợp lệ theo R-B02..R-B05; tối đa 2 đặt chỗ `PENDING`", "Giữ chỗ tới `releaseAt = reservedStartAt + 15'`; chiếm hạn mức"),
        ("PENDING", "CONFIRMED", "VNPay callback thành công", "Thanh toán lúc `now ≤ releaseAt` (hoặc `payNowDeadline`), đặt chỗ còn `PENDING`", "Giữ chắc suốt khung giờ; không còn hạn 15 phút"),
        ("PENDING", "CHECKED_IN", "Nhân viên nhận tiền mặt, bấm \"Đã nhận tiền mặt\" và xác nhận (một giao dịch)", "`start ≤ now ≤ releaseAt`, đúng biển số (**BE chưa có**, G-36)", "Xếp tầng, tạo phiên rồi mới ghi Payment `CASH` `SUCCESS`; hủy thanh toán VNPay đang chờ"),
        ("PENDING", "CANCELLED", "Tài xế hủy", "`now ≤ releaseAt`", "Miễn phí; nhả chỗ ngay"),
        ("PENDING", "EXPIRED", "`now > releaseAt` mà chưa trả và chưa check-in; hoặc hết `payNowDeadline`", "Hệ thống, kiểm theo giờ ở mỗi thao tác (**BE chưa có**, G-35)", "\"Tự nguyện bỏ\", **không mất tiền**; nhả chỗ cho khách vãng lai"),
        ("CONFIRMED", "CANCELLED", "Tài xế hủy (kèm lý do)", "`now < reservedStartAt` (**BE chưa có**, G-02)", "Nhả chỗ ngay; **tạo yêu cầu hoàn tiền `REQUESTED`**, tiền chưa hoàn"),
        ("CONFIRMED", "CHECKED_IN", "Nhân viên check-in", "`start ≤ now < end`, đúng biển số, `holdApplied` (không thì `RESERVATION_HOLD_NOT_APPLIED`)", "Tạo phiên gửi xe; hold tắt"),
        ("CONFIRMED", "EXPIRED", "Qua `reservedEndAt` không đến (no-show)", "Hệ thống", "**Đã trả nên mất tiền, không hoàn**"),
        ("EXPIRED / CANCELLED", "—", "VNPay báo thành công muộn", "Đặt chỗ không còn `PENDING`", "BE hiện: Payment → `FAILED`, tiền đã bị thu, không hoàn. **Yêu cầu (T-B7): ghi Payment `SUCCESS` kèm cờ `lateArrival` và tạo yêu cầu hoàn tiền `REQUESTED`** để quản lý duyệt (G-05)"),
        ("CHECKED_IN", "COMPLETED", "Nhân viên check-out, thu phụ phí nếu có", "Phí = 0 hoặc đã thu", "Kết thúc"),
        ("CANCELLED / EXPIRED / COMPLETED", "—", "Trạng thái cuối", "", "Chỉ xem"),
    ]),
    ("Phiên gửi xe (SessionStatus)", "D", [
        ("(check-in)", "CHECKED_IN_GATE", "Nhân viên check-in (đặt chỗ, gói hoặc vãng lai)", "Còn chỗ; xe chưa đỗ", "Cấp mã vé `PKG-…`, xếp tầng/khu; chiếm chỗ"),
        ("CHECKED_IN_GATE", "ACTIVE", "Quét vé ở đúng tầng được xếp (`/check-in/floor`)", "`currentFloorId` = tầng được xếp", "Cho phép check-out, áp phạt sai khu"),
        ("CHECKED_IN_GATE", "CHECKED_IN_GATE", "Quét vé ở sai tầng", "`correctFloor=false`", "Không đổi trạng thái, hiện hướng dẫn"),
        ("ACTIVE", "ACTIVE", "Nhân viên áp/hủy phạt sai khu", "Tầng hỗn hợp, không có thanh toán `PENDING`", "Cộng/trừ `wrongZoneFee` vào phí"),
        ("ACTIVE", "COMPLETED", "Check-out", "Phí 0, hoặc tiền mặt, hoặc VNPay thành công", "Đặt chỗ → `COMPLETED`; thông báo `CHECK_OUT` **chỉ khi phí > 0**"),
        ("ACTIVE", "ACTIVE", "Quét vé lần nữa ở tầng", "Phiên đã `ACTIVE`", "BE trả lỗi `VEHICLE_ALREADY_PARKING`, không đổi gì"),
        ("ACTIVE", "ACTIVE", "Check-out bằng VNPay chưa trả/thất bại", "Payment `PENDING`/`FAILED`", "Cho thử lại không giới hạn (giờ ra đã chốt); trong lúc `PENDING` không áp/hủy phạt được (`SESSION_CHECKOUT_IN_PROGRESS`)"),
        ("(CANCELED)", "—", "BE khai báo nhưng không bao giờ đặt", "", "Bỏ qua"),
    ]),
    ("Gói thành viên (MembershipSubscriptionStatus)", "C", [
        ("(tạo)", "PENDING_PAYMENT", "Tài xế bấm Mua/Gia hạn", "Qua kiểm tra R-C02, R-C03", "Hạn 15 phút từ lúc tạo"),
        ("PENDING_PAYMENT", "ACTIVE", "VNPay callback thành công", "Trả trước hạn, đúng số tiền, không xung đột", "Sinh `membershipCode`; `usableNow` theo `startAt`"),
        ("PENDING_PAYMENT", "PAYMENT_EXPIRED", "Quá hạn (job mỗi phút + 180 giây ân hạn)", "Hệ thống", "Chặn gói chồng chỉ tới `paymentExpiresAt`"),
        ("PENDING_PAYMENT", "CANCELLED", "Tài xế hủy; hoặc xung đột lúc trả/kích hoạt; hoặc bị nâng cấp đè", "", "Đã bị thu tiền mà xung đột: không hoàn (G-16)"),
        ("ACTIVE", "EXPIRED", "Qua `endAt`", "API tài xế trả trạng thái hiệu lực (BE không lưu DB, G-24)", "Chỉ Gia hạn"),
        ("ACTIVE", "REPLACED", "Nâng cấp lên FULL_TIME thành công", "**Mọi** gói nguồn vẫn `ACTIVE` lúc thanh toán (không thì `INVALID_MEMBERSHIP_STATUS` và nâng cấp bị hủy)", "Xem `replacement`; gói khung giờ đang chờ thanh toán bị hủy"),
        ("ACTIVE", "—", "**Không có đường hủy/hoàn tiền**", "", "R-C06"),
    ]),
    ("Yêu cầu nâng cấp (MembershipChangeStatus)", "C", [
        ("(tạo)", "PENDING_PAYMENT", "`POST /upgrade`", "R-C08", "Báo giá đóng băng, hạn 15 phút"),
        ("PENDING_PAYMENT", "COMPLETED", "Callback thành công trong hạn", "Các gói nguồn vẫn `ACTIVE`", "Gói mới `FULL_TIME`; gói cũ `REPLACED`"),
        ("PENDING_PAYMENT", "CANCELLED", "VNPay thất bại, hoặc mất bản ghi thanh toán", "", "Tạo lại được"),
        ("PENDING_PAYMENT", "EXPIRED", "Trả muộn, hoặc bị đóng khi tạo lần sau", "Lazy, không có job", "Báo giá lại"),
        ("PENDING_PAYMENT", "PENDING_PAYMENT", "Bấm Nâng cấp lần nữa khi còn yêu cầu chờ", "Chưa quá hạn", "BE **dùng lại** yêu cầu cũ: URL mới, số tiền cũ đã đóng băng"),
    ]),
    ("Xác minh xe (VehicleVerificationStatus)", "A", [
        ("NOT_SUBMITTED", "PENDING", "Tài xế upload 1 mặt giấy tờ", "File hợp lệ", "UI bắt buộc đủ 2 mặt"),
        ("PENDING", "VERIFIED", "Quản lý duyệt (S-C07)", "", "Khóa upload"),
        ("PENDING", "REJECTED", "Quản lý từ chối kèm lý do (S-C07)", "Lý do bắt buộc", "Hiện lý do"),
        ("REJECTED", "PENDING", "Tài xế upload lại", "Xóa lý do cũ", "—"),
        ("VERIFIED", "—", "Upload bị chặn `VEHICLE_ALREADY_VERIFIED`", "", "Trạng thái cuối với tài xế"),
    ]),
    ("Tầng (FloorStatus)", "B", [
        ("(tạo)", "MAINTENANCE", "Tạo tầng", "Chưa đạt số tầng tối đa, tên không trùng", "Chưa có loại tầng"),
        ("MAINTENANCE", "MAINTENANCE", "Cấu hình tầng", "Không có xe `CHECKED_IN_GATE/ACTIVE`", "Xóa và tạo lại khu, chính sách, ưu tiên = 1"),
        ("MAINTENANCE", "ACTIVE", "Đổi trạng thái", "Đã cấu hình (có loại tầng và chính sách)", "Nhận xe, được hệ thống tự xếp"),
        ("(bất kỳ)", "(bất kỳ)", "Đổi trạng thái", "BE cho chuyển qua lại tự do và **không kiểm tra còn xe khi rời `ACTIVE`**", "App cảnh báo trước khi rời `ACTIVE` nếu tầng còn xe"),
        ("ACTIVE", "MAINTENANCE", "Đổi trạng thái", "Muốn cấu hình lại thì phải về đây", "Ngừng nhận xe mới"),
        ("ACTIVE / MAINTENANCE", "INACTIVE / LOCKED", "Đổi trạng thái", "", "Ngừng nhận xe"),
    ]),
    ("Yêu cầu hoàn tiền (RefundStatus, đề xuất)", "C", [
        ("(tạo)", "REQUESTED", "Tài xế hủy đặt chỗ `CONFIRMED` trước giờ bắt đầu; hoặc VNPay báo thanh toán thành công khi đặt chỗ không còn `PENDING` (trả muộn/trùng)", "Khoản thanh toán này chưa có yêu cầu (tối đa 1 yêu cầu cho mỗi khoản)", "Chỗ đã nhả; **thông báo cho tài xế và mọi quản lý**; chờ duyệt"),
        ("REQUESTED", "APPROVED", "Quản lý duyệt", "Đang `REQUESTED`", "Chờ chuyển tiền (mốc 19:00 giờ Việt Nam); thông báo cho tài xế; **không rút lại được**"),
        ("REQUESTED", "REJECTED", "Quản lý từ chối", "Bắt buộc có lý do", "Tiền giữ nguyên; thông báo kèm lý do"),
        ("APPROVED", "REFUNDED", "Quản lý bấm \"Đã chuyển tiền\"", "Đã chuyển tiền ngoài app (Q-16) và nhập đủ bằng chứng (nguồn tiền, mã giao dịch, ảnh biên lai); xử lý theo từng id", "Payment `REFUNDED`; doanh thu trừ vào ngày chuyển; thông báo; idempotent"),
        ("REJECTED / REFUNDED", "—", "Trạng thái cuối", "", "Chỉ xem; không đổi ngược"),
    ]),
    ("Thanh toán (PaymentStatus)", "D", [
        ("(tạo)", "PENDING", "Cấp URL VNPay", "", "Có thể có nhiều `Transaction` (mỗi URL một giao dịch)"),
        ("PENDING", "SUCCESS", "VNPay callback hợp lệ (`vnp_ResponseCode=00`)", "Đối tượng còn hợp lệ", "Đặt chỗ/gói/phiên được cập nhật"),
        ("PENDING", "FAILED", "VNPay lỗi, quá hạn thanh toán (`releaseAt`/`payNowDeadline`/hạn gói), hoặc đối tượng không còn hợp lệ", "", "Có thể về `PENDING` khi thử lại trước hạn; thu muộn thì chuyển hoàn tiền"),
        ("SUCCESS", "REFUNDED", "Quản lý xác nhận **đã chuyển tiền** cho yêu cầu hoàn tiền đã duyệt", "**BE chưa có**, G-02; chỉ sau khi `APPROVED`", "Hiển thị \"Đã hoàn tiền\""),
    ]),
]
