# -*- coding: utf-8 -*-
"""Chia việc cho 4 người. Mỗi người sở hữu thư mục riêng, không sửa file của người khác.

Nguyên tắc chia: theo VÙNG NGHIỆP VỤ (mỗi người làm trọn một luồng từ màn hình tới API và tự kiểm thử),
cân tải bằng số màn và độ khó, không theo tầng kỹ thuật.
"""

OWNERS = {
    "A": ("Dev A", "Nền tảng, Đăng nhập & Tài khoản", "lib/core/network, lib/features/auth, lib/features/account"),
    "B": ("Dev B", "Đặt chỗ & Quản trị bãi", "lib/features/reservation, lib/features/admin, lib/core/payment (bản WebView), Backend (task T-B7)"),
    "C": ("Dev C", "Gói thành viên & Quản lý", "lib/features/membership, lib/features/manager"),
    "D": ("Dev D", "Cổng bãi (nhân viên), Trang chủ tài xế & QA", "lib/features/staff, lib/features/scan, lib/features/home, lib/features/wallet, lib/features/notification, lib/core/errors"),
}

PHASES = [
    ("P0", "Khung & hợp đồng", "**Xong hôm nay**: app chạy trên điện thoại qua ADB wifi, đăng nhập 4 vai trò (`<role>@parking.vn` / `123123@`), mỗi vai trò một bottom tab 5 ô với nút giữa nổi bật, màn quét QR chạy thật, repository Fake, theme, cổng thanh toán giả, tài liệu này."),
    ("P1", "Màn hình bằng Fake data", "Cả 4 người làm song song trong thư mục của mình, **chưa cần BE**. Đích: mọi màn của mình đủ 4 trạng thái (tải/rỗng/lỗi/có dữ liệu) với Fake và chạy được trên điện thoại."),
    ("P2", "Nối BE thật", "A giao `ApiClient` **trước tiên** (task T-A1, mọi người chờ nó). Sau đó mỗi người viết `Api*Repository` thay Fake, chỉ đổi dòng khai báo trong `*_providers.dart`."),
    ("P3", "Chạy xuyên suốt & vá", "Chạy toàn bộ bộ test ở mục Kiểm thử trên điện thoại thật nối BE (đặc biệt kịch bản liên vai trò: tài xế đặt chỗ → nhân viên check-in → check-out). D tổng hợp lỗi, nhóm vá. Đóng băng tính năng trước hạn nộp."),
]

# id, owner, phase, size, tiêu đề, deliverable, [screens], [endpoint keys], [rules], [depends], [acceptance]
TASKS = [
    # ===================== A =====================
    ("T-A0", "A", "P1", "S", "Hợp đồng nền cho cả nhóm (làm đầu tiên)",
     "`core/clock/clock.dart` (`Clock`, `serverNow()` đọc `Env.serverUtcOffset`, có `FakeClock`), `ApiException(code, message, status)` rỗng ruột để mọi người cùng ném/bắt, model `Vehicle{id, numberPlate, vehicleTypeId, vehicleTypeName, status, verification}` + interface `VehicleRepository` (B và C **chỉ đọc**, không sửa model).",
     [], ["veh.list"], ["R-X03", "R-X02"], [],
     ["`serverNow()` có unit test với offset `+07:00` và `0`, và với `FakeClock` để test ranh giới giờ.",
      "`Vehicle` có đủ trường như trên và `VehicleRepository` có bản Fake; B và C dùng ngay mà không đợi A làm xong màn Xe của tôi.",
      "Hoàn thành trong ngày đầu của P1 để T-B1, T-B4, T-C1, T-C3, T-C4 không phải chờ."]),
    ("T-A1", "A", "P2", "L", "ApiClient + phiên đăng nhập",
     "`core/network/api_client.dart` (Dio), `core/network/api_exception.dart`, `core/auth/token_storage.dart` (flutter_secure_storage), cầu nối `AuthRepository` thật thay `FakeAuthRepository`.",
     [], ["auth.login", "auth.refresh", "auth.logout", "auth.me", "auth.register_verify"], ["R-A04", "R-A01", "R-X03", "R-X05", "R-X08"], ["T-A0"],
     ["Base URL từ `Env.apiBaseUrl` (`--dart-define`).",
      "Gắn `Bearer`; 401 → refresh đúng 1 lần, các request khác chờ cùng 1 Future, rồi thử lại.",
      "Đọc `Set-Cookie: refresh_token` ở login/register-verify/refresh và gửi lại ở `/auth/refresh` và `/auth/logout`.",
      "Bóc `ApiResponse`, ném `ApiException(code, message, status, data)`; xử lý cả 401/403 **text thuần**.",
      "Cắm `serverNow()` của T-A0 vào header `Date` của phản hồi (UTC) cộng `Env.serverUtcOffset`; có unit test với 2 offset.",
      "Cookie refresh gửi tay với **Path `/api/auth`** đúng như R-A04.",
      "Đăng nhập thật lấy `role` từ BE và đưa vào `AuthState` (vỏ giao diện đã có sẵn).",
      "Chịu được phản hồi **204 không có phần thân** (đổi ưu tiên tầng) và body là chuỗi JSON trần (đổi trạng thái tầng).",
      "Có unit test với mock server cho: refresh thành công, refresh thất bại, 2 request song song cùng gặp 401."]),
    ("T-A2", "A", "P1", "M", "Đăng nhập, đăng ký OTP, quên mật khẩu, Splash",
     "S-A01..S-A05, giữ phiên qua lần mở app, redirect guard trong `app/router.dart` (chỉ sửa phần đánh dấu TODO(Dev A)).",
     ["S-A01", "S-A02", "S-A03", "S-A04", "S-A05"], ["auth.login", "auth.register", "auth.register_verify", "auth.forgot", "auth.verify_otp", "auth.reset", "auth.me"],
     ["R-A01", "R-A02", "R-A03", "R-A05", "R-X01"], [],
     ["Fake chạy được cả 3 luồng, kể cả OTP sai/hết hạn/sai 5 lần.",
      "Đăng nhập bằng cả 4 tài khoản demo vào đúng vỏ của vai trò; chưa đăng nhập không vào được tab nào; đã đăng nhập không thấy màn login.",
      "Đóng app mở lại vẫn còn phiên (khi đã nối token thật).",
      "Đếm ngược OTP 5 phút, giãn 30 giây giữa 2 lần gửi lại."]),
    ("T-A3", "A", "P1", "M", "Tài khoản dùng chung mọi vai trò",
     "S-A06..S-A08: hồ sơ (sửa với tài xế, xem với vai trò khác), đổi mật khẩu, đăng xuất. `accountBranch(prefix)` đã dùng chung.",
     ["S-A06", "S-A07", "S-A08"], ["auth.me", "auth.logout", "auth.change_pw", "drv.profile_get", "drv.profile_put"], ["R-A12", "R-A13", "R-A03"], [],
     ["Sửa hồ sơ luôn gửi đủ `fullName` + `phoneNumber`; vai trò khác không có nút sửa và **không phát sinh request tới `/drivers/profile`** (chỉ `/auth/me`).",
      "Đăng xuất xóa token, về `/login`, và dù API lỗi vẫn xóa cục bộ; không tự đăng nhập lại.",
      "Quản lý đăng xuất được từ tab Quản lý.",
      "Test: đăng xuất ở từng vai trò quay về màn đăng nhập (đã có mẫu cho quản lý)."]),
    ("T-A4", "A", "P1", "M", "Xe của tôi: danh sách, thêm, xóa",
     "S-A09, S-A10, `VehicleRepository` (thay `AccountRepository`).",
     ["S-A09", "S-A10"], ["veh.list", "veh.add", "veh.delete", "fee.list"], ["R-A06", "R-A07", "R-A08", "R-A14"], ["T-A0"],
     ["Regex biển số đúng R-A06, có test cho: `72C2-61690`, `59A-12345`, `59X1-67890`, `51F-1234`, và biển sai (`59a-123.45`, `5A-12345`, `59A12345`).",
      "Loại xe lấy từ chính sách giá ACTIVE (lọc `INACTIVE`).",
      "Xóa xe bị chặn hiển thị đúng lý do (3 mã `VEHICLE_*`).",
      "Thêm xe trùng biển với xe vãng lai cũ: hiển thị loại xe và trạng thái theo **phản hồi BE** (R-A14).",
      "Model `Vehicle` do T-A0 định nghĩa, ở đây chỉ hoàn thiện repository."]),
    ("T-A5", "A", "P1", "L", "Xác minh xe bằng giấy tờ (phía tài xế)",
     "S-A11 + dịch vụ nén ảnh (≤ 1 MB, jpeg) bằng `image_picker` + `flutter_image_compress`.",
     ["S-A11"], ["doc.upload", "doc.view_url", "ver.my_status"], ["R-A09", "R-A10", "R-A11"], [],
     ["Đủ 2 mặt mới bật nút Gửi.", "Gửi tuần tự từng mặt; lỗi mặt nào báo ở mặt đó, có Thử lại.",
      "4 trạng thái hiển thị đúng; `REJECTED` hiện lý do; `VERIFIED` không còn nút upload.",
      "Test nén: ảnh 4 MB → ≤ 1 MB. Xin quyền camera/thư viện đúng cách."]),
    # ===================== B =====================
    ("T-B1", "B", "P1", "L", "Tạo đặt chỗ (chọn xe, ngày, slot, giá)",
     "S-B02, `ReservationQuote` (hàm thuần tính giá), widget `SlotRangePicker`.",
     ["S-B02"], ["veh.list", "fee.list", "fee.active", "cfg.slots", "rsv.create", "rsv.my"],
     ["R-B01", "R-B02", "R-B03", "R-B04", "R-B05", "R-B06"], ["T-A0"],
     ["Chọn slot theo quy tắc ở TC-B02; không thể tạo dải đứt đoạn.",
      "Hôm nay: slot đã qua bị khóa, slot đang diễn ra có cảnh báo đỏ.",
      "Ngày chỉ trong [hôm nay, hôm nay+7].",
      "Hàm tính giá có test đơn vị khớp TC-B10 (Ô tô: slot 1 = 90.000đ, slot 2 = 60.000đ, slot 2+3 = 120.000đ, cả ngày = 270.000đ; Xe máy: slot 1 = 36.000đ, slot 3 = 24.000đ).",
      "Giá xem trước nằm cạnh công thức; số thật lấy từ `reservationFee` sau khi tạo.",
      "Hai nút ở cuối form: **Đặt và trả ngay** và **Đặt, trả sau** (hiển thị rõ giờ nhả chỗ `releaseAt`); ẩn \"trả sau\" khi slot đang diễn ra, `releaseAt` còn dưới 5 phút, hoặc giờ bắt đầu cách quá 24 giờ (R-B03); chặn khi đã có 2 đặt chỗ trả sau còn hạn trong danh sách `rsv.my` (R-B05).",
      "Chặn tạo nếu xe đã có đặt chỗ `PENDING/CONFIRMED` trùng khung giờ (R-B04, G-14), báo trùng kèm nút \"Hủy bản cũ\" / \"Thanh toán bản cũ\".",
      "Chặn slot làm `reservedEndAt ≤ reservedStartAt` (R-B02); cảnh báo giá tính đủ cả slot ở slot đang diễn ra (R-B03)."]),
    ("T-B2", "B", "P1", "L", "Cổng thanh toán VNPay bằng WebView (dùng chung 3 nơi)",
     "`core/payment/webview_payment_gateway.dart` thay `FakePaymentGateway` (giữ nguyên interface `PaymentGateway`), S-B06. **Không cần ApiClient**: chỉ nhận một URL và trả `PaymentOutcome`.",
     ["S-B06"], ["rsv.cb"], ["R-X05", "R-B07"], [],
     ["Chặn điều hướng `/payment-success`, `/payment-fail`, trả đúng `PaymentOutcome`; nút Đóng có xác nhận.",
      "Chạy được với một URL tĩnh bất kỳ để C (mua gói) và D (check-out VNPay) dùng ngay trong P1.",
      "Chuyển bản dùng được cho C và D trước khi họ làm bước thanh toán."]),
    ("T-B8", "B", "P2", "M", "Nối thanh toán đặt chỗ vào BE + poll xác nhận",
     "S-B03 với `ApiReservationRepository.pay()`, bộ poll dùng chung `awaitStatus` (C và D tái sử dụng).",
     ["S-B03"], ["rsv.pay", "rsv.my_detail"], ["R-B07", "R-X05", "R-B05"], ["T-A1", "T-B2", "T-B7"],
     ["Đóng WebView luôn gọi lại `GET /reservations/my/{id}` và rẽ nhánh theo trạng thái thật; mở lại `PENDING` còn hạn thì poll 2 giây × 30 giây, ẩn nút Thanh toán trong lúc đó (R-B07).",
      "Đếm ngược theo `releaseAt` (= `reservedStartAt + 15 phút`); từ 2 phút trước `releaseAt` khóa nút Thanh toán; hết hạn thì tải lại; không bao giờ mở lại URL cũ khi đặt chỗ đã hết hạn/hủy.",
      "Thanh toán **không** gặp `RESERVATION_NOT_AVAILABLE` (hạn mức đã giữ từ lúc tạo, R-B05); chỉ xử lý `RESERVATION_NOT_PENDING`/`RESERVATION_EXPIRED`.",
      "Khi `now ≥ reservedStartAt` hiện hộp xác nhận đỏ \"không hủy, không hoàn tiền\" và bắt buộc tích xác nhận (R-B07)."]),
    ("T-B3", "B", "P1", "M", "Danh sách và chi tiết đặt chỗ + QR",
     "S-B01, S-B04, widget QR dùng `qr_flutter` (đã có mẫu ở `reservation_detail_screen.dart`).", ["S-B01", "S-B04"], ["rsv.my", "rsv.my_detail", "qr.rsv", "ref.my"],
     ["R-B11", "R-B12", "R-B13", "R-B20", "R-B10", "R-B07", "R-X09"], [],
     ["Hai nhóm Sắp tới/Lịch sử đúng R-B13.",
      "QR sinh từ `reservationCode`, đủ tương phản để quét; QR to khi `PENDING` còn giữ chỗ và khi `CONFIRMED`, các trạng thái khác chỉ hiện mã (R-B12).",
      "Màn chi tiết ghi rõ các điều ở R-B11 (đến sớm, ra sớm, quá giờ).",
      "`fromJson` nhận cả `holdApplied` và `isHoldApplied` (G-15).",
      "Chi tiết hiển thị đúng theo từng trạng thái ở R-B20; `EXPIRED` phân biệt có/không có giao dịch `SUCCESS` (R-B10); `EXPIRED`/`CANCELLED` có nút Đặt lại.",
      "`PENDING` hiển thị \"Giữ chỗ đến HH:mm\" và đếm ngược cả ở danh sách lẫn chi tiết (tính từ `reservedStartAt`, R-B13).",
      "`EXPIRED` hiển thị đúng nghĩa: chưa trả (\"tự nguyện bỏ\", không mất tiền) hay đã trả (mất tiền), theo R-B10.",
      "Đặt chỗ đã hủy có thẻ yêu cầu hoàn tiền (`ref.my`) với đủ 4 trạng thái và lý do từ chối (R-B22)."]),
    ("T-B4", "B", "P1", "M", "Hủy đặt chỗ và hoàn tiền",
     "S-B05, `ReservationRepository.cancel(reason)` trả `CancelResult{refundRequest?}` (null khi hủy `PENDING`).",
     ["S-B05"], ["rsv.cancel"], ["R-B08", "R-B09", "R-B10", "R-B22"], ["T-B3", "T-A0"],
     ["`PENDING`: hủy miễn phí, không nói gì về hoàn tiền.",
      "`CONFIRMED` + `now < reservedStartAt`: hộp xác nhận ghi số tiền xin hoàn và nêu rõ chỉ hoàn nếu quản lý duyệt.",
      "Từ giờ bắt đầu: không có nút Hủy, hiện lý do.",
      "Ranh giới giờ: kiểm tra bằng `serverNow()`; `CONFIRMED` test tại `start-1s`, `start`, `start+1s`; `PENDING` test tại `releaseAt-1s`, `releaseAt` (còn hợp lệ), `releaseAt+1s` (đã hết).",
      "Hủy `CONFIRMED` trước giờ: hộp xác nhận bắt chọn lý do, ghi rõ \"hoàn sau khi quản lý duyệt\", gọi `cancel(reason)` và hiển thị yêu cầu hoàn tiền `REQUESTED`; hủy `PENDING` thì miễn phí, không có yêu cầu hoàn tiền.",
      "Fake đúng hợp đồng đề xuất (G-02).",
      "Nếu `now < reservedStartAt` mà BE vẫn trả `RESERVATION_CANNOT_BE_CANCELLED` thì hiện \"Hệ thống chưa hỗ trợ hủy đặt chỗ đã trả, liên hệ quản lý\"; chỉ nói \"đã tới giờ bắt đầu\" khi `serverNow ≥ reservedStartAt`."]),
    ("T-B7", "B", "P1", "L", "Backend: sửa G-01, G-02, G-03, G-35, G-36 (Java)",
     "Trong `Backend/`: (1) `SecurityConfig` thêm `permitAll` cho `/api/reservations/vnPay-callback` (G-01); (2) **hủy và hoàn tiền qua duyệt (G-02)**: `PATCH /reservations/my/{id}/cancel {reason}` cho phép `CONFIRMED` khi `now < reservedStartAt`, đặt `CANCELLED`, nhả hạn mức, tạo `RefundRequest` `REQUESTED`; thêm `GET /reservations/my/{id}/refund`, `GET /refund-requests`, `PATCH /refund-requests/{id}/approve|reject`, `PATCH /refund-requests/paid` (→ `REFUNDED`, Payment `REFUNDED`), mã lỗi `REFUND_REQUEST_ALREADY_PROCESSED` và `REFUND_REQUEST_ALREADY_EXISTS` (unique theo khoản thanh toán), thêm `PaymentStatus.REFUNDED`, thêm Payment `lateArrival` và `collectedBy`, loại thông báo mới (`REFUND_REQUEST_CREATED` gửi mọi quản lý; `REFUND_REQUESTED/APPROVED/REJECTED/REFUNDED` gửi tài xế), doanh thu trừ khoản `REFUNDED` vào ngày chuyển, `GET /payments/cash-summary` (G-38); (3) mở `GET /reservations/availability?vehicleId&date` (G-03); (4) **mô hình giữ chỗ mới (G-35)**: `releaseAt = reservedStartAt + ân hạn`, `PENDING` giữ hạn mức và chỗ vật lý trong `[reservedStartAt, releaseAt]` (`holdStartAt = reservedStartAt`, G-09), bỏ cửa sổ thanh toán 15 phút cũ, mọi thao tác kiểm theo `now ≤ releaseAt`, quét định kỳ thay timer RAM, kiểm trùng khung giờ tính cả `PENDING`, thanh toán không kiểm lại hạn mức, `vnp_ExpireDate = releaseAt`; (5) `create` nhận `payNow`, thêm mã lỗi `PENDING_LIMIT_EXCEEDED` và `RESERVATION_RELEASE_TOO_SOON`; (6) callback muộn ghi Payment `SUCCESS` kèm `lateArrival` và sinh yêu cầu hoàn tiền (G-05); (7) **thu tiền mặt tại cổng (G-36)**: `check-in/reservation` nhận `collectCash`, nguyên tử và idempotent.",
     [], ["rsv.cancel", "rsv.cb", "rsv.create", "rsv.pay", "pk.checkin_rsv", "ref.my", "ref.list", "ref.approve", "ref.reject", "ref.paid", "pay.cash_summary"], ["R-B09", "R-B08", "R-B05", "R-B07", "R-B21", "R-B11"], [],
     ["Callback đặt chỗ không còn bị 401; thanh toán sandbox chuyển được đặt chỗ sang `CONFIRMED` (TC-B15).",
      "Hủy `CONFIRMED` trước giờ bắt đầu thành `CANCELLED`, hạn mức được nhả ngay, có `RefundRequest` `REQUESTED` và Payment **chưa đổi**; từ giờ bắt đầu vẫn `RESERVATION_CANNOT_BE_CANCELLED` (TC-B17).",
      "Quản lý duyệt/từ chối/xác nhận đã chuyển tiền chạy đúng một chiều, người đã xử lý trước thì `REFUND_REQUEST_ALREADY_PROCESSED`; `paid` idempotent (TC-C34..TC-C37).",
      "Tạo đặt chỗ trả sau rồi không trả: `now > releaseAt` thì `EXPIRED`, hạn mức và chỗ vật lý được nhả, check-in vãng lai nhận được chỗ đó (TC-B44); đặt cho ngày mai không làm bãi hôm nay báo đầy (TC-B48).",
      "`createPaymentForReservation` không còn gọi kiểm hạn mức; thanh toán `PENDING` đã giữ suất không bao giờ `RESERVATION_NOT_AVAILABLE` (TC-B33).",
      "Ranh giới: tại `releaseAt` vẫn hợp lệ, `releaseAt + 1 giây` thì hết, kể cả khi bộ quét chưa chạy (TC-B13, TC-D25).",
      "`PENDING_LIMIT_EXCEEDED` ở lần tạo thứ 3 và `RESERVATION_RELEASE_TOO_SOON` khi trả sau quá gần/quá xa; `payNow` không tính vào giới hạn (TC-B46, TC-B51).",
      "Callback thành công khi đặt chỗ không còn `PENDING` (muộn hoặc trùng) thì ghi Payment `SUCCESS` kèm `lateArrival` và tạo `RefundRequest`, không để Payment `FAILED` mất tiền; thanh toán trong hạn mà callback tới muộn vẫn xác nhận bình thường (TC-B50).",
      "`ref.my` chỉ chủ đặt chỗ xem được; nhân viên/tài xế khác gọi `ref.*` của quản lý nhận 403 (TC-C38).",
      "`collectCash`: lỗi xếp tầng thì không ghi tiền; gọi lại sau khi thành công trả kết quả cũ; thanh toán VNPay đang chờ bị hủy (TC-D25, TC-D27).",
      "Có test Java (hoặc Postman) cho từng thay đổi; cập nhật bảng mã lỗi (script `docs/spec/build.py` đối chiếu `ErrorCode.java`: thêm mã mới vào bảng và bỏ khỏi danh sách đề xuất).",
      "Xong trước P3; app dùng Fake đến lúc đó."]),
    ("T-B5", "B", "P1", "M", "Quản trị: thông tin bãi, loại xe, bảng giá",
     "S-B07, S-B11, S-B12 (bảng giá cũng được màn Quản lý dùng lại; B xuất widget để C/quản lý nhúng).",
     ["S-B07", "S-B11", "S-B12"], ["cfg.get", "cfg.update", "cfg.manager_update", "cfg.create", "veh.type_save", "fee.list", "fee.save", "fee.update"],
     ["R-B14", "R-B15", "R-B19", "R-X08"], [],
     ["Quản trị sửa được đủ trường; quản lý chỉ thấy/sửa 4 slot + hạn mức. Luôn gửi đủ mọi trường, bắt buộc đủ 8 mốc giờ và hạn mức 0–100 ở form (BE không kiểm tra).",
      "Sửa bảng giá tạo bản mới và hiển thị bản cũ là `INACTIVE`; chỉ cho Sửa trên dòng ACTIVE và chỉ cho Tạo khi loại xe chưa có bản ACTIVE; không cho nhập số âm.",
      "Loại xe: danh sách suy ra từ bảng giá/tầng; chỉ thêm mới (BE không có sửa), bắt diện tích > 0 ở form.",
      "Lỗi BE (`INVALID_PARKING_CONFIGURATION`...) hiện ở đúng ô."]),
    ("T-B6", "B", "P1", "L", "Quản trị: tầng, khu, ưu tiên",
     "S-B08, S-B09, S-B10 (quản lý dùng chung S-B08/S-B09 từ tab Bãi xe).",
     ["S-B08", "S-B09", "S-B10"], ["flr.list", "flr.get", "flr.create", "flr.info", "flr.status", "flr.config", "flr.priority", "zon.list", "zon.create", "zon.save"],
     ["R-B16", "R-B17", "R-B18", "R-X08"], [],
     ["Tạo tầng ở trạng thái `MAINTENANCE`; không đạt giới hạn tầng → báo `FLOOR_LIMIT_EXCEEDED`.",
      "Cấu hình tầng: đơn loại (1 loại xe) hoặc hỗn hợp (2 loại xe, chọn khu sao cho **chia hết**, không bỏ sót), chỉ mở khi tầng đang bảo trì.",
      "Đổi `ACTIVE` khi chưa cấu hình → `FLOOR_NOT_CONFIGURED` và nút dẫn tới cấu hình.",
      "Ưu tiên: bắt `DUPLICATE_VEHICLE_PRIORITY`; hiển thị mức lấp đầy từng loại xe.",
      "Test logic chia khu hợp lệ (VD 4 khu → 2/2, 1/3, 3/1 hợp lệ; 4/0 và bỏ sót khu không hợp lệ)."]),
    # ===================== C =====================
    ("T-C1", "C", "P1", "M", "Danh sách gói + chọn xe + xác minh",
     "S-C01, S-C02, `MembershipRepository.getAvailablePlans(vehicleId)`.",
     ["S-C01", "S-C02"], ["veh.list", "ver.my_status", "mem.plans_available", "mem.my"], ["R-C01", "R-A11", "R-C10"], ["T-A0"],
     ["Gói nhóm theo khung giờ, hiển thị giá, thời hạn, khung giờ vào bãi.",
      "Xe chưa `VERIFIED`: cảnh báo + nút tới `/driver/account/vehicles/:id/verify`.",
      "Huy hiệu trạng thái đúng 6 trạng thái và `usableNow`."]),
    ("T-C2", "C", "P2", "L", "Mua gói + thanh toán + poll kích hoạt",
     "S-C03; poller `awaitSubscriptionStatus(id)` dùng chung với nâng cấp/gia hạn.",
     ["S-C03"], ["mem.preview", "mem.create", "mem.pay", "mem.detail", "mem.cancel", "mem.cb"],
     ["R-C02", "R-C03", "R-C04", "R-C09", "R-C11"], ["T-B2", "T-A1", "T-B8"],
     ["Không gửi `scheduledStartAt` khi chọn bắt đầu ngay; hẹn ngày giới hạn [bây giờ, +30 ngày].",
      "Banner gợi ý FULL_TIME khi `recommendFullTime`.",
      "Poll 2 giây × 30 giây; hết hạn thì chuyển sang thông báo \"đang xử lý\".",
      "Gói `PENDING_PAYMENT` mở lại được để trả tiếp (đếm ngược `paymentExpiresAt`) hoặc hủy."]),
    ("T-C3", "C", "P1", "M", "Chi tiết gói + QR + gia hạn",
     "S-C04, hộp xác nhận Gia hạn.", ["S-C04"], ["mem.detail", "mem.renew", "mem.replacement", "mem.cancel", "qr.mem"],
     ["R-C05", "R-C06", "R-C07", "R-C10", "R-X09"], ["T-A0"],
     ["QR từ `membershipCode`; gói `PENDING_PAYMENT` chưa có mã thì không hiện QR.",
      "Nút Gia hạn chỉ hiện khi `ACTIVE` còn ≤ 3 ngày hoặc `EXPIRED`; vẫn bắt `MEMBERSHIP_RENEWAL_NOT_OPEN`.",
      "Gói `ACTIVE` không có nút Hủy, có dòng \"không hoàn tiền\".",
      "Đã gia hạn rồi thì ẩn nút Gia hạn, ghi \"Đã gia hạn, bắt đầu <ngày>\" và nêu `FUTURE_MEMBERSHIP_EXISTS` làm lý do khóa Nâng cấp (R-C07).",
      "`usableNow=false` hiển thị đúng lý do (chưa tới ngày, ngoài khung giờ, hết hạn) (R-C05)."]),
    ("T-C4", "C", "P2", "L", "Nâng cấp lên FULL_TIME",
     "S-C05.", ["S-C05"], ["mem.up_preview", "mem.upgrade", "mem.detail", "mem.replacement"], ["R-C08"], ["T-C2", "T-B2", "T-A0"],
     ["Chỉ hiện Nâng cấp khi đủ điều kiện (còn lại là bắt lỗi từ BE).",
      "Danh sách `creditItems`, `totalCredit`, `payableAmount` đúng; test đơn vị công thức R-C08 (TC-C14).",
      "Đếm ngược `quoteExpiresAt`; hết hạn → tải lại báo giá.",
      "`payableAmount == 0` → khóa nút (G-16).",
      "Số phải trả ở bước thanh toán lấy từ phản hồi của `/upgrade`, không lấy từ bản xem trước (R-C08).",
      "Sau thanh toán: gói cũ `REPLACED`, hiển thị gói mới từ `replacement`."]),
    ("T-C5", "C", "P1", "M", "Quản lý: tổng quan và giám sát",
     "S-C06, S-C11 (3 tab chỉ đọc), S-C12 (quản trị: người dùng).",
     ["S-C06", "S-C11", "S-C12"], ["dash.manager", "rsv.all", "ses.list", "ses.staffs", "tx.all", "tx.detail", "adm.drivers", "adm.driver", "pay.cash_summary"],
     ["R-C12", "R-C17", "R-C18", "R-X06"], [],
     ["Tổng quan có 4 trạng thái, kéo để làm mới; thanh lấp đầy đổi màu đỏ khi > 85%.",
      "Phiên gửi xe lọc được theo trạng thái, khoảng ngày, nhân viên (từ `ses.staffs`), biển số, mã vé; phân trang.",
      "Danh sách đặt chỗ tải 1 lần, tìm/lọc phía app (G-22).",
      "Danh sách tài xế có tìm kiếm; chi tiết chỉ đọc.",
      "Tổng quan có thêm \"Tiền mặt đã thu theo nhân viên hôm nay\" từ `pay.cash_summary` (R-C12)."]),
    ("T-C6", "C", "P1", "M", "Quản lý: duyệt xe",
     "S-C07; huy hiệu số lượng chờ duyệt trên tab Duyệt xe (đã có mẫu `ManagerVerifyScreen`).",
     ["S-C07"], ["ver.pending", "ver.detail", "ver.view_url", "ver.approve", "ver.reject"], ["R-C13", "R-A10"], [],
     ["Xem được cả 2 mặt giấy tờ qua URL tạm (xử lý URL hết hạn bằng cách lấy lại).",
      "Từ chối bắt buộc lý do (ô trống thì khóa nút).",
      "Duyệt/từ chối xong xe biến khỏi danh sách; bắt `INVALID_VEHICLE_VERIFICATION_STATUS` khi người khác đã xử lý trước và tải lại.",
      "Xe thiếu 1 mặt giấy tờ: khóa nút Duyệt, chỉ cho Từ chối kèm lý do; ẩn xe đã xóa (`INACTIVE`) (R-C13)."]),
    ("T-C7", "C", "P1", "L", "Quản lý: gói, khung giờ gói, người đăng ký",
     "S-C08, S-C09, S-C10.", ["S-C08", "S-C09", "S-C10"],
     ["mem.plans_public", "mem.plan_get", "mem.plan_create", "mem.plan_update", "mem.plan_status", "mem.slot_list", "mem.slot_get", "mem.slot_create", "mem.slot_update", "mem.slot_status", "mem.subscribers", "mem.subscriber_subs"],
     ["R-C14", "R-C15", "R-C16"], [],
     ["Form gói: chọn loại gói thì lọc khung giờ phù hợp (FULL_TIME ↔ cả ngày); báo đúng lỗi giá FULL_TIME và trùng gói.",
      "Form khung giờ: bật \"cả ngày\" thì ẩn ô giờ; kiểm tra giờ bắt đầu ≠ kết thúc; báo trùng giờ.",
      "Người đăng ký: tự đánh dấu \"Hết hạn\" khi `ACTIVE` và `endAt ≤ now` (G-24).",
      "Test: logic phát hiện hai khung giờ chồng nhau kể cả qua nửa đêm."]),
    # ===================== D =====================
    ("T-C8", "C", "P1", "M", "Quản lý: duyệt hoàn tiền và chuyển tiền cuối ngày",
     "S-C13 trong tab \"Cần duyệt\" của quản lý (cùng tab với duyệt xe, 2 phần); `RefundRepository` (Fake dùng chung với phía tài xế để thấy luồng liền mạch).",
     ["S-C13"], ["ref.list", "ref.approve", "ref.reject", "ref.paid", "ref.evidence_upload"], ["R-C19", "R-B22"], [],
     ["3 danh sách (Chờ duyệt, Chờ chuyển tiền gom theo ngày kèm tổng tiền, Đã xử lý); huy hiệu số lượng chờ duyệt trên tab.",
      "Từ chối bắt buộc lý do (ô trống thì khóa nút); Duyệt không cần lý do.",
      "\"Đã chuyển tiền\": chọn từng yêu cầu hoặc tất cả, hộp xác nhận ghi tổng số tiền; bấm lại là idempotent.",
      "Yêu cầu đã duyệt từ ngày trước mà chưa chuyển có cảnh báo quá hạn.",
      "Bắt `REFUND_REQUEST_ALREADY_PROCESSED` khi người khác xử lý trước và tải lại danh sách.",
      "Hiển thị mã giao dịch VNPay và thời điểm đã trả của từng yêu cầu; nhóm Chờ chuyển tiền gom theo ngày duyệt giờ Việt Nam kèm cảnh báo quá hạn (mốc 19:00, R-C19).",
      "Hộp \"Đã chuyển tiền\": chọn nguồn tiền (doanh nghiệp / cá nhân kèm họ tên chủ tài khoản), nhập mã giao dịch ngân hàng, chụp hoặc chọn ảnh biên lai; nút xác nhận khóa tới khi đủ; cảnh báo nếu mã giao dịch đã dùng; hiển thị tài khoản nhận tiền đầy đủ cho quản lý.",
      "Duyệt xong không có nút rút lại; \"Đã chuyển tiền\" hiển thị danh sách id bị bỏ qua nếu có."]),
    ("T-D1", "D", "P1", "M", "Bảng mã lỗi + widget dùng chung",
     "`core/errors/error_messages.dart` (124 mã + 3 mã ngoài enum), `AsyncView` nâng cấp, `EmptyView`, `MoneyText`. **Làm đầu tiên, cả nhóm dùng.**",
     [], [], ["R-X02", "R-X04", "R-X06", "R-X08"], [],
     ["`messageFor(code)` có đủ mọi mã ở mục Mã lỗi; mã lạ → câu chung kèm mã.",
      "Có test duyệt toàn bộ danh sách mã và đảm bảo không mã nào trả rỗng.",
      "`formatVnd` có test: `0 → 0đ`, `110000 → 110.000đ`, `1700000 → 1.700.000đ`."]),
    ("T-D2", "D", "P1", "L", "Quét mã + check-in đặt chỗ/gói",
     "S-D08 (đã chạy camera thật + nhập tay), S-D09 (kết quả quét, ô xác nhận biển số, nút Check-in), nối `GateRepository` thật.",
     ["S-D08", "S-D09"], ["rsv.by_code", "mem.staff_preview", "pk.checkin_rsv", "pk.checkin_mem", "flr.list", "ses.list"], ["R-D08", "R-D09", "R-D10", "R-D19", "R-X09", "R-X07"], [],
     ["Quét QR thật và nhập tay đều dẫn tới cùng màn kết quả; không xử lý trùng một mã hai lần.",
      "Phân loại theo tiền tố (có test `classifyCode`); quét `PKG-` tra trạng thái phiên qua `ses.list` rồi chuyển Xác nhận lên tầng / Check-out / báo \"Xe đã ra\" (R-D08).",
      "Tiền kiểm đặt chỗ theo bảng trạng thái ở R-D09 (kể cả `holdApplied=false` và `CHECKED_IN` → \"Đã check-in rồi\"); mọi lỗi BE hiển thị tiếng Việt (bảng nhân viên ở mục Mã lỗi).",
      "Đặt chỗ `PENDING` trong giờ giữ chỗ: thẻ \"Chưa thanh toán, thu <tiền> tiền mặt\" và nút **Đã nhận <tiền> tiền mặt** (một thao tác nguyên tử, chỉ hiện \"Đã thu\" khi BE trả 200, bấm lại khi đã check-in thì hiện lại vé); quá `releaseAt` thì hướng dẫn check-in vãng lai (R-D09).",
      "Biển số thực tế điền sẵn, sửa được; lệch → `NUMBER_PLATE_NOT_MATCH`.",
      "Gói: hiện `usableNow` và khung giờ vào bãi; nút khóa nếu không dùng được.",
      "Xin quyền camera đúng cách; từ chối vẫn dùng được nhập tay."]),
    ("T-D3", "D", "P1", "M", "Check-in xe vãng lai + xác nhận lên tầng",
     "S-D10, S-D11, widget chọn tầng dùng `GET /floors`.", ["S-D10", "S-D11"], ["pk.checkin_walkin", "pk.floor_gate", "fee.list", "flr.list", "qr.ticket", "rsv.all"],
     ["R-D11", "R-D12", "R-A06"], [],
     ["Biển số dùng cùng regex R-A06; loại xe lấy từ chính sách giá ACTIVE.",
      "Trước khi gửi, tra `rsv.all` theo biển: `PENDING` trong `[reservedStartAt, releaseAt]` thì buộc dẫn tới check-in bằng đặt chỗ; `CONFIRMED` còn hiệu lực hôm nay mà chưa tới giờ thì cảnh báo \"sẽ mất đặt chỗ đã trả\" và cần xác nhận (R-D11).",
      "Khi báo hết chỗ vì đặt chỗ đang giữ, nêu giờ nhả gần nhất của các đặt chỗ `PENDING` (R-B21).",
      "Hết chỗ → `PARKING_CAPACITY_FULL`; tầng chọn tay hết chỗ → `SELECTED_FLOOR_FULL`.",
      "Kết quả có QR mã vé.",
      "Xác nhận lên tầng: đúng tầng → thành công; sai tầng → hiển thị hướng dẫn, phiên giữ nguyên."]),
    ("T-D4", "D", "P2", "L", "Check-out, phạt sai khu, danh sách xe đang gửi",
     "S-D12, S-D13; dùng `PaymentGateway` của B cho VNPay.", ["S-D12", "S-D13"],
     ["pk.checkout_preview", "pk.checkout", "pk.exit_gate", "pk.cb", "ses.current", "ses.penalty_apply", "ses.penalty_cancel"],
     ["R-D13", "R-D14", "R-D15", "R-D16", "R-D19", "R-X05"], ["T-B2", "T-A1"],
     ["Tra theo mã vé hoặc biển số; hiển thị đúng phí từ BE (không tự tính).",
      "Tiền mặt: hiện số tiền cần thu thật lớn và nút **Đã nhận <tiền> tiền mặt** có hộp xác nhận, chỉ bấm mới gọi `POST` check-out (R-D19); nút khóa ngay khi bấm, lỗi mạng thì tra lại trạng thái phiên (`COMPLETED`/`SESSION_NOT_FOUND` sau khi bấm = đã thu, G-37); VNPay hiện QR/WebView và poll phiên tới `COMPLETED`; phí 0đ **tự gửi `CASH`** (BE bắt buộc `paymentMethod`) và không hiện bước chọn.",
      "Màn thanh toán hiển thị `totalFee` của phản hồi `POST`; đổi VNPay sang tiền mặt khi còn `PENDING` phải hỏi xác nhận (R-D13).",
      "Phạt sai khu: nút chỉ hiện ở tầng hỗn hợp; áp/hủy cập nhật phí ngay.",
      "`SESSION_NOT_ACTIVE` (khi gọi thẳng `POST`) và `SESSION_NOT_FOUND` ở bước xem trước đều dẫn tới tra trạng thái phiên và gợi ý Xác nhận lên tầng.",
      "Danh sách phân trang cuộn vô hạn + tìm theo biển/vé."]),
    ("T-D5", "D", "P1", "S", "Trang chủ nhân viên + tra cứu đặt chỗ",
     "S-D07, S-D14.", ["S-D07", "S-D14"], ["ses.current", "rsv.all", "rsv.by_code", "rsv.by_id", "pay.cash_summary"], ["R-D17", "R-D18"], [],
     ["Trang chủ hiển thị số xe đang gửi từ `totalElements` và **tiền mặt đã thu hôm nay** của chính nhân viên (`pay.cash_summary`, R-D18).",
      "Tra cứu: tìm theo mã/biển, lọc trạng thái, giới hạn 200 dòng và báo nếu bị cắt (G-22)."]),
    ("T-D6", "D", "P1", "M", "Trang chủ tài xế + Bảng giá + Thẻ gửi xe",
     "S-D01, S-D05, S-D06.", ["S-D01", "S-D05", "S-D06"], ["mem.my", "rsv.my", "ntf.unread", "ntf.list", "fee.list", "mem.plans_public", "cfg.slots"],
     ["R-D05", "R-D06", "R-D07"], [],
     ["Mỗi thẻ có đủ 4 trạng thái; lỗi một thẻ không làm hỏng cả trang.",
      "Thẻ Xe đang gửi lấy từ đặt chỗ `CHECKED_IN`; phiên không đặt chỗ suy từ thông báo ghi \"tạm\", có test (có/không có `CHECK_OUT`, và ca check-out 0đ không có thông báo).",
      "Bảng giá lọc `ACTIVE`, ghi đúng chính sách hủy/hoàn (R-B08..B10)."]),
    ("T-D7", "D", "P2", "L", "Thông báo + SSE",
     "S-D02, `NotificationRepository`, `SseClient` tự nối lại.",
     ["S-D02"], ["ntf.list", "ntf.unread", "ntf.read", "ntf.read_all", "ntf.stream"], ["R-D01", "R-D02"], ["T-A1"],
     ["SSE gắn `?token=`, tự nối lại ngay khi đứt/hết 55 giây, nối lại sau refresh token.",
      "Sau mỗi lần nối lại tải lại danh sách và số chưa đọc.",
      "Điều hướng từ thông báo đúng 3 kiểu (đặt chỗ/gói/phiên).",
      "Khử trùng thông báo giống nhau trong 1 phút (G-15). Không chạy SSE khi app ở nền."]),
    ("T-D8", "D", "P1", "M", "Lịch sử và chi tiết giao dịch (tài xế)",
     "S-D03, S-D04, phân trang vô hạn.", ["S-D03", "S-D04"], ["tx.my", "tx.my_detail"], ["R-D03", "R-D04", "R-X04"], [],
     ["Phân trang theo `page`/`totalPages`, kéo để làm mới.",
      "Lọc theo loại và trạng thái ở phía app.",
      "Chi tiết dựng khối đúng theo `paymentType`; `REFUNDED` có màu riêng (khi BE xong)."]),
    ("T-D9", "D", "P3", "M", "QA tích hợp + sổ lệch BE",
     "Chạy bộ test ở mục Kiểm thử trên điện thoại thật; duy trì danh sách G-xx và gửi yêu cầu cho BE; cập nhật tài liệu này (`python docs/spec/build.py`).",
     [], [], ["R-X01", "R-X03", "R-X05", "R-X08"], ["T-A1", "T-B8", "T-C2", "T-D4", "T-D7", "T-B7"],
     ["Toàn bộ test loại \"BE\" ở mục Kiểm thử chạy và ghi kết quả; kịch bản liên vai trò TC-X10 chạy được trên 2 điện thoại.",
      "Mỗi lỗi tìm được có phân loại: lỗi app / lỗi BE (G-xx mới).",
      "Tài liệu và `build.py` vẫn pass kiểm tra chéo sau khi cập nhật."]),
]
