# -*- coding: utf-8 -*-
"""Ca kiểm thử. level: 'Fake' = chạy được ngay với dữ liệu giả (P1); 'BE' = cần BE thật (P3);
'Unit' = test đơn vị thuần Dart."""

# id, module, level, tiêu đề, [rules], các bước, kết quả mong đợi
TESTS = [
    # ------------- Xuyên suốt -------------
    ("TC-X01", "X", "Unit", "Định dạng tiền VND", ["R-X04"],
     "`formatVnd(0)`, `formatVnd(110000)`, `formatVnd(1700000)`.",
     "`0đ`, `110.000đ`, `1.700.000đ`."),
    ("TC-X02", "X", "Unit", "Mọi mã lỗi đều có thông điệp tiếng Việt", ["R-X02"],
     "Duyệt 124 mã `ErrorCode` + `REFRESH_TOKEN_MISSING`, `UNAUTHORIZED`, `FORBIDDEN`; gọi `messageFor(code)`.",
     "Không mã nào trả rỗng hoặc tiếng Anh; mã lạ `FOO_BAR` → câu chung kèm `FOO_BAR`."),
    ("TC-X03", "X", "Fake", "4 trạng thái của mọi màn có dữ liệu", ["R-X06"],
     "Với mỗi màn: ép Fake trả chậm, trả rỗng, ném lỗi, trả dữ liệu.",
     "Có vòng quay tải, thông điệp rỗng, thông điệp lỗi + nút Thử lại, và danh sách. Bấm Thử lại gọi lại API."),
    ("TC-X04", "X", "Fake", "Chống bấm đúp", ["R-X06"],
     "Bấm nhanh 3 lần nút Tạo đặt chỗ / Mua gói / Đăng nhập khi Fake đang trễ 400 ms.",
     "Chỉ 1 request được gửi; nút ở trạng thái đang tải."),
    ("TC-X05", "X", "Fake", "Thời gian không bị đổi múi giờ", ["R-X03"],
     "Đặt múi giờ điện thoại sang UTC-8 rồi mở danh sách đặt chỗ có `reservedStartAt = 2026-10-02T06:00:00`.",
     "Vẫn hiển thị `06:00 02/10/2026`."),
    ("TC-X06", "X", "BE", "Đồng hồ hiệu chỉnh theo máy chủ", ["R-X03"],
     "Chỉnh đồng hồ điện thoại lệch +10 phút. Mở chi tiết đặt chỗ `CONFIRMED` có `reservedStartAt` cách 5 phút nữa. Lặp lại khi BE chạy múi giờ UTC với `SERVER_UTC_OFFSET=0` và khi BE chạy giờ Việt Nam với offset mặc định `+07:00`.",
     "App vẫn coi là *chưa* tới giờ (nút Hủy còn) vì dùng `serverNow()` = header `Date` + offset, không dùng đồng hồ máy. Khi offset cấu hình đúng với múi giờ BE thì mọi so sánh đúng; sai offset sẽ lệch đúng số giờ đó (ghi vào hướng dẫn demo)."),
    ("TC-X07", "X", "Fake", "Cô lập vai trò", ["R-X01", "R-X08"],
     "Đăng nhập tài xế rồi mở thẳng `/staff/home`, `/manager/overview`, `/admin/users`, `/scan`. Lặp lại với nhân viên mở `/driver/home` và với quản trị mở `/scan`.",
     "Mỗi lần bị chuyển về trang chủ của chính vai trò; `/scan` chỉ vào được với nhân viên và quản lý."),
    ("TC-X08", "X", "BE", "Đóng WebView trước khi redirect", ["R-X05"],
     "Mở thanh toán đặt chỗ, thanh toán thành công ở VNPay nhưng tắt WebView ngay trước khi chuyển trang.",
     "App vẫn gọi lại chi tiết; nếu BE đã nhận callback thì thấy `CONFIRMED`, nếu chưa thì vẫn `PENDING` và cho thử lại (không báo thành công giả)."),

    # ------------- A -------------
    ("TC-A01", "A", "Fake", "Đăng nhập bằng cả 4 vai trò", ["R-A01", "R-X01"],
     "Lần lượt đăng nhập `driver@`, `staff@`, `manager@`, `admin@parking.vn` với mật khẩu `123123@`; thử thêm mật khẩu sai và email lạ.",
     "Mỗi tài khoản vào đúng vỏ (tài xế: Trang chủ; nhân viên: Ca làm việc; quản lý: Tổng quan; quản trị: Người dùng) với đúng 5 ô tab; sai mật khẩu/email lạ hiện `INVALID_EMAIL_OR_PASSWORD`, không lưu phiên."),
    ("TC-A02", "A", "Fake", "Đăng ký thành công", ["R-A02", "R-A03"],
     "Điền hợp lệ → nhận OTP → nhập đúng.",
     "Vào `/home`, đã có phiên."),
    ("TC-A03", "A", "Fake", "OTP sai / hết hạn / quá 5 lần", ["R-A02"],
     "Nhập sai 1 lần; chờ quá 5 phút; nhập sai 5 lần.",
     "Lần lượt: `INVALID_OTP`, `OTP_EXPIRED`, `OTP_MAX_ATTEMPTS` với thông điệp ở mục Mã lỗi và nút Gửi lại mã đúng lúc."),
    ("TC-A04", "A", "Fake", "Gửi lại OTP có giãn cách", ["R-A02"],
     "Bấm Gửi lại ngay sau khi gửi.",
     "Nút bị khóa 30 giây rồi mới bấm được; gọi lại E02 với đúng body bước 1."),
    ("TC-A05", "A", "Unit", "Kiểm tra mật khẩu và email", ["R-A03"],
     "Mật khẩu `12345` (5 ký tự), `123456`, 101 ký tự, xác nhận lệch; email `a@b`, `a@b.com`.",
     "Từ chối 5 ký tự, 101 ký tự, xác nhận lệch, `a@b`; chấp nhận `123456` và `a@b.com`."),
    ("TC-A06", "A", "BE", "Refresh token một lần cho nhiều request", ["R-A04"],
     "Làm access token hết hạn; bắn song song 3 request.",
     "Chỉ 1 lần gọi `/auth/refresh`; cả 3 request thành công sau đó."),
    ("TC-A07", "A", "BE", "Refresh thất bại thì đăng xuất", ["R-A04"],
     "Thu hồi refresh token ở DB, làm access hết hạn, thực hiện 1 request.",
     "Xóa token, về `/login`, có thông báo phiên hết hạn. Không lặp vô hạn."),
    ("TC-A08", "A", "BE", "401 dạng text thuần", ["R-A04", "R-X02"],
     "Gửi request với token rác.",
     "Không crash vì parse JSON; xử lý như 401 (thử refresh rồi đăng xuất)."),
    ("TC-A09", "A", "Fake", "Quên mật khẩu đủ 3 bước", ["R-A05"],
     "Mở link Quên mật khẩu, cố bấm sang bước 3 khi chưa nhập OTP.",
     "Không cho sang bước 3. Đủ 3 bước thì về Đăng nhập kèm thông báo."),
    ("TC-A10", "A", "Unit", "Regex biển số", ["R-A06"],
     "Kiểm tra `72C2-61690`, `59A-12345`, `59X1-67890`, `51F-1234`, ` 59a-12345 ` (có khoảng trắng, chữ thường); và `59A-123.45`, `5A-12345`, `59A12345`, `59AAA-12345`.",
     "5 mẫu đầu hợp lệ (mẫu có khoảng trắng/chữ thường được chuẩn hóa thành `59A-12345`); 4 mẫu sau không hợp lệ."),
    ("TC-A11", "A", "Fake", "Thêm xe và chọn loại", ["R-A06", "R-A07"],
     "Mở Thêm xe; mở danh sách loại xe.",
     "Chỉ thấy loại xe có chính sách giá `ACTIVE`; chính sách `INACTIVE` không xuất hiện."),
    ("TC-A12", "A", "BE", "Xóa xe bị chặn", ["R-A08"],
     "Xóa xe: (a) đang đỗ, (b) có đặt chỗ `CONFIRMED`, (c) có gói `ACTIVE`, (d) xe sạch.",
     "(a) `VEHICLE_ALREADY_PARKING`, (b) `VEHICLE_HAS_ACTIVE_RESERVATION`, (c) `VEHICLE_HAS_ACTIVE_MEMBERSHIP`, hiển thị đúng lý do; (d) xóa được."),
    ("TC-A13", "A", "BE", "Thêm lại biển số đã xóa", ["R-A08"],
     "Xóa xe sạch rồi thêm lại đúng biển đó.",
     "`VEHICLE_NUMBER_PLATE_EXISTS` hiển thị rõ; không treo."),
    ("TC-A14", "A", "Unit", "Nén ảnh", ["R-A09"],
     "Nén ảnh 4 MB.",
     "Kết quả ≤ 1 MB, định dạng jpeg."),
    ("TC-A15", "A", "Fake", "Gửi đủ 2 mặt giấy tờ", ["R-A09", "R-A10"],
     "Chỉ chọn 1 mặt → nút Gửi; chọn đủ 2 mặt → Gửi; Fake báo lỗi ở mặt sau.",
     "Nút Gửi khóa khi mới 1 mặt; lỗi hiện đúng mặt sau kèm Thử lại, mặt trước không gửi lại."),
    ("TC-A16", "A", "Fake", "Bốn trạng thái xác minh", ["R-A10"],
     "Với xe `NOT_SUBMITTED`, `PENDING`, `REJECTED` (kèm lý do), `VERIFIED`.",
     "Huy hiệu đúng; `REJECTED` hiện lý do và cho gửi lại; `VERIFIED` khóa upload."),
    ("TC-A17", "A", "Fake", "Mua gói với xe chưa xác minh", ["R-A11"],
     "Ở màn Các gói chọn xe `PENDING`.",
     "Có cảnh báo và nút tới màn xác minh; bấm mở đúng `/account/vehicles/:id/verify`."),
    ("TC-A18", "A", "BE", "Đặt chỗ không cần xác minh", ["R-A11"],
     "Với xe `NOT_SUBMITTED` tạo đặt chỗ.",
     "Tạo thành công."),
    ("TC-A19", "A", "BE", "Sửa hồ sơ không làm mất số điện thoại", ["R-A12"],
     "Chỉ đổi họ tên, giữ nguyên SĐT, lưu; tải lại hồ sơ.",
     "SĐT vẫn còn nguyên."),

    # ------------- B -------------
    ("TC-B01", "B", "Fake", "Slot lấy từ cấu hình", ["R-B01"],
     "Fake trả slot đổi thành 05–11, 11–17, 17–23, 23–24 (kết thúc 00:00), rồi thử cấu hình lỗi 23–05.",
     "Chip slot hiển thị đúng khoảng giờ mới, không hard-code 6 giờ; cấu hình 23–05 (qua đêm) bị chặn với thông báo \"khung giờ không hỗ trợ\" vì giá sẽ là 0đ."),
    ("TC-B02", "B", "Unit", "Quy tắc chọn slot liên tiếp", ["R-B02"],
     "Quy tắc: chạm slot chưa chọn và kề dải hiện tại → mở rộng dải; chạm slot chưa chọn nhưng không kề → dải mới chỉ gồm slot đó; chạm slot ở rìa dải → bỏ slot đó; chạm slot ở giữa dải → dải chỉ còn slot đó; chạm slot duy nhất → bỏ chọn. Chạm lần lượt 2, 4, 3, 2, 3, 3.",
     "Sau từng lần chạm: {2}, {4}, {3,4}, {2,3,4}, {3}, {} (rỗng). Không bao giờ có dải đứt đoạn; nút Tạo khóa khi rỗng."),
    ("TC-B03", "B", "Fake", "Giới hạn ngày đặt", ["R-B02"],
     "Mở bộ chọn ngày.",
     "Chọn được từ hôm nay đến hôm nay+7 (8 ngày), các ngày khác bị khóa."),
    ("TC-B04", "B", "Fake", "Slot cuối ngày kết thúc 00:00", ["R-B02", "R-B06"],
     "Chọn slot 4 ngày 05/10.",
     "Hiển thị `18:00 05/10 → 00:00 06/10`; giá 24.000đ (Xe máy) hoặc 60.000đ (Ô tô)."),
    ("TC-B05", "B", "Fake", "Hôm nay: slot đã qua và đang diễn ra", ["R-B03"],
     "Lúc 14:00 mở chọn slot hôm nay.",
     "Slot 1, 2 bị khóa; slot 3 (12–18) chọn được kèm cảnh báo đỏ không hủy/hoàn; slot 4 chọn được không cảnh báo."),
    ("TC-B06", "B", "BE", "Xe đang đỗ không đặt được", ["R-B04"],
     "Dùng xe đang có phiên `ACTIVE` để Tạo.",
     "`VEHICLE_ALREADY_PARKING` thông điệp rõ."),
    ("TC-B07", "B", "BE", "Trùng khung giờ", ["R-B04"],
     "Xe có đặt chỗ `CONFIRMED` 06–18 ngày mai; tạo tiếp 12–24 cùng ngày.",
     "`ACTIVE_RESERVATION_EXISTS`; BE không trả id nên app tìm đặt chỗ trùng trong danh sách `GET /reservations/my` đã tải và hiện link tới đó."),
    ("TC-B08", "B", "Fake", "Chặn trùng ở phía app", ["R-B04"],
     "Fake có đặt chỗ `PENDING` xe A khung 12–18; tạo mới xe A khung 12–18.",
     "App chặn trước khi gọi API, báo trùng kèm hai nút \"Hủy bản cũ\" và \"Thanh toán bản cũ\"."),
    ("TC-B09", "B", "BE", "Hết hạn mức", ["R-B05"],
     "Hạ `reservationQuotaPercent` về 0 rồi Tạo.",
     "`RESERVATION_NOT_AVAILABLE`, giữ lại lựa chọn người dùng để đổi."),
    ("TC-B10", "B", "Unit", "Giá ước tính theo công thức BE", ["R-B06"],
     "Ô tô (10.000đ/h, ×1.5 đêm): slot 1; slot 2; slot 2+3; slot 1..4. Xe máy (4.000đ/h, ×1.5): slot 1; slot 3. Thử giờ slot lẻ 5–11 (đêm 5–6 → 1 giờ đêm).",
     "Ô tô: 90.000đ; 60.000đ; 120.000đ; 270.000đ. Xe máy: 36.000đ; 24.000đ. Slot 5–11 Ô tô: 1 giờ đêm × 15.000 + 5 giờ ngày × 10.000 = 65.000đ."),
    ("TC-B11", "B", "BE", "Số tiền thật thắng giá ước tính", ["R-B06"],
     "Tạo đặt chỗ, so `reservationFee` với giá ước tính.",
     "Màn thanh toán dùng `reservationFee`; nếu lệch thì ghi chú nhỏ, không chặn."),
    ("TC-B12", "B", "BE", "Đặt, trả sau: chỗ được giữ tới giờ bắt đầu + 15 phút", ["R-B07", "R-B13"],
     "Tạo đặt chỗ ngày mai bằng \"Đặt, trả sau\"; chờ vài giờ không bấm gì; mở danh sách và chi tiết.",
     "Đặt chỗ vẫn `PENDING`, hiển thị \"Giữ chỗ đến HH:mm\" (= `reservedStartAt + 15 phút`) và đếm ngược cả ở danh sách lẫn chi tiết; chiếm hạn mức ngày đó; trả tiền được bất kỳ lúc nào trước giờ này (không có cửa sổ 15 phút tính từ lúc bấm)."),
    ("TC-B13", "B", "BE", "Quá giờ giữ chỗ mà chưa trả và chưa tới: tự nguyện bỏ", ["R-B07", "R-B21"],
     "Đặt trả sau một slot bắt đầu 08:00; không trả, không tới; kiểm tra lúc 08:14:59, 08:15:00, 08:15:01 (thao tác trả/hủy/check-in và trạng thái), rồi để nhân viên check-in vãng lai một xe cùng loại khi bãi đang đầy chỉ vì chỗ này.",
     "Đến hết 08:15:00 mọi thao tác vẫn hợp lệ; từ 08:15:01 đặt chỗ là `EXPIRED` (kể cả khi bộ quét chưa chạy), không có giao dịch nào bị mất tiền, tài xế nhận thông báo, app ghi \"Chỗ đã được nhả vì quá giờ giữ\" kèm nút Đặt lại; hạn mức và chỗ vật lý được nhả nên check-in vãng lai thành công."),
    ("TC-B14", "B", "BE", "Trả tiền lại khi lần trước thất bại", ["R-B07", "R-X05"],
     "Đặt trả sau, bấm Thanh toán, hủy ở VNPay, bấm Thanh toán lại trước giờ nhả chỗ.",
     "Nhận URL mới, trả được; kết quả `CONFIRMED` và không còn hạn 15 phút. Nút Thanh toán bị khóa từ 2 phút trước giờ nhả chỗ."),
    ("TC-B15", "B", "BE", "Thanh toán thành công", ["R-X05", "R-B07"],
     "Trả thành công ở VNPay sandbox. (Cần G-01 đã sửa.)",
     "WebView đóng; app gọi lại chi tiết thấy `CONFIRMED`; có QR; Giao dịch có dòng `SUCCESS` đúng số tiền."),
    ("TC-B16", "B", "Fake", "Hủy đặt chỗ chưa trả tiền", ["R-B08"],
     "Hủy đặt chỗ `PENDING`.",
     "Hộp xác nhận ghi \"Hủy miễn phí\"; sau khi hủy hiển thị `CANCELLED`, nút Thanh toán biến mất."),
    ("TC-B17", "B", "Fake", "Hủy đã trả tiền trước giờ bắt đầu → yêu cầu hoàn tiền", ["R-B09", "R-B22"],
     "Đặt chỗ `CONFIRMED` bắt đầu sau 2 giờ; bấm Hủy; đọc hộp xác nhận; thử gửi khi chưa chọn lý do; chọn lý do rồi gửi; bấm gửi hai lần liên tiếp.",
     "Hộp xác nhận ghi \"Đặt chỗ sẽ bị hủy ngay và chỗ được nhả. Tiền chỉ được hoàn nếu quản lý duyệt; nếu bị từ chối bạn không được hoàn tiền\" và số tiền xin hoàn, không hứa thời gian; chưa chọn lý do thì không gửi được; sau khi gửi: đặt chỗ `CANCELLED`, chỗ được nhả ngay, chi tiết hiển thị \"Chờ quản lý duyệt\", Giao dịch có dòng \"Chờ duyệt hoàn tiền\"; bấm gửi hai lần chỉ sinh một yêu cầu."),
    ("TC-B18", "B", "Fake", "Ranh giới giờ bắt đầu", ["R-B09", "R-B10"],
     "Dùng đặt chỗ `CONFIRMED` bắt đầu lúc T; thử tại T-1 giây, T, T+1 giây (đồng hồ test).",
     "T-1s: hiện nút Hủy; T và T+1s: ẩn nút Hủy, hiện \"Đã tới giờ bắt đầu: không hủy/hoàn tiền\"."),
    ("TC-B19", "B", "Fake", "Không đến thì mất tiền", ["R-B10"],
     "Xem hai đặt chỗ `EXPIRED`: (a) đã trả tiền (có giao dịch `RESERVATION` `SUCCESS`) nhưng không đến, (b) chưa từng trả; và (c) trường hợp chưa tải được giao dịch.",
     "(a) ghi \"Không đến: không hoàn tiền\"; (b) và (c) ghi câu trung tính \"Đặt chỗ đã hết hạn\"; cả ba không có nút Hủy hay Hoàn, có nút Đặt lại."),
    ("TC-B20", "B", "BE", "Hủy sau khi bắt đầu bị BE từ chối", ["R-B10"],
     "Gọi hủy đặt chỗ `CONFIRMED` đã quá giờ bắt đầu (ép bằng cách giữ màn mở).",
     "`RESERVATION_CANNOT_BE_CANCELLED` → app tải lại và ẩn nút Hủy. Lý do hiển thị: nếu `serverNow ≥ reservedStartAt` thì \"Đã tới giờ bắt đầu\"; nếu chưa tới giờ mà BE vẫn từ chối (chưa có hủy/hoàn tiền, G-02) thì \"Hệ thống chưa hỗ trợ hủy và hoàn tiền, liên hệ quản lý\", không nói sai là đã tới giờ."),
    ("TC-B21", "B", "BE", "Hủy đặt chỗ rồi vẫn trả bằng URL cũ", ["R-B08"],
     "Bấm Thanh toán (có URL), quay lại hủy đặt chỗ, rồi mở URL cũ trả tiền.",
     "Đặt chỗ vẫn `CANCELLED`; Giao dịch `FAILED`; app giải thích \"bị trừ tiền thì liên hệ quản lý\" (G-05). Đây là lỗi BE được ghi lại, không phải lỗi app."),
    ("TC-B22", "B", "BE", "Check-in trong khung giờ", ["R-B11"],
     "Staff check-in đặt chỗ `CONFIRMED` (a) trước giờ bắt đầu, (b) trong khung giờ, (c) sau giờ kết thúc.",
     "(a) `RESERVATION_NOT_STARTED`, (b) thành công và đặt chỗ thành `CHECKED_IN` + thông báo CHECK_IN, (c) `RESERVATION_NOT_CONFIRMED` nếu bộ hẹn giờ đã chuyển sang `EXPIRED`, hoặc `RESERVATION_EXPIRED` nếu chưa kịp chạy. Màn chi tiết nói rõ \"không có thời gian ân hạn\"."),
    ("TC-B23", "B", "Fake", "QR đặt chỗ", ["R-B12", "R-B20"],
     "Mở chi tiết đặt chỗ `CONFIRMED`, `PENDING`, `EXPIRED`.",
     "`CONFIRMED` và `PENDING`: QR to, quét bằng điện thoại khác ra đúng `RSV-…` (nhân viên dùng để check-in, `PENDING` kèm thu tiền mặt); `EXPIRED`: chỉ hiện mã, không có QR."),
    ("TC-B24", "B", "Fake", "Hai nhóm danh sách", ["R-B13"],
     "Fake có đủ 6 trạng thái.",
     "Sắp tới: PENDING, CONFIRMED, CHECKED_IN; Lịch sử: COMPLETED, CANCELLED, EXPIRED."),
    ("TC-B25", "B", "Unit", "JSON `holdApplied`/`isHoldApplied`", ["R-B13"],
     "Parse cả hai dạng phản hồi.",
     "Cả hai cho cùng giá trị, không ném lỗi."),

    # ------------- C -------------
    ("TC-C01", "C", "Fake", "Gói theo loại xe", ["R-C01"],
     "Chọn xe Ô tô rồi xe Xe máy.",
     "Danh sách gói đổi theo loại xe; giá Ô tô 450.000đ khung giờ, 580.000đ đêm, 1.700.000đ cả ngày."),
    ("TC-C02", "C", "BE", "Giá chốt lúc mua", ["R-C01"],
     "Mua gói, manager đổi giá gói, mở chi tiết gói đã mua.",
     "Hiển thị giá đã mua (`purchasePrice`), không đổi theo giá mới."),
    ("TC-C03", "C", "BE", "Điều kiện mua", ["R-C02"],
     "Mua với: xe chưa `VERIFIED`; gói khác loại xe; hẹn ngày +31 ngày; hẹn ngày ở quá khứ.",
     "`VEHICLE_NOT_VERIFIED`, `INVALID_MEMBERSHIP_PLAN_FOR_VEHICLE_TYPE`, `INVALID_MEMBERSHIP_START_TIME`, `INVALID_MEMBERSHIP_START_TIME`. Chọn \"bắt đầu ngay\" thì không gửi `scheduledStartAt`."),
    ("TC-C04", "C", "BE", "Nhiều gói không chồng nhau", ["R-C03"],
     "Xe có gói Sáng; mua gói Tối; mua gói Sáng lần nữa; mua FULL_TIME.",
     "Gói Tối OK; gói Sáng lần 2 `MEMBERSHIP_TIME_RANGE_CONFLICT`; FULL_TIME `USE_MEMBERSHIP_UPGRADE_FLOW` với nút mở Nâng cấp."),
    ("TC-C05", "C", "BE", "Hạn thanh toán gói 15 phút từ lúc tạo", ["R-C04"],
     "Tạo gói, chờ 16 phút rồi bấm Thanh toán.",
     "`MEMBERSHIP_PAYMENT_EXPIRED`; gói thành `PAYMENT_EXPIRED` (sau tối đa 180 giây ân hạn của job); mua lại được."),
    ("TC-C06", "C", "BE", "Gói chờ thanh toán chặn gói trùng", ["R-C03", "R-C04"],
     "Tạo gói Sáng nhưng không trả; tạo tiếp gói Sáng khác; hủy gói đầu; tạo lại.",
     "Lần 2: `MEMBERSHIP_TIME_RANGE_CONFLICT`; sau khi hủy, tạo lại thành công."),
    ("TC-C07", "C", "BE", "Thanh toán và kích hoạt", ["R-C05", "R-C11", "R-X05"],
     "Mua gói bắt đầu ngay, trả thành công, đóng WebView.",
     "App poll tới khi `ACTIVE`; có `membershipCode` dạng `MBS-xxx-yyy`; QR hiện; `usableNow=true` nếu đang trong khung giờ."),
    ("TC-C08", "C", "BE", "Gói bắt đầu tương lai", ["R-C05"],
     "Mua hẹn bắt đầu sau 5 ngày.",
     "Sau trả tiền `ACTIVE` nhưng `usableNow=false`, ghi \"Có hiệu lực từ <ngày>\"."),
    ("TC-C09", "C", "Fake", "Poll hết 30 giây", ["R-C11"],
     "Fake giữ `PENDING_PAYMENT` mãi sau khi đóng WebView.",
     "Sau 30 giây hiện \"Đang xử lý, kiểm tra lại trong mục Giao dịch\", không báo thành công."),
    ("TC-C10", "C", "Fake", "Gói ACTIVE không hủy/hoàn", ["R-C06"],
     "Mở chi tiết gói `ACTIVE`.",
     "Không có nút Hủy; có dòng \"Gói đã thanh toán không hoàn tiền\"; chỉ có Gia hạn (khi đủ điều kiện) và Nâng cấp (khi đủ điều kiện)."),
    ("TC-C11", "C", "BE", "Hủy gói chờ thanh toán", ["R-C04", "R-C06"],
     "Tạo gói, bấm Hủy trước khi trả.",
     "Gói `CANCELLED`; nếu đã trả thành công trước đó thì `PAYMENT_ALREADY_EXISTS` và app tải lại."),
    ("TC-C12", "C", "BE", "Gia hạn", ["R-C07"],
     "(a) Gói còn 10 ngày bấm Gia hạn; (b) còn 2 ngày; (c) đã hết hạn.",
     "(a) nút ẩn hoặc `MEMBERSHIP_RENEWAL_NOT_OPEN` kèm ngày mở (endAt-3 ngày); (b) thành công, gói mới bắt đầu = `endAt` cũ, mã mới, giá hiện hành; (c) thành công, bắt đầu ngay."),
    ("TC-C13", "C", "BE", "Điều kiện nâng cấp", ["R-C08"],
     "Xe chỉ có gói FULL_TIME; xe chỉ có gói tương lai; xe có đủ 4 gói khung giờ; xe có 1 gói khung giờ.",
     "`FULL_TIME_ALREADY_ACTIVE`; `FUTURE_MEMBERSHIP_EXISTS`; `FULL_TIME_COVERAGE_ALREADY_REACHED`; xe cuối cùng được xem báo giá."),
    ("TC-C14", "C", "Unit", "Tiền được trừ khi nâng cấp", ["R-C08"],
     "Gói Sáng 450.000đ, tổng 30 ngày, mua cách đây 10 ngày (ngày hôm nay tính là đã dùng nên còn 30 − 10 − 1 = 19 ngày); giá FULL_TIME 1.700.000đ. Thêm ca làm tròn: 110.000đ, còn 7/30 ngày.",
     "`450000 × 19 ÷ 30 = 285.000`; phải trả `1.700.000 − 285.000 = 1.415.000đ`. Ca làm tròn: `110000 × 7 ÷ 30 = 25.666,67 → 25.667` (HALF_UP). Tổng được trừ lớn hơn giá FULL_TIME thì phải trả = 0 (không âm)."),
    ("TC-C15", "C", "BE", "Báo giá nâng cấp 15 phút", ["R-C08"],
     "Xem báo giá, chờ 16 phút, bấm Thanh toán.",
     "App đã khóa nút và tự tải lại báo giá khi đếm ngược về 0."),
    ("TC-C16", "C", "BE", "Nâng cấp thành công", ["R-C08", "R-C11"],
     "Nâng cấp và trả tiền.",
     "Gói cũ → `REPLACED`; gói FULL_TIME mới `ACTIVE` bắt đầu ngay, mã mới; `replacement` hiển thị đúng cả hai mã."),
    ("TC-C17", "C", "Fake", "Nâng cấp 0đ", ["R-C08"],
     "Fake trả `payableAmount = 0`.",
     "Nút Thanh toán khóa kèm thông báo \"Không thể thanh toán 0đ, liên hệ quản lý\" (G-16)."),
    ("TC-C18", "C", "Fake", "Đoán gợi ý FULL_TIME", ["R-C09"],
     "Fake trả `recommendFullTime=true` và `false`.",
     "Banner chỉ hiện khi `true`, ghi cả hai số tiền."),
    ("TC-C19", "C", "Fake", "Ghi chú dùng gói", ["R-C10"],
     "Mở chi tiết gói Sáng.",
     "Có đoạn: \"Chỉ vào bãi trong khung 06:00–12:00; ra sau khung giờ bị tính phí lẻ; không giới hạn số lần vào\". Gói hết hạn hiện `EXPIRED` đúng theo API."),

    # ------------- D -------------
    ("TC-D01", "D", "BE", "Thông báo đọc và điều hướng", ["R-D01"],
     "Tải thông báo; chạm vào 3 loại: có `reservationId`, `membershipSubscriptionId`, `parkingSessionId`.",
     "Mở lần lượt chi tiết đặt chỗ, chi tiết gói, thẻ gửi xe; thông báo chuyển sang đã đọc, số chưa đọc giảm."),
    ("TC-D02", "D", "BE", "SSE tự nối lại", ["R-D02"],
     "Mở Home, chờ qua 2 chu kỳ 60 giây, sau đó tạo đặt chỗ mới hoặc để staff check-in.",
     "Vẫn nhận thông báo mới sau khi nối lại; sau mỗi lần nối lại danh sách được tải lại."),
    ("TC-D03", "D", "BE", "SSE khi token hết hạn", ["R-D02", "R-A04"],
     "Để access token hết hạn khi SSE đứt.",
     "App refresh token rồi nối lại; không rơi vào vòng lặp nối lại với token cũ."),
    ("TC-D04", "D", "Fake", "SSE dừng ở nền", ["R-D02"],
     "Đưa app xuống nền 2 phút rồi mở lại.",
     "SSE không chạy khi ở nền; khi mở lại tải lại danh sách và số chưa đọc rồi nối lại."),
    ("TC-D05", "D", "BE", "Giao dịch hiển thị cả PENDING/FAILED", ["R-D03"],
     "Tạo đặt chỗ, bấm Thanh toán rồi hủy ở VNPay; mở tab Giao dịch.",
     "Có dòng `PENDING`/`FAILED` đúng số tiền; `id` dùng để mở chi tiết (Payment id) thành công."),
    ("TC-D06", "D", "Fake", "Lọc và phân trang giao dịch", ["R-D03"],
     "Fake 45 giao dịch; lọc `MEMBERSHIP`; lọc `FAILED`; cuộn tới cuối.",
     "Lọc đúng; tải thêm trang tiếp khi cuộn; không trùng dòng giữa 2 trang."),
    ("TC-D07", "D", "Fake", "Giao dịch theo trạng thái yêu cầu hoàn tiền", ["R-D04", "R-B22"],
     "Fake có 4 yêu cầu hoàn tiền: `REQUESTED`, `APPROVED`, `REFUNDED`, `REJECTED` (kèm lý do).",
     "Giao dịch hiển thị lần lượt \"Chờ duyệt hoàn tiền\", \"Đã duyệt, hoàn vào cuối ngày\", \"Đã hoàn tiền\", \"Không được hoàn: <lý do>\" với màu khác nhau; chi tiết có liên kết tới đặt chỗ đã hủy."),
    ("TC-D08", "D", "Unit", "Suy ra phiên gửi xe từ thông báo", ["R-D05", "R-D06"],
     "Danh sách thông báo: (a) CHECK_IN `parkingSessionId=7` không có CHECK_OUT; (b) CHECK_IN 7 rồi CHECK_OUT 7; (c) rỗng; (d) CHECK_IN có mã `PKG-20261002-0042` trong nội dung.",
     "(a) Có phiên đang gửi 7; (b) không có; (c) không có; (d) `ticketCode = PKG-20261002-0042` tách đúng bằng regex `PKG-\\d{8}-\\d{4}`. Lưu ý (e): phiên đã check-out 0đ không có `CHECK_OUT` nên (a) có thể sai; thẻ này luôn ghi \"tạm\" và ưu tiên đặt chỗ `CHECKED_IN` nếu có."),
    ("TC-D09", "D", "Fake", "Trang chủ chịu lỗi từng thẻ", ["R-D05", "R-X06"],
     "Fake ném lỗi riêng ở thẻ Đặt chỗ sắp tới.",
     "Các thẻ khác vẫn hiển thị; thẻ lỗi có Thử lại."),
    ("TC-D10", "D", "Fake", "Bảng giá & Chính sách", ["R-D07"],
     "Fake có chính sách giá ACTIVE và INACTIVE cùng loại xe.",
     "Chỉ hiện chính sách ACTIVE; đoạn chính sách hủy ghi đúng R-B08..R-B10; giờ slot lấy từ cấu hình."),

    # ------------- Xuyên suốt: bổ sung -------------
    ("TC-X09", "X", "Fake", "Bottom tab và nút giữa nổi bật", ["R-X07"],
     "Với từng vai trò, nhìn thanh tab; bấm từng ô; bấm lại ô đang đứng khi đã đi sâu vào màn con; ở nhân viên/quản lý bấm ô giữa.",
     "Luôn 5 ô, ô giữa là nút tròn nổi lên: tài xế \"Đặt chỗ\", nhân viên và quản lý \"Quét mã\", quản trị \"Thiết lập\". Bấm lại tab quay về màn gốc. \"Quét mã\" mở màn toàn màn hình (không còn thanh tab) và nút đóng quay lại đúng tab cũ."),
    ("TC-X10", "X", "BE", "Kịch bản liên vai trò: đặt chỗ → vào → ra", ["R-X01", "R-X05", "R-D09", "R-D12", "R-D13"],
     "Dùng 2 điện thoại. (1) Tài xế tạo đặt chỗ khung giờ đang diễn ra, trả VNPay sandbox. (2) Nhân viên quét QR trên máy tài xế, xác nhận biển số, Check-in. (3) Nhân viên quét vé ở đúng tầng. (4) Nhân viên Check-out bằng tiền mặt. (5) Tài xế xem lại.",
     "Đặt chỗ: PENDING → CONFIRMED → CHECKED_IN → COMPLETED. Phiên: CHECKED_IN_GATE → ACTIVE → COMPLETED. Tài xế nhận thông báo CONFIRMED, CHECK_IN (CHECK_OUT chỉ có nếu phí > 0; ra trước giờ kết thúc thì phí 0đ nên không có); Giao dịch có dòng RESERVATION `SUCCESS`; tab Đặt chỗ chuyển đặt chỗ sang Lịch sử."),
    ("TC-X11", "X", "BE", "403 không đăng xuất", ["R-X08"],
     "Dùng tài khoản tài xế gọi một endpoint của nhân viên (ép bằng bản debug), rồi quay lại dùng app.",
     "Hiển thị \"Bạn không có quyền thực hiện thao tác này\", phiên vẫn còn, không bị đưa về màn đăng nhập."),
    ("TC-X12", "X", "Unit", "Phân loại mã quét và chuẩn hóa", ["R-X09", "R-D08"],
     "`classifyCode` với `RSV-1002-K3F`, ` rsv-1002-k3f `, `MBS-345-A9F`, `PKG-20261002-0042`, `ABC-123`, chuỗi rỗng.",
     "reservation, reservation (đã trim + hoa), membership, ticket, unknown, unknown. `normalizeCode` trả `RSV-1002-K3F`."),

    # ------------- A bổ sung -------------
    ("TC-A20", "A", "Fake", "Đăng xuất ở từng vai trò", ["R-A13"],
     "Đăng nhập rồi Đăng xuất ở tài xế (tab Tài khoản), nhân viên (tab Tài khoản), quản lý (tab Quản lý), quản trị (tab Tài khoản). Sau đó bấm nút Back của điện thoại.",
     "Mỗi lần về `/login`, không tự đăng nhập lại, không còn lộ màn của phiên cũ; Back không quay lại màn trong app."),
    ("TC-A21", "A", "Fake", "Hồ sơ theo vai trò", ["R-A12", "R-A13"],
     "Mở Hồ sơ ở tài xế và ở nhân viên.",
     "Tài xế sửa được họ tên, SĐT; nhân viên chỉ xem, không có nút Lưu."),

    # ------------- B: Quản trị bãi -------------
    ("TC-B26", "B", "BE", "Thông tin bãi theo vai trò", ["R-B14"],
     "Quản trị sửa tên, địa chỉ, 4 slot, hạn mức 25%. Quản lý mở cùng màn: chỉ thấy 4 slot + hạn mức, thử bỏ trống 1 mốc giờ rồi lưu.",
     "Quản trị lưu được và tạo đặt chỗ mới thấy slot mới (TC-B01). Quản lý thiếu mốc giờ bị báo ngay ở form, không gọi API; giá trị sai nghiệp vụ hiện lỗi BE ở đúng ô."),
    ("TC-B27", "B", "Fake", "Loại xe", ["R-B15"],
     "Mở Loại xe, thêm \"Xe tải nhỏ\" diện tích 20; thử diện tích 0 và âm.",
     "Danh sách có loại mới sau khi tải lại; diện tích ≤ 0 bị chặn ở form."),
    ("TC-B28", "B", "Unit", "Chia khu cho tầng hỗn hợp", ["R-B16"],
     "Bộ kiểm tra cấu hình tầng hỗn hợp với 4 khu A,B,C,D: (A,B | C,D), (A | B,C,D), (A,B,C | D), (A,B,C,D | rỗng), (A,B | C), (A,B | B,C), tầng đơn loại với 2 loại xe.",
     "Hợp lệ: 3 ca đầu. Không hợp lệ: ca có loại không có khu, ca bỏ sót khu, ca có khu trùng; tầng đơn loại chỉ nhận đúng 1 loại xe."),
    ("TC-B29", "B", "BE", "Vòng đời tầng", ["R-B16", "R-X08"],
     "Tạo tầng mới; đổi `ACTIVE` ngay; cấu hình; đổi `ACTIVE`; cấu hình lại khi đang `ACTIVE`; cấu hình lại khi còn xe; tạo tầng cho tới vượt giới hạn.",
     "Tầng mới `MAINTENANCE`; `FLOOR_NOT_CONFIGURED`; sau cấu hình `ACTIVE` được; cấu hình khi `ACTIVE` → `FLOOR_MUST_BE_MAINTENANCE`; còn xe → `FLOOR_HAS_ACTIVE_SESSION`; quá giới hạn → `FLOOR_LIMIT_EXCEEDED`. Mỗi lỗi có nút/hành động gợi ý đúng."),
    ("TC-B30", "B", "BE", "Ưu tiên tầng", ["R-B17"],
     "Đặt ưu tiên 1 cho tầng B2 loại Xe máy khi B1 đã là 1; đặt 0.",
     "`DUPLICATE_VEHICLE_PRIORITY` và `INVALID_PRIORITY_LEVEL` hiển thị rõ; giá trị cũ không bị đổi."),
    ("TC-B31", "B", "BE", "Khu", ["R-B18"],
     "Tạo khu trùng tên; tạo khu vượt số khu của bãi; đổi tên.",
     "`ZONE_NAME_ALREADY_EXISTS`, `ZONE_COUNT_LIMIT_EXCEEDED`; đổi tên thành công cập nhật ở màn cấu hình tầng."),
    ("TC-B32", "B", "BE", "Bảng giá tạo bản mới", ["R-B19"],
     "Sửa giá Ô tô từ 10.000đ lên 12.000đ; xem lịch sử; thử giá âm; tạo đặt chỗ mới.",
     "Bản cũ thành `INACTIVE`, bản mới `ACTIVE`; số âm bị chặn ở form; đặt chỗ mới tính theo 12.000đ (TC-B10 điều chỉnh); đặt chỗ cũ không đổi giá."),

    # ------------- C: Quản lý -------------
    ("TC-C20", "C", "Fake", "Tổng quan quản lý", ["R-C12", "R-X06"],
     "Mở Tổng quan; ép lỗi; kéo làm mới; Fake có tầng 90% và tầng 40%.",
     "Có 4 trạng thái; số liệu doanh thu theo VND; thanh tầng 90% màu đỏ, 40% màu thường; kéo làm mới gọi lại API."),
    ("TC-C21", "C", "BE", "Duyệt xe", ["R-C13", "R-A10"],
     "Tài xế gửi 2 ảnh; quản lý mở danh sách, xem ảnh, thử Từ chối khi để trống lý do, Từ chối có lý do; tài xế gửi lại; quản lý Duyệt; quản lý khác thao tác lại xe vừa duyệt.",
     "Nút Từ chối khóa khi thiếu lý do; xe `REJECTED` hiện đúng lý do bên tài xế; sau duyệt xe `VERIFIED` và tài xế mua gói được; thao tác lần hai → `INVALID_VEHICLE_VERIFICATION_STATUS`, danh sách tự tải lại."),
    ("TC-C22", "C", "Fake", "Form gói theo loại gói", ["R-C14"],
     "Mở tạo gói, chọn loại gói FULL_TIME rồi MORNING.",
     "FULL_TIME chỉ cho chọn khung giờ cả ngày; MORNING chỉ cho khung giờ không cả ngày đang bật."),
    ("TC-C23", "C", "BE", "Ràng buộc giá và trùng gói", ["R-C14"],
     "Tạo FULL_TIME Ô tô 1 tháng với giá ≤ tổng 3 giá khung giờ cao nhất (450.000 + 450.000 + 580.000 = 1.480.000đ); tạo gói trùng bộ (loại xe, loại gói, thời hạn).",
     "`INVALID_MEMBERSHIP_PLAN_PRICE_CONFIGURATION` (cần > 1.480.000đ); `MEMBERSHIP_PLAN_ALREADY_EXISTS`; không có dữ liệu bị lưu dở."),
    ("TC-C24", "C", "Unit", "Phát hiện khung giờ chồng nhau", ["R-C15"],
     "Cặp (06–12, 11–13), (06–12, 12–18), (18–00, 00–06), (22–02, 01–03), (22–02, 03–05), (00–06, 00–06).",
     "Chồng: (06–12,11–13), (22–02,01–03), (00–06,00–06). Không chồng: (06–12,12–18), (18–00,00–06), (22–02,03–05). Khoảng nửa mở [bắt đầu, kết thúc)."),
    ("TC-C25", "C", "BE", "Khung giờ gói", ["R-C15"],
     "Tạo khung `fullDayAccess=true` có kèm giờ; tạo khung giờ bắt đầu = kết thúc; tắt khung đang có gói ACTIVE; tạo mã trùng.",
     "`INVALID_MEMBERSHIP_PLAN_CONFIGURATION` cho 2 ca đầu và ca tắt khung đang dùng; `MEMBERSHIP_TIME_SLOT_ALREADY_EXISTS`; mã được hiển thị viết hoa."),
    ("TC-C26", "C", "Unit", "Trạng thái hết hạn thô", ["R-C16"],
     "Gói `ACTIVE` có `endAt` = quá khứ; `ACTIVE` còn hạn; `CANCELLED` quá khứ.",
     "Hiển thị \"Hết hạn\", \"Đang hiệu lực\", \"Đã hủy\"; so sánh bằng `serverNow()`."),
    ("TC-C27", "C", "BE", "Giám sát", ["R-C17"],
     "Lọc phiên theo trạng thái `COMPLETED`, khoảng ngày hôm nay, nhân viên staff1; cuộn qua nhiều trang; tìm đặt chỗ theo mã.",
     "Kết quả khớp bộ lọc, không trùng dòng giữa các trang; danh sách nhân viên lấy từ `ses.staffs`; tìm đặt chỗ phía app ra đúng dòng."),
    ("TC-C28", "C", "Fake", "Người dùng (quản trị)", ["R-C18"],
     "Mở Người dùng, tìm theo tên và theo email, mở chi tiết.",
     "Lọc đúng; chi tiết chỉ đọc, không có nút sửa/khóa."),

    # ------------- D: Nhân viên cổng -------------
    ("TC-D11", "D", "Fake", "Quét mã: camera và nhập tay", ["R-D08"],
     "Từ chối quyền camera; nhập tay `RSV-1002-K3F`; quét cùng một mã 3 lần liên tiếp; nhập mã `ABC`.",
     "Có hướng dẫn cấp quyền và vẫn nhập tay được; mã chỉ mở màn kết quả một lần; `ABC` báo \"Mã không đúng định dạng\"."),
    ("TC-D12", "D", "BE", "Check-in đặt chỗ phía nhân viên", ["R-D09"],
     "Quét QR đặt chỗ: (a) chưa thanh toán, (b) trong khung giờ, nhập biển số lệch, (c) biển đúng, (d) quét lại sau khi đã check-in.",
     "(a) cảnh báo chặn, nói rõ trạng thái hiện tại (BE: `RESERVATION_NOT_CONFIRMED`); (b) `NUMBER_PLATE_NOT_MATCH` và giữ lại form; (c) thành công, hiện `PKG-…`, tầng, khu; (d) hiển thị \"Đã check-in rồi\" suy từ trạng thái `CHECKED_IN` ở bước tra cứu (BE trả `RESERVATION_NOT_CONFIRMED`, không bao giờ tới `ALREADY_CHECKED_IN`). Thêm (e): đặt chỗ `CONFIRMED` trong giờ nhưng `holdApplied=false` (BE vừa khởi động lại) → \"Hệ thống chưa giữ chỗ, báo quản lý\"."),
    ("TC-D13", "D", "BE", "Check-in gói thành viên", ["R-D10"],
     "Quét QR gói: (a) ngoài khung giờ, (b) xe chưa `VERIFIED`, (c) trong khung giờ, xe đã xác minh.",
     "(a) `MEMBERSHIP_NOT_AVAILABLE` và nút khóa vì `usableNow=false`; (b) `VEHICLE_NOT_VERIFIED`; (c) thành công, tạo phiên loại gói thành viên, `entryCountToday` tăng."),
    ("TC-D14", "D", "BE", "Check-in xe vãng lai", ["R-D11", "R-A06"],
     "Check-in `72C2-61690`; check-in lại; check-in biển chưa từng có `51F-99999`; chọn tầng đã đầy; làm hết chỗ loại xe.",
     "Lần đầu thành công; lần hai `VEHICLE_ALREADY_PARKING`; biển mới được tạo khách vãng lai; `SELECTED_FLOOR_FULL`; `PARKING_CAPACITY_FULL`. Kết quả có QR vé."),
    ("TC-D15", "D", "BE", "Xác nhận lên tầng", ["R-D12"],
     "Quét vé ở sai tầng; quét đúng tầng; check-out khi chưa xác nhận (xem trước và gọi thẳng).",
     "Sai tầng: `correctFloor=false` kèm hướng dẫn và phiên vẫn `CHECKED_IN_GATE`; đúng tầng: `ACTIVE`; quét lại khi đã `ACTIVE`: lỗi `VEHICLE_ALREADY_PARKING` (không đổi gì); check-out sớm: bước xem trước báo `SESSION_NOT_FOUND` (chỉ thấy phiên `ACTIVE`) còn gọi thẳng `POST` báo `SESSION_NOT_ACTIVE`; cả hai dẫn tới tra trạng thái phiên và nút Xác nhận lên tầng."),
    ("TC-D16", "D", "BE", "Check-out", ["R-D13", "R-X05"],
     "Check-out theo mã vé; theo biển số; tiền mặt; VNPay (tài xế quét trả); VNPay rồi bỏ dở; phiên có tổng phí 0đ.",
     "Phí hiển thị đúng bằng BE; tiền mặt xong ngay (`COMPLETED`); VNPay thành công thì poll thấy `COMPLETED`, bỏ dở thì giữ `ACTIVE` và cho thử lại (số tiền không đổi vì giờ ra đã chốt); phí 0đ hoàn tất ngay, không có bước chọn phương thức và tài xế không nhận thông báo CHECK_OUT."),
    ("TC-D17", "D", "BE", "Phí hiển thị khớp công thức BE", ["R-D14"],
     "(a) Vãng lai Ô tô đỗ 2h10 ban ngày (10.000đ/h). (b) Đặt chỗ ra trước `reservedEndAt`. (c) Đặt chỗ ở quá `reservedEndAt` 1h20. (d) Gói khung giờ ra sau khung 40 phút.",
     "(a) 3 giờ × 10.000 = 30.000đ (làm tròn lên). (b) 0đ. (c) 2 giờ × giá lẻ (làm tròn lên). (d) tính phần ngoài khung giờ gói. Với gói qua nửa đêm (VD 22:00–06:00) vào lúc 01:00, BE miễn phí tới 06:00 hôm sau (G-28): ghi nhận là lỗi BE, app vẫn hiển thị số BE trả."),
    ("TC-D18", "D", "BE", "Phạt đỗ sai khu", ["R-D15"],
     "Phiên ở tầng đơn loại; phiên ACTIVE ở tầng hỗn hợp áp phạt; áp lần hai; hủy phạt; áp khi đang chờ thanh toán VNPay.",
     "Nút phạt ẩn ở tầng đơn loại; áp thành công cộng `wrongZoneFee` vào phí; lần hai `WRONG_ZONE_PENALTY_ALREADY_APPLIED`; hủy trừ lại; đang chờ trả `SESSION_CHECKOUT_IN_PROGRESS`."),
    ("TC-D19", "D", "BE", "Xe đang gửi: phân trang và tìm", ["R-D16"],
     "Tạo hơn 25 phiên; cuộn; tìm theo biển và theo mã vé.",
     "Trang 2 nối tiếp không trùng; tìm ra đúng phiên; chạm mở chi tiết có Xác nhận lên tầng/Phạt/Check-out đúng theo trạng thái."),
    ("TC-D20", "D", "Fake", "Tra cứu đặt chỗ giới hạn 200 dòng", ["R-D17"],
     "Fake trả 300 đặt chỗ; tìm theo biển; lọc `CONFIRMED`; chạm vào một đặt chỗ.",
     "Hiển thị 200 dòng đầu kèm thông báo \"Còn 100 kết quả, hãy tìm theo mã/biển số\"; tìm và lọc chạy trên toàn bộ 300; chi tiết có nút Check-in khi đủ điều kiện."),
    ("TC-D21", "D", "Fake", "Trang chủ nhân viên", ["R-D18"],
     "Mở Ca làm việc; Fake trả `totalElements = 128`; ép lỗi.",
     "Hiển thị 128 xe đang gửi; có nút Quét mã và Check-in vãng lai; lỗi chỉ ảnh hưởng ô số liệu, hai nút vẫn dùng được."),

    # ------------- bổ sung sau vòng đối chiếu code -------------
    ("TC-A22", "A", "BE", "Thêm xe nhận lại xe vãng lai", ["R-A14"],
     "Nhân viên check-in vãng lai biển `51F-99999` loại Ô tô; tài xế thêm xe cùng biển và chọn loại Xe máy.",
     "BE gán xe cho tài xế nhưng giữ loại Ô tô; danh sách xe hiển thị **Ô tô** (theo phản hồi), không phải Xe máy."),
    ("TC-X13", "X", "Unit", "ApiClient chịu được phản hồi lạ", ["R-B17", "R-B16", "R-X02"],
     "Mock: 204 không có phần thân; 401 text thuần `Unauthorized`; 403 text thuần `Forbidden`; body chuỗi JSON trần khi gửi đổi trạng thái tầng.",
     "204 trả thành công không lỗi; 401/403 text thuần được xử lý như lỗi quyền; gửi `\"ACTIVE\"` đúng định dạng."),
    ("TC-B33", "B", "BE", "Hạn mức bằng 0 và kiểm lại ở bước thanh toán", ["R-B05", "R-B07"],
     "(a) Tạo đặt chỗ khi hạn mức tính ra 0 (bãi nhỏ). (b) Tạo đặt chỗ lúc còn 1 suất, người khác lấy suất đó rồi mới bấm Thanh toán. (c) Bấm Thanh toán lại sau một lần thất bại khi đã hết suất.",
     "(a) `RESERVATION_NOT_AVAILABLE` ngay khi tạo. (b) và (c) `RESERVATION_NOT_AVAILABLE` hiển thị **ở màn thanh toán** kèm nút quay lại chọn ngày khác."),
    ("TC-B34", "B", "BE", "Không mở lại URL thanh toán đã hết hiệu lực", ["R-B07", "R-B08"],
     "Bấm Thanh toán lấy URL, hủy đặt chỗ (hoặc để hết hạn), rồi quay lại màn thanh toán.",
     "Nút thanh toán biến mất; app không cho mở lại URL cũ. Nếu đã lỡ trả: giao dịch `FAILED` kèm lời nhắc liên hệ quản lý (G-05)."),
    ("TC-B35", "B", "Fake", "Đồng hồ đếm ngược theo giờ nhả chỗ", ["R-B13", "R-B07"],
     "Mở danh sách có đặt chỗ `PENDING`; mở chi tiết; chỉnh giờ giả lập tới 2 phút trước giờ nhả chỗ rồi quá giờ nhả chỗ.",
     "Danh sách và chi tiết cùng hiển thị \"Giữ chỗ đến HH:mm\" và đếm ngược tính từ `reservedStartAt`; còn dưới 2 phút thì khóa nút Thanh toán; quá giờ thì chuyển sang `EXPIRED` sau lần tải lại."),
    ("TC-C29", "C", "BE", "Gia hạn gói đã ngừng bán", ["R-C07"],
     "Quản lý ngừng bán gói; tài xế bấm Gia hạn gói đó; sau đó bấm Gia hạn hai lần liên tiếp ở gói khác.",
     "`MEMBERSHIP_PLAN_NOT_FOUND` hiển thị rõ; lần bấm thứ hai mở lại bản đang chờ thanh toán thay vì báo xung đột."),
    ("TC-C30", "C", "BE", "Nâng cấp: số tiền lấy từ phản hồi tạo", ["R-C08"],
     "Xem báo giá, chờ 5 phút, bấm Nâng cấp; bấm Nâng cấp lần nữa khi bản đầu còn chờ thanh toán.",
     "Màn thanh toán hiển thị `payableAmount` của phản hồi `/upgrade` (có thể khác báo giá); bấm lần hai dùng lại yêu cầu cũ với số tiền cũ."),
    ("TC-C31", "C", "BE", "Trạng thái gói thô ở màn quản lý", ["R-C16"],
     "Tạo gói đã quá `endAt` nhưng còn `ACTIVE` trong DB; mở Người đăng ký.",
     "Dòng gói hiển thị \"Hết hạn\"; số tổng của app cộng từ danh sách (không dùng `activeSubscriptions` của BE, đang gồm cả gói hết hạn)."),
    ("TC-B36", "B", "BE", "Cấu hình bãi không bị ghi đè null", ["R-B14"],
     "Quản trị chỉ sửa tên bãi rồi lưu; quản lý lưu cấu hình thiếu 1 mốc giờ; nhập hạn mức 150.",
     "App luôn gửi đủ mọi trường nên địa chỉ và slot không bị mất; thiếu mốc giờ và hạn mức ngoài 0–100 bị chặn ở form."),
    ("TC-B37", "B", "BE", "Bảng giá: chặn tạo trùng và sửa bản cũ", ["R-B19"],
     "Mở loại xe đã có bản ACTIVE: thử Tạo; mở dòng INACTIVE: thử Sửa.",
     "Không có nút Tạo cho loại xe đã có bản ACTIVE; dòng INACTIVE không có nút Sửa."),

    # ------------- bổ sung vòng 2 -------------
    ("TC-X14", "X", "Unit", "serverNow theo múi giờ BE", ["R-X03"],
     "Header `Date: Thu, 02 Oct 2026 03:00:00 GMT`: tính `serverNow()` với offset `+07:00` và `0`; so với `reservedStartAt = 2026-10-02T10:00:00` (BE giờ VN) và `2026-10-02T03:30:00` (BE giờ UTC).",
     "Offset `+07:00` cho `10:00` → đã tới giờ bắt đầu; offset `0` cho `03:00` → còn 30 phút. Đổi `FakeClock` thì kết quả đổi theo, không phụ thuộc đồng hồ máy."),
    ("TC-A23", "A", "Fake", "Nhân viên mở hồ sơ không gọi API tài xế", ["R-A12"],
     "Đăng nhập nhân viên, mở Tài khoản → Hồ sơ; ghi lại các request.",
     "Chỉ có `GET /auth/me`; không có request nào tới `/drivers/profile`; không thấy lỗi 403."),
    ("TC-B38", "B", "Fake", "Chi tiết đặt chỗ theo trạng thái", ["R-B20", "R-B12"],
     "Mở chi tiết lần lượt cho 6 trạng thái: `PENDING`, `CONFIRMED`, `CHECKED_IN`, `COMPLETED`, `CANCELLED`, `EXPIRED`.",
     "Mỗi trạng thái hiển thị đúng nội dung ở R-B20; chỉ `PENDING`/`CONFIRMED` còn nút thao tác; `PENDING` có nút Thanh toán ngay và Hủy kèm dòng \"Quá giờ này mà chưa trả/chưa tới, chỗ sẽ nhường khách khác\"; `CHECKED_IN` nói ra trước giờ kết thúc không hoàn."),
    ("TC-B39", "B", "BE", "Mở lại đặt chỗ PENDING sau khi đóng app lúc đang trả", ["R-B07", "R-X05"],
     "Bấm Thanh toán, trả thành công ở VNPay, tắt app ngay trước khi callback về; mở lại app và vào đặt chỗ đó.",
     "App gọi lại chi tiết rồi poll 2 giây × 30 giây, hiện \"Đang xác nhận thanh toán\" và ẩn nút Thanh toán; khi `CONFIRMED` thì thông báo thành công. Nếu hết 30 giây vẫn `PENDING` mới hiện lại nút kèm cảnh báo không trả lại."),
    ("TC-B40", "B", "Fake", "Đặt lại từ đặt chỗ đã hết hạn/hủy", ["R-B07", "R-B13"],
     "Mở đặt chỗ `EXPIRED` rồi `CANCELLED`, bấm Đặt lại.",
     "Mở màn tạo đặt chỗ với xe, ngày và slot điền sẵn; nếu ngày/slot đã qua thì chỉ điền xe và báo \"Hãy chọn khung giờ mới\"."),
    ("TC-D22", "D", "Fake", "Check-in vãng lai cho xe đã có đặt chỗ", ["R-D11", "R-D09"],
     "Nhân viên nhập biển `59A-12345` ở Check-in vãng lai; Fake có đặt chỗ `CONFIRMED` đang trong khung giờ của biển đó. Thử thêm biển không có đặt chỗ.",
     "Biển có đặt chỗ: hiện \"Xe có đặt chỗ RSV-…, hãy check-in bằng đặt chỗ\" và nút dẫn tới S-D09, không cho check-in vãng lai ngay; biển không có đặt chỗ: đi tiếp bình thường."),
    ("TC-D23", "D", "Fake", "Quét vé PKG theo trạng thái phiên", ["R-D08", "R-D12", "R-D13"],
     "Quét ba vé: một vé `CHECKED_IN_GATE`, một vé `ACTIVE`, một vé `COMPLETED`.",
     "Vé `CHECKED_IN_GATE` → màn Xác nhận lên tầng; `ACTIVE` → màn Check-out; `COMPLETED` → \"Xe đã ra\". Không có vé nào hiện \"Không tìm thấy phiên\" vì lỗi sai màn."),
    ("TC-D24", "D", "BE", "Check-out 0đ và đổi phương thức", ["R-D13"],
     "(a) Check-out phiên phí 0đ. (b) Check-out VNPay, bỏ dở, rồi chọn tiền mặt. (c) Xem số tiền ở màn thanh toán so với xem trước khi chờ vài phút giữa 2 bước.",
     "(a) app tự gửi `CASH`, không hiện bước chọn, BE không báo thiếu `paymentMethod`; (b) hỏi xác nhận \"link VNPay trước đó sẽ không còn dùng\"; (c) màn thanh toán hiển thị `totalFee` của phản hồi `POST` (giờ ra đã chốt), không phải số xem trước."),
    ("TC-C32", "C", "BE", "Duyệt xe thiếu một mặt giấy tờ", ["R-C13", "R-A09"],
     "Tài xế gửi mặt trước rồi thoát (xe `PENDING` với 1 ảnh); quản lý mở xe đó; tài xế mở lại màn xác minh và gửi nốt mặt sau.",
     "Quản lý thấy thiếu mặt sau: nút Duyệt khóa, chỉ Từ chối kèm lý do; tài xế mở lại thấy mặt sau còn thiếu và gửi bổ sung được; sau đó quản lý Duyệt được."),
    ("TC-C33", "C", "Fake", "Nút Gia hạn sau khi đã gia hạn", ["R-C07", "R-C08"],
     "Gói còn 2 ngày: Gia hạn và trả tiền; quay lại danh sách; mở lại gói cũ; thử Nâng cấp.",
     "Gói cũ không còn nút Gia hạn, ghi \"Đã gia hạn, bắt đầu <ngày>\"; Nâng cấp bị khóa với lý do `FUTURE_MEMBERSHIP_EXISTS` (có gói bắt đầu ở tương lai)."),

    # ------------- mô hình đặt chỗ mới: trả ngay / trả sau -------------
    ("TC-B44", "B", "BE", "Nhả chỗ cho khách vãng lai đúng lúc", ["R-B21", "R-B05"],
     "Bãi chỉ còn đúng 1 chỗ và nó đang bị một đặt chỗ `PENDING` giữ. (a) Trước giờ nhả chỗ nhân viên check-in vãng lai; (b) hủy đặt chỗ đó rồi check-in vãng lai; (c) để đặt chỗ hết hạn rồi check-in vãng lai.",
     "(a) `PARKING_CAPACITY_FULL`, màn nhân viên nêu giờ nhả gần nhất; (b) và (c) check-in vãng lai thành công. Đặt chỗ `CONFIRMED` (đã trả) thì chỗ vẫn bị giữ tới hết khung giờ."),
    ("TC-B45", "B", "Fake", "Ẩn \"Đặt, trả sau\" khi chỗ sắp bị nhả", ["R-B03", "R-B07"],
     "Đặt hôm nay: (a) slot đang diễn ra, (b) slot bắt đầu sau 3 phút nhưng `releaseAt` còn 18 phút, (c) slot đã quá `releaseAt`.",
     "(a) và (c) chỉ còn \"Đặt và trả ngay\" kèm cảnh báo giá tính đủ cả slot; (b) có cả hai nhưng \"trả sau\" ghi rõ giờ nhả chỗ."),
    ("TC-B46", "B", "BE", "Giới hạn 2 đặt chỗ trả sau", ["R-B05", "R-B07"],
     "Tạo liên tiếp 3 đặt chỗ bằng \"Đặt, trả sau\" cho các giờ trong 24 giờ tới, rồi gọi API trực tiếp lần thứ 3; hủy một cái rồi tạo lại; xen vào một \"Đặt và trả ngay\".",
     "Lần thứ 3 bị chặn ở app và BE trả `PENDING_LIMIT_EXCEEDED` khi gọi trực tiếp; sau khi hủy thì tạo được; \"Đặt và trả ngay\" không tính vào giới hạn (có hạn riêng 15 phút) và bị nhả nếu bỏ dở."),
    ("TC-B47", "B", "BE", "Trả ngay thì giữ chắc, không đến thì mất tiền", ["R-B07", "R-B10"],
     "Đặt và trả ngay một slot 08:00–14:00; không tới; kiểm tra lúc 08:20, 13:59 và 14:01.",
     "Lúc 08:20 và 13:59 đặt chỗ vẫn `CONFIRMED` (không có hạn 15 phút vì đã trả) và chỗ vẫn được giữ; 14:01 thành `EXPIRED` với ghi chú \"Không đến: không hoàn tiền\" và Giao dịch không có dòng hoàn tiền."),
    ("TC-D25", "D", "BE", "Thu tiền mặt và check-in đặt chỗ chưa trả", ["R-D09", "R-B11"],
     "Đặt trả sau slot 08:00; tài xế tới lúc 08:10 đưa QR; nhân viên quét. Thử thêm các mốc 07:50, 08:14:59, 08:15:00, 08:15:01.",
     "08:10, 08:14:59 và 08:15:00: thẻ \"Chưa thanh toán, thu <tiền> tiền mặt\" và nút Đã nhận tiền mặt; bấm xong đặt chỗ thành `CHECKED_IN`, Giao dịch có dòng `RESERVATION` `CASH` `SUCCESS`, có mã vé. 07:50: báo chưa tới giờ bắt đầu. 08:15:01: báo đã quá giờ giữ chỗ và dẫn sang check-in vãng lai."),
    ("TC-D26", "D", "Fake", "Quét đặt chỗ đã quá giờ giữ chỗ", ["R-D09", "R-D11"],
     "Fake có đặt chỗ `PENDING` đã quá `releaseAt` (BE chưa kịp đánh dấu `EXPIRED`); nhân viên quét rồi bấm sang check-in vãng lai.",
     "Hiển thị \"Đã quá giờ giữ chỗ (HH:mm)\" và không cho Đã nhận tiền mặt; check-in vãng lai ở S-D10 được phép (không bị chặn bởi đặt chỗ đã quá hạn)."),

    # ------------- vòng 3: ranh giới, nguyên tử, chống lạm dụng -------------
    ("TC-B48", "B", "BE", "releaseAt tính từ slot đầu; đặt trước không làm bãi hôm nay báo đầy", ["R-B07", "R-B05", "R-B21"],
     "(a) Đặt trả sau slot 4 (18:00–24:00): kiểm tra `releaseAt`. (b) Đặt trả sau slot 2+3 (06:00–18:00). (c) Tạo 5 đặt chỗ cho **ngày mai**, rồi để nhân viên check-in vãng lai hôm nay. (d) 23:58 đặt trả sau slot 1 của ngày mai (00:00).",
     "(a) `releaseAt = 18:15` (không phải 24:00), 18:16 thành `EXPIRED`. (b) tính từ đầu slot 2: 06:15. (c) check-in vãng lai hôm nay thành công (chỗ vật lý chỉ bị giữ từ giờ bắt đầu), chỉ hạn mức ngày mai bị trừ. (d) đặt được hay không tuân theo điều kiện 24 giờ/5 phút và tính bằng ngày giờ đầy đủ, không lỗi vì đổi ngày."),
    ("TC-B49", "B", "Fake", "Trả muộn sau giờ bắt đầu phải xác nhận không hoàn", ["R-B07", "R-B10"],
     "Đặt chỗ `PENDING` slot 08:00; lúc 08:12 bấm Thanh toán; thử không tích xác nhận rồi tích; sau khi trả xong xem chi tiết.",
     "Hộp xác nhận đỏ \"Đã tới giờ bắt đầu: thanh toán xong sẽ không hủy, không hoàn tiền\"; chưa tích thì nút Thanh toán khóa; sau khi trả đặt chỗ `CONFIRMED` và không có nút Hủy."),
    ("TC-B50", "B", "BE", "Thanh toán đến muộn/trùng sinh yêu cầu hoàn tiền", ["R-B07", "R-B10", "R-B22"],
     "(a) Bấm Thanh toán lúc `releaseAt − 3 phút`, trì hoãn ở VNPay tới sau `releaseAt` rồi trả thành công; (b) thanh toán xong **trong hạn** nhưng callback về muộn hơn `releaseAt`; (c) đặt chỗ vừa bị hủy rồi vẫn trả bằng URL cũ.",
     "(a) và (c): đặt chỗ vẫn `EXPIRED`/`CANCELLED`, Payment ghi `SUCCESS` kèm cờ trả muộn và có yêu cầu hoàn tiền `REQUESTED` (không để `FAILED` mất tiền), Giao dịch hiển thị \"Thanh toán đến muộn, chờ hoàn tiền\"; (b): thời điểm thanh toán trong hạn nên xác nhận bình thường, đặt chỗ `CONFIRMED`, không có yêu cầu hoàn tiền."),
    ("TC-B51", "B", "BE", "Điều kiện cho phép trả sau", ["R-B03", "R-B05"],
     "Gọi API tạo đặt chỗ trả sau cho: slot bắt đầu sau 3 ngày; slot đang diễn ra; slot có `releaseAt` còn 3 phút.",
     "Cả ba bị `RESERVATION_RELEASE_TOO_SOON` (app đã ẩn nút trả sau theo cùng điều kiện); \"Đặt và trả ngay\" vẫn đặt được."),
    ("TC-B52", "B", "BE", "Đặt và trả ngay có hạn riêng 15 phút", ["R-B07", "R-B05"],
     "Đặt và trả ngay cho slot 7 ngày sau, thoát VNPay không trả; kiểm tra sau 15 phút.",
     "Sau `payNowDeadline` (15 phút) đặt chỗ `EXPIRED`, hạn mức của ngày đó được nhả; nó không chiếm suất 7 ngày và không tính vào giới hạn 2 đặt chỗ trả sau."),
    ("TC-D27", "D", "BE", "Thu tiền mặt không mất tiền khi check-in lỗi", ["R-D09", "R-B11", "R-D19"],
     "(a) Bấm Đã nhận tiền mặt khi `selectTarget` lỗi (tầng không hoạt động); (b) mạng lỗi sau khi BE đã thành công, nhân viên bấm lại; (c) tài xế đang ở VNPay (thanh toán đang chờ) trong lúc nhân viên nhận tiền mặt rồi VNPay trả thành công sau đó.",
     "(a) không có Payment tiền mặt, app báo \"CHƯA ghi nhận thu tiền\"; (b) lần bấm lại coi như thành công và hiện lại vé, chỉ có 1 Payment tiền mặt; (c) thanh toán VNPay đang chờ bị hủy lúc ghi nhận tiền mặt, khoản VNPay tới sau (đặt chỗ đã `CHECKED_IN`) tạo yêu cầu hoàn tiền `REQUESTED` với lý do \"thanh toán trùng\" để quản lý duyệt."),
    ("TC-D28", "D", "Fake", "Chặn vãng lai đúng trường hợp", ["R-D11"],
     "Nhân viên nhập biển có: (a) đặt chỗ `PENDING` cho ngày mai; (b) `PENDING` trong `[start, releaseAt]`; (c) `PENDING` đã quá `releaseAt`; (d) `CONFIRMED` hôm nay chưa tới giờ bắt đầu.",
     "(a) và (c) không chặn; (b) bắt buộc dẫn sang check-in bằng đặt chỗ; (d) cảnh báo \"Xe đã trả chỗ lúc HH:mm, hãy đợi\" và chỉ tiếp tục vãng lai khi nhân viên xác nhận sẽ mất đặt chỗ đã trả."),

    # ------------- hoàn tiền qua duyệt và nút "Đã nhận tiền mặt" -------------
    ("TC-B53", "B", "Fake", "Tài xế theo dõi yêu cầu hoàn tiền", ["R-B22", "R-D04"],
     "Hủy đặt chỗ đã trả; ở phía quản lý lần lượt Duyệt rồi Đã chuyển tiền; sau đó với đặt chỗ khác Từ chối kèm lý do.",
     "Tài xế thấy \"Chờ quản lý duyệt\" → \"Đã duyệt, sẽ hoàn vào cuối ngày\" → \"Đã hoàn <số tiền>\"; với yêu cầu bị từ chối thấy \"Không được hoàn: <lý do>\"; mỗi lần đổi có thông báo; đặt chỗ vẫn `CANCELLED` và chỗ không bị giữ lại."),
    ("TC-B54", "B", "Fake", "Hủy đặt chỗ chưa trả không có hoàn tiền", ["R-B08", "R-B22"],
     "Hủy đặt chỗ `PENDING`.",
     "Hủy miễn phí, không hiện lý do bắt buộc, không có thẻ yêu cầu hoàn tiền, không có dòng nào ở Giao dịch."),
    ("TC-C34", "C", "Fake", "Quản lý duyệt hoàn tiền", ["R-C19"],
     "Mở Duyệt hoàn tiền, xem một yêu cầu `REQUESTED`, bấm Duyệt.",
     "Thẻ hiển thị mã đặt chỗ, biển số, số tiền, giờ đã trả, giờ hủy, còn bao lâu tới giờ bắt đầu, lý do tài xế; sau khi Duyệt yêu cầu chuyển sang Chờ chuyển tiền và huy hiệu số chờ duyệt giảm."),
    ("TC-C35", "C", "Fake", "Từ chối phải có lý do", ["R-C19"],
     "Bấm Từ chối với ô lý do trống, rồi nhập lý do.",
     "Nút xác nhận khóa khi chưa có lý do; sau khi gửi yêu cầu sang `REJECTED` và lý do hiển thị cho tài xế."),
    ("TC-C36", "C", "Fake", "Chuyển tiền cuối ngày và xác nhận", ["R-C19"],
     "Có 3 yêu cầu `APPROVED` trong ngày (100.000đ, 60.000đ, 24.000đ) và 1 yêu cầu duyệt từ hôm qua chưa chuyển; chọn tất cả rồi bấm Đã chuyển tiền; bấm lại lần nữa.",
     "Danh sách gom theo ngày, tổng hôm nay 184.000đ, yêu cầu của hôm qua có cảnh báo quá hạn; hộp xác nhận ghi đúng tổng tiền; sau khi xác nhận các yêu cầu thành `REFUNDED` và tài xế nhận thông báo; bấm lại không đổi gì và không ghi trùng."),
    ("TC-C37", "C", "BE", "Hai quản lý xử lý cùng một yêu cầu", ["R-C19"],
     "Quản lý A và B cùng mở một yêu cầu `REQUESTED`; A duyệt, B bấm Từ chối.",
     "B nhận `REFUND_REQUEST_ALREADY_PROCESSED`, danh sách tự tải lại và yêu cầu hiển thị `APPROVED`; trạng thái không đi ngược."),
    ("TC-D29", "D", "Fake", "Nút \"Đã nhận tiền mặt\" khi check-in đặt chỗ chưa trả", ["R-D19", "R-D09"],
     "Quét đặt chỗ `PENDING` trong giờ giữ chỗ: kiểm tra màn trước khi bấm; bấm nút nhưng chọn Hủy ở hộp xác nhận; rồi xác nhận; ép API lỗi một lần.",
     "Màn hiện số tiền cần thu thật lớn và dòng \"Hãy nhận đủ tiền mặt rồi bấm nút\"; chưa bấm nút thì không có thao tác ghi nhận nào; chọn Hủy ở hộp xác nhận thì không gọi API; xác nhận thì check-in và ghi nhận thu tiền; API lỗi thì hiện \"CHƯA ghi nhận thu tiền\" và bấm lại không ghi trùng."),
    ("TC-D30", "D", "BE", "Check-out bằng tiền mặt có nút \"Đã nhận tiền mặt\"", ["R-D19", "R-D13"],
     "Check-out phiên có phí 30.000đ, chọn Tiền mặt; thử thoát màn khi chưa bấm; bấm Đã nhận tiền mặt; bấm hai lần liên tiếp; mất mạng ngay sau khi BE đã ghi rồi bấm lại.",
     "Chưa bấm nút thì phiên vẫn `ACTIVE` và không có Payment tiền mặt; bấm xong thì `COMPLETED`, Giao dịch có dòng `PARKING_FEE` `CASH` `SUCCESS` ghi nhân viên thu; nút khóa ngay khi bấm nên chỉ ghi một lần; khi mất mạng app tra lại phiên, thấy `COMPLETED`/`SESSION_NOT_FOUND` thì coi là đã thu và hiện lại kết quả thay vì báo \"CHƯA ghi nhận\"; phí 0đ không cần bước này."),

    ("TC-C38", "C", "BE", "Phân quyền các endpoint hoàn tiền", ["R-C19", "R-B22"],
     "Gọi `GET /refund-requests`, `approve`, `reject`, `paid` bằng tài khoản nhân viên và tài xế; tài xế A gọi `ref.my` của đặt chỗ thuộc tài xế B.",
     "Nhân viên và tài xế nhận 403 ở mọi endpoint của quản lý; tài xế A nhận `RESERVATION_NOT_FOUND` với đặt chỗ của B; nhân viên không thấy màn Duyệt hoàn tiền nào trong app."),
    ("TC-C39", "C", "BE", "Đánh dấu đã chuyển tiền theo lô lẫn trạng thái", ["R-C19"],
     "Gửi `paid` với 5 id: 2 `APPROVED`, 1 đã `REFUNDED`, 1 `REQUESTED`, 1 `REJECTED`.",
     "Không lỗi cả lô: 2 id `APPROVED` thành `REFUNDED`, id đã `REFUNDED` coi là thành công, 2 id còn lại nằm trong `skipped` kèm lý do; app hiển thị danh sách bỏ qua."),
    ("TC-C40", "C", "Fake", "Mốc cuối ngày 19:00 và cảnh báo quá hạn", ["R-C19"],
     "Duyệt một yêu cầu lúc 18:55 và một lúc 19:05 (giờ Việt Nam); xem tab Chờ chuyển tiền vào 19:30 và 09:00 hôm sau mà chưa chuyển.",
     "Yêu cầu duyệt 18:55 thuộc ngày hôm nay và bị cảnh báo quá hạn nếu chưa chuyển sau cuối ngày; yêu cầu duyệt 19:05 gom vào ngày làm việc kế tiếp; hôm sau quản lý được nhắc lúc 09:00 và tài xế thấy \"Đang chờ chuyển tiền\"."),
    ("TC-C41", "C", "Fake", "Đã chuyển tiền bắt buộc bằng chứng", ["R-C19"],
     "Duyệt một yêu cầu. Mở hộp Đã chuyển tiền và thử lần lượt: để trống mã giao dịch; không đính ảnh biên lai; chọn tài khoản cá nhân mà không ghi họ tên; rồi nhập đủ.",
     "Mỗi lần thiếu một mục thì nút xác nhận khóa (hoặc báo đúng mục thiếu) và yêu cầu vẫn `APPROVED`; nhập đủ thì thành `REFUNDED` và lưu nguồn tiền, mã giao dịch, ảnh, họ tên chủ tài khoản cá nhân (nếu có)."),
    ("TC-C42", "C", "Fake", "Cảnh báo trùng mã giao dịch ngân hàng", ["R-C19"],
     "Chuyển tiền yêu cầu A với mã `FT26100200001`; duyệt yêu cầu B rồi nhập cùng mã (khác hoa thường) cho B.",
     "App cảnh báo mã đã dùng cho yêu cầu khác và bắt quản lý xác nhận lại trước khi lưu; mã khác thì không cảnh báo."),
    ("TC-C43", "C", "Fake", "Đã duyệt không rút lại được, hoàn 100% hoặc không", ["R-C19", "R-B09"],
     "Duyệt một yêu cầu; tìm cách từ chối hoặc hủy duyệt; thử sửa số tiền hoàn trên màn duyệt.",
     "Không có nút hủy duyệt hay từ chối trên yêu cầu `APPROVED`; thao tác sau trả báo đã xử lý; số tiền hoàn luôn bằng đúng số đã thanh toán, không sửa được."),
    ("TC-B55", "B", "Fake", "Hủy đặt chỗ đã trả phải nhập tài khoản nhận tiền", ["R-B22"],
     "Hủy đặt chỗ `CONFIRMED`: chọn lý do nhưng để trống ngân hàng; nhập số tài khoản `12345` và `12345a67`; rồi nhập `0123456789` với đủ ngân hàng và tên chủ tài khoản.",
     "Nút gửi khóa với ba trường hợp đầu (số tài khoản báo chưa hợp lệ); hợp lệ thì gửi được; chi tiết đặt chỗ hiển thị số đã che `••••6789`, quản lý thấy đủ ở màn duyệt."),
    ("TC-D31", "D", "Fake", "Tiền mặt đã thu hôm nay", ["R-D18", "R-D19", "R-C12"],
     "Nhân viên A nhận tiền mặt 24.000đ (check-in) và 30.000đ (check-out); nhân viên B nhận 10.000đ; mở Trang chủ nhân viên và Tổng quan quản lý.",
     "Nhân viên A thấy 54.000đ, 2 lần; nhân viên B chỉ thấy 10.000đ của mình; quản lý thấy bảng theo từng nhân viên và tổng 64.000đ."),
    ("TC-A24", "A", "Fake", "Không xóa xe khi còn yêu cầu hoàn tiền", ["R-A08"],
     "Hủy đặt chỗ đã trả của xe X (yêu cầu `REQUESTED`), rồi thử xóa xe X; xử lý xong yêu cầu rồi thử lại.",
     "Lần đầu báo \"còn khoản hoàn tiền đang xử lý\" và không xóa; sau khi yêu cầu `REFUNDED`/`REJECTED` thì xóa được."),
]
